import type {
  VideoModelId,
  VideoPromptIntent,
} from "./videoPromptBuilder";

export type VideoPromptPresetCategory =
  | "flight"
  | "airport"
  | "destination"
  | "night"
  | "transition";

export interface VideoPromptPreset {
  id: string;
  label: string;
  icon: string;
  category: VideoPromptPresetCategory;
  description: string;
  draftModelId: VideoModelId;
  finishModelId: VideoModelId;
  qaFocus: string;
  intent: VideoPromptIntent;
}

export const VIDEO_PROMPT_PRESETS: VideoPromptPreset[] = [
  {
    id: "cloud-sea",
    label: "雲海",
    icon: "☁️",
    category: "flight",
    description: "飛行機窓・旅立ち・章間の余韻に使う、静かな雲海のI2V。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "runway-gen-4.5",
    qaFocus: "雲の流れが沸騰せず、翼や水平線が変形しないこと。",
    intent: {
      title: "雲海 / slow push-in",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "The cloud layer drifts very slowly and naturally while the main composition remains stable; no new cloud forms suddenly appear.",
      camera: "slow push-in",
      pace: "subtle",
      lighting: "soft natural morning daylight",
      mood: "quiet, hopeful departure-film realism",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "natural-film",
      captionSpace: true,
      loop: true,
      referenceNotes: "preserve the supplied horizon, cloud silhouette, color palette and any airplane-wing geometry",
    },
  },
  {
    id: "airplane-window",
    label: "飛行機窓・地上",
    icon: "✈️",
    category: "flight",
    description: "離陸前後の窓景色。翼と窓枠を固定し、地上だけに自然な相対運動を出す。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "runway-gen-4.5",
    qaFocus: "翼・窓枠・滑走路の直線が呼吸するように曲がらないこと。",
    intent: {
      title: "飛行機窓・地上 / restrained motion",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "The distant ground and runway scenery move gradually relative to the window view while the wing and window-frame geometry stay completely stable.",
      camera: "locked camera",
      pace: "subtle",
      lighting: "soft natural daylight",
      mood: "observational travel-film realism",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "documentary",
      captionSpace: true,
      loop: false,
      referenceNotes: "preserve the exact wing, window-frame, horizon and runway geometry; animate only physically motivated exterior movement",
    },
  },
  {
    id: "airport-gate-empty",
    label: "無人の搭乗ゲート",
    icon: "🛫",
    category: "airport",
    description: "人物・文字・看板を出さず、空港の静かな出発感だけを補強する。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "runway-gen-4.5",
    qaFocus: "人物の生成、読める案内表示、椅子や窓枠の増殖を即不採用にする。",
    intent: {
      title: "無人の搭乗ゲート / quiet airport",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Only subtle reflections and distant exterior light change gently; the empty gate seating and architecture remain still and structurally unchanged.",
      camera: "slow lateral truck",
      pace: "subtle",
      lighting: "restrained airport practical lighting",
      mood: "quiet pre-departure realism, calm and understated",
      durationSec: 4,
      aspectRatio: "16:9",
      realism: "documentary",
      captionSpace: true,
      loop: false,
      referenceNotes: "preserve empty seating, glass, architecture and perspective; do not invent people, readable signage or screens",
    },
  },
  {
    id: "airport-lobby-empty",
    label: "無人の空港ロビー",
    icon: "🛄",
    category: "airport",
    description: "広い空港ロビーの奥行きを使うB-roll。人を足さず、光と反射だけを控えめに動かす。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "veo-3.1",
    qaFocus: "遠景に人影・顔・文字が発生しないこと。床反射と柱の形状を固定する。",
    intent: {
      title: "無人の空港ロビー / subtle push-in",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Soft ambient reflections shift slightly across the floor while the empty lobby architecture remains stable and unchanged.",
      camera: "slow push-in",
      pace: "subtle",
      lighting: "restrained airport practical lighting",
      mood: "calm modern travel realism",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "documentary",
      captionSpace: true,
      loop: false,
      referenceNotes: "preserve the empty lobby, floor reflections, columns, windows and perspective; no people, text, logos or signs",
    },
  },
  {
    id: "runway-lights",
    label: "滑走路の灯り",
    icon: "🛬",
    category: "flight",
    description: "旅の始まり・カウントダウン前後に使う、直線と光が主役の短尺。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "veo-3.1",
    qaFocus: "滑走路の直線、灯火の間隔、消失点がフレーム間でズレないこと。",
    intent: {
      title: "滑走路の灯り / stable perspective",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Runway lights pass with gentle physically consistent parallax while the runway lines and vanishing point remain perfectly stable.",
      camera: "slow push-in",
      pace: "slow",
      lighting: "cool blue-hour ambient light",
      mood: "restrained cinematic departure, realistic not glossy",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "natural-film",
      captionSpace: true,
      loop: false,
      referenceNotes: "preserve runway line geometry, light spacing, vanishing point and horizon; avoid additional vehicles or aircraft",
    },
  },
  {
    id: "hawaii-sea",
    label: "ハワイの海",
    icon: "🌊",
    category: "destination",
    description: "旅行先の余韻や写真の間に使う海。波だけを小さく自然に動かす。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "runway-gen-4.5",
    qaFocus: "波が巨大化・液体変形せず、水平線と海岸形状が安定していること。",
    intent: {
      title: "ハワイの海 / natural small waves",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Small waves move naturally toward shore with restrained foam motion; the horizon and coastline remain stable with no dramatic wave growth.",
      camera: "locked camera",
      pace: "subtle",
      lighting: "warm golden-hour light",
      mood: "warm relaxed travel memory, natural and understated",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "natural-film",
      captionSpace: true,
      loop: true,
      referenceNotes: "preserve the supplied coastline, horizon, water color and composition; animate only realistic small-wave motion",
    },
  },
  {
    id: "city-night",
    label: "旅先の夜景",
    icon: "🌃",
    category: "night",
    description: "夜の章間や余韻用。発光や粒子を増やさず、反射と遠景光だけを微細に動かす。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "veo-3.1",
    qaFocus: "窓・建物が歪まず、不要なネオン・粒子・読める看板が追加されないこと。",
    intent: {
      title: "旅先の夜景 / restrained lights",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Only distant practical lights and subtle reflections change slightly; buildings and skyline geometry remain completely stable.",
      camera: "locked camera",
      pace: "subtle",
      lighting: "cool blue-hour ambient light",
      mood: "quiet city-night travel memory, realistic and restrained",
      durationSec: 5,
      aspectRatio: "16:9",
      realism: "documentary",
      captionSpace: true,
      loop: true,
      referenceNotes: "preserve skyline, building edges and existing practical lights; do not add text, signs, neon graphics, particles or lens effects",
    },
  },
  {
    id: "door-light",
    label: "扉から差す光",
    icon: "🚪",
    category: "transition",
    description: "章切り替え用。扉そのものを無理に動かさず、光の広がりだけで転換を作る。",
    draftModelId: "seedance-2.0-mini",
    finishModelId: "veo-3.1",
    qaFocus: "扉・床・壁の形状を固定し、光が爆発的に発光しないこと。",
    intent: {
      title: "扉から差す光 / light-only transition",
      mode: "i2v",
      subject: "",
      environment: "",
      action: "Warm light from beyond the doorway expands very gently across the floor while the door, wall and floor geometry remain unchanged.",
      camera: "slow push-in",
      pace: "subtle",
      lighting: "warm soft directional light",
      mood: "hopeful transition, elegant and restrained",
      durationSec: 4,
      aspectRatio: "16:9",
      realism: "natural-film",
      captionSpace: true,
      loop: false,
      referenceNotes: "preserve door, wall, floor and perspective exactly; animate only the physically plausible spread of light without particles or magical effects",
    },
  },
];

export function getVideoPromptPreset(id: string) {
  return VIDEO_PROMPT_PRESETS.find((preset) => preset.id === id);
}
