import { useMemo, useState } from "react";
import { Header } from "../components/Header";
import { useProduction } from "../store/productionStore";
import { useToast } from "../store/toastStore";
import { generateId } from "../lib/ids";
import { compileVideoPrompt, VIDEO_MODELS } from "../lib/videoPromptBuilder";
import { getVideoPromptPreset, VIDEO_PROMPT_PRESETS } from "../lib/videoPromptPresets";
import { suggestVideoPreset } from "../lib/videoShotPlanner";
import {
  buildVideoModelEvidence,
  observedEvidenceForToolPreset,
  promotedObservedModelForPreset,
} from "../lib/videoModelEvidence";
import type { Scene } from "../types/movie";

export function VideoShotPlanner() {
  const {
    selectedMovieId,
    data,
    movieScenes,
    moviePrompts,
    addPrompt,
    linkPromptToScene,
  } = useProduction();
  const { addToast } = useToast();
  const [overrides, setOverrides] = useState<Record<string, string>>({});

  const scenes = selectedMovieId === "all" ? data.scenes : movieScenes;
  const sourcePrompts = selectedMovieId === "all" ? data.prompts : moviePrompts;
  const videoPrompts = sourcePrompts.filter((prompt) => prompt.target === "video");
  const suggestions = useMemo(() => scenes.map((scene) => ({ scene, suggestion: suggestVideoPreset(scene) })), [scenes]);
  const modelEvidence = useMemo(() => buildVideoModelEvidence(data.prompts), [data.prompts]);

  const existingSceneIds = useMemo(() => new Set(videoPrompts.flatMap((prompt) => prompt.relatedSceneIds)), [videoPrompts]);
  const highReady = suggestions.filter(({ scene, suggestion }) => scene.status !== "done" && suggestion.kind === "preset" && suggestion.confidence === "high" && !existingSceneIds.has(scene.sceneId));
  const realMediaCount = suggestions.filter(({ suggestion }) => suggestion.kind === "real-media").length;
  const unclassifiedCount = suggestions.filter(({ suggestion }) => suggestion.kind === "unclassified").length;

  function selectedPresetId(sceneId: string, suggestedPresetId?: string) {
    return overrides[sceneId] ?? suggestedPresetId ?? "";
  }

  function modelRouteForPreset(presetId: string) {
    const preset = getVideoPromptPreset(presetId);
    if (!preset) return undefined;
    const defaultModel = VIDEO_MODELS.find((item) => item.id === preset.draftModelId) ?? VIDEO_MODELS[0];
    const promoted = promotedObservedModelForPreset(modelEvidence, preset.id);
    const learnedModel = promoted ? VIDEO_MODELS.find((item) => item.toolLabel === promoted.tool) : undefined;
    const defaultEvidence = observedEvidenceForToolPreset(modelEvidence, defaultModel.toolLabel, preset.id);
    const model = learnedModel ?? defaultModel;
    return {
      model,
      evidence: learnedModel ? promoted : defaultEvidence,
      defaultEvidence,
      learned: Boolean(learnedModel && learnedModel.id !== preset.draftModelId),
    };
  }

  function createDraft(scene: Scene, presetId: string) {
    if (existingSceneIds.has(scene.sceneId)) return false;
    const preset = getVideoPromptPreset(presetId);
    const route = modelRouteForPreset(presetId);
    if (!preset || !route) return false;
    const durationSec = scene.durationSec > 0 ? Math.max(2, Math.min(preset.intent.durationSec, scene.durationSec)) : preset.intent.durationSec;
    const intent = {
      ...preset.intent,
      title: `${scene.title} / ${preset.label}`,
      durationSec,
    };
    const compiled = compileVideoPrompt(route.model.id, intent);
    const promptId = generateId("prompt");
    const evidenceRate = route.evidence ? Math.round(route.evidence.passRate * 100) : undefined;

    addPrompt({
      promptId,
      title: intent.title,
      target: "video",
      tool: route.model.toolLabel,
      prompt: compiled.prompt,
      negativePrompt: compiled.negativePrompt,
      relatedSceneIds: [],
      relatedMovieIds: [scene.movieId],
      status: "draft",
      resultAssetIds: [],
      notes: [
        `Generated by AI Video Shot Planner / model=${route.model.label}`,
        `mode=${intent.mode}, duration=${intent.durationSec}s, ratio=${intent.aspectRatio}, realism=${intent.realism}`,
        `preset=${preset.id} / finish-candidate=${preset.finishModelId} / qa=${preset.qaFocus}`,
        route.learned
          ? `model-routing=project-observed / preset-default-model=${preset.draftModelId} / reviewed=${route.evidence?.reviewed ?? 0} / pass-rate=${evidenceRate ?? 0}%`
          : `model-routing=preset-default / reviewed=${route.evidence?.reviewed ?? 0}${evidenceRate === undefined ? "" : ` / pass-rate=${evidenceRate}%`}`,
        `scene=${scene.sceneId} / purpose=${scene.purpose} / visual=${scene.visual}`,
        ...compiled.modelNotes,
        ...(compiled.warnings.length ? [`Warnings: ${compiled.warnings.join(" / ")}`] : []),
      ].filter(Boolean).join("\n"),
    });
    linkPromptToScene(promptId, scene.sceneId);
    return true;
  }

  function createOne(scene: Scene, suggestedPresetId?: string) {
    const presetId = selectedPresetId(scene.sceneId, suggestedPresetId);
    if (!presetId) {
      addToast("プリセットを選んでください", "error");
      return;
    }
    if (createDraft(scene, presetId)) addToast(`「${scene.title}」の動画Prompt下書きを作成しました`, "success");
  }

  function createHighConfidence() {
    let created = 0;
    for (const { scene, suggestion } of highReady) {
      const presetId = selectedPresetId(scene.sceneId, suggestion.presetId);
      if (presetId && createDraft(scene, presetId)) created += 1;
    }
    addToast(created > 0 ? `高信頼の動画Promptを${created}件作成しました` : "新しく作成できる高信頼候補はありません", created > 0 ? "success" : "info");
  }

  return (
    <div>
      <Header
        title="AI動画 ショットプランナー"
        description="絵コンテを読み、AI向けB-rollだけを8プリセットへ分類し、プロジェクト全体のQA実績が十分ならモデル選択にも反映します"
        showMovieSelector
      />

      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-6">
        <div className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-4"><p className="text-xs text-navy-400">シーン</p><p className="text-2xl font-bold text-navy-800 dark:text-sand-100">{scenes.length}</p></div>
        <div className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-4"><p className="text-xs text-navy-400">高信頼・未作成</p><p className="text-2xl font-bold text-emerald-700 dark:text-emerald-300">{highReady.length}</p></div>
        <div className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-4"><p className="text-xs text-navy-400">既存動画Promptあり</p><p className="text-2xl font-bold text-navy-800 dark:text-sand-100">{existingSceneIds.size}</p></div>
        <div className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-4"><p className="text-xs text-navy-400">実素材優先</p><p className="text-2xl font-bold text-sky-700 dark:text-sky-300">{realMediaCount}</p></div>
        <div className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-4"><p className="text-xs text-navy-400">未分類</p><p className="text-2xl font-bold text-amber-700 dark:text-amber-300">{unclassifiedCount}</p></div>
      </div>

      <div className="rounded-xl border border-sky-200 dark:border-sky-800 bg-sky-50 dark:bg-sky-900/20 p-4 mb-4">
        <p className="font-bold text-sky-900 dark:text-sky-200">自動化する範囲</p>
        <p className="mt-1 text-sm text-sky-800 dark:text-sky-300">空港・雲海・飛行機・滑走路・海・夜景・扉などの背景/B-rollだけを候補化します。photoSlots・person指定・visual内の人物/家族/友人/犬などは実素材優先として自動除外します。</p>
      </div>

      <div className="rounded-xl border border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-900/20 p-4 mb-6">
        <p className="font-bold text-emerald-900 dark:text-emerald-200">モデル選択もプロジェクト実績から学習</p>
        <p className="mt-1 text-sm text-emerald-800 dark:text-emerald-300">結婚式プロジェクト全体で、同じモデル + presetがQA済み3本以上・採用率67%以上になった組み合わせだけを自動昇格します。3本未満や差が曖昧な場合はpreset既定モデルを維持し、外部ランキングだけでは差し替えません。</p>
      </div>

      <div className="flex flex-wrap items-center gap-3 mb-6">
        <button
          type="button"
          onClick={createHighConfidence}
          disabled={highReady.length === 0}
          className="px-4 py-2.5 text-sm rounded-lg bg-navy-700 text-white hover:bg-navy-800 disabled:opacity-40"
        >
          高信頼の未作成Promptをまとめて作る ({highReady.length})
        </button>
        <span className="text-xs text-navy-400">作成するのはdraftだけです。外部AI生成・credits消費は行いません。</span>
      </div>

      <div className="space-y-4">
        {suggestions.map(({ scene, suggestion }) => {
          const existing = existingSceneIds.has(scene.sceneId);
          const presetId = selectedPresetId(scene.sceneId, suggestion.presetId);
          const preset = getVideoPromptPreset(presetId);
          const route = preset ? modelRouteForPreset(preset.id) : undefined;
          const movie = data.movies.find((item) => item.movieId === scene.movieId);
          const evidenceRate = route?.evidence ? Math.round(route.evidence.passRate * 100) : undefined;
          return (
            <article key={scene.sceneId} className="rounded-xl border border-sand-200 dark:border-navy-600 bg-white dark:bg-navy-800 p-5">
              <div className="flex flex-wrap items-start gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="font-bold text-navy-800 dark:text-sand-100">{scene.title}</h2>
                    {selectedMovieId === "all" && <span className="text-[11px] text-navy-400">{movie?.title ?? scene.movieId}</span>}
                    {existing && <span className="px-2 py-0.5 rounded-full text-[11px] bg-emerald-100 dark:bg-emerald-900/30 text-emerald-800 dark:text-emerald-300">動画Promptあり</span>}
                    {suggestion.kind === "real-media" && <span className="px-2 py-0.5 rounded-full text-[11px] bg-sky-100 dark:bg-sky-900/30 text-sky-800 dark:text-sky-300">実素材優先</span>}
                    {suggestion.kind === "preset" && <span className={`px-2 py-0.5 rounded-full text-[11px] ${suggestion.confidence === "high" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300" : suggestion.confidence === "medium" ? "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300" : "bg-sand-100 text-navy-500 dark:bg-navy-700 dark:text-navy-300"}`}>{suggestion.confidence} confidence</span>}
                  </div>
                  <p className="text-xs text-navy-400 mt-1">{scene.sceneId} · {scene.durationSec}s · {scene.status}</p>
                  <p className="text-sm text-navy-600 dark:text-navy-200 mt-2">{suggestion.reason}</p>
                  {scene.visual && <p className="text-xs text-navy-400 mt-1 line-clamp-2">画: {scene.visual}</p>}
                </div>
              </div>

              {suggestion.kind === "real-media" ? (
                <div className="mt-4 rounded-lg bg-sky-50 dark:bg-sky-900/20 p-3 text-sm text-sky-800 dark:text-sky-300">AI動画を自動生成対象にしません。実写真・実動画を使い、必要なら背景だけ別scene/shotとして分離します。</div>
              ) : (
                <div className="mt-4 flex flex-wrap items-end gap-3">
                  <div className="min-w-[240px] flex-1">
                    <label className="form-label">提案プリセット</label>
                    <select value={presetId} onChange={(e) => setOverrides((prev) => ({ ...prev, [scene.sceneId]: e.target.value }))} className="form-input">
                      <option value="">手動で選ぶ</option>
                      {VIDEO_PROMPT_PRESETS.map((item) => <option key={item.id} value={item.id}>{item.icon} {item.label}</option>)}
                    </select>
                  </div>
                  <div className="min-w-[280px] flex-[1.5] rounded-lg bg-sand-50 dark:bg-navy-700 p-3 text-xs text-navy-500 dark:text-navy-300">
                    {preset && route ? <>
                      <p><strong>試作:</strong> {route.model.label} {route.learned && <span className="ml-1 text-emerald-700 dark:text-emerald-300">● 実績から自動昇格</span>}</p>
                      {route.evidence && <p><strong>project QA:</strong> {route.evidence.reviewed}本 / 採用率 {evidenceRate}%</p>}
                      {!route.learned && route.defaultEvidence?.signal === "caution" && <p className="mt-1 text-amber-700 dark:text-amber-300"><strong>注意:</strong> preset既定モデルは同条件のproject実績で要見直し。代替の優先候補がまだ十分に育っていないため自動変更しません。</p>}
                      <p><strong>仕上げ候補:</strong> {preset.finishModelId}</p>
                      <p><strong>重点QA:</strong> {preset.qaFocus}</p>
                    </> : <p>自動分類できない場合は、背景として本当にAIが必要かを先に確認します。</p>}
                  </div>
                  <button
                    type="button"
                    onClick={() => createOne(scene, suggestion.presetId)}
                    disabled={existing || !presetId || scene.status === "done"}
                    className="px-4 py-2.5 text-sm rounded-lg bg-navy-700 text-white hover:bg-navy-800 disabled:opacity-40"
                  >
                    {existing ? "作成済み" : scene.status === "done" ? "完了scene" : "Prompt下書きを作る"}
                  </button>
                </div>
              )}
            </article>
          );
        })}
      </div>
    </div>
  );
}
