import { useMemo, useState } from "react";
import { Header } from "../components/Header";
import { useProduction } from "../store/productionStore";
import { useToast } from "../store/toastStore";
import { generateId } from "../lib/ids";
import {
  VIDEO_MODELS,
  compileVideoPrompt,
  type MotionPace,
  type RealismProfile,
  type VideoGenerationMode,
  type VideoModelId,
  type VideoPromptIntent,
} from "../lib/videoPromptBuilder";

const cameraPresets = [
  "locked camera",
  "slow push-in",
  "slow lateral truck",
  "gentle pan",
  "subtle handheld observation",
  "slow pull-back",
];

const lightingPresets = [
  "soft natural daylight",
  "warm golden-hour light",
  "soft overcast daylight",
  "restrained airport practical lighting",
  "cool blue-hour ambient light",
];

const starterIntent: VideoPromptIntent = {
  title: "",
  mode: "i2v",
  subject: "",
  environment: "",
  action: "Only the naturally moving elements in the scene move gently; the main composition stays stable.",
  camera: "slow push-in",
  pace: "slow",
  lighting: "soft natural daylight",
  mood: "quiet, elegant travel-film realism",
  durationSec: 5,
  aspectRatio: "16:9",
  realism: "natural-film",
  captionSpace: true,
  loop: false,
  referenceNotes: "preserve the supplied composition, color palette and geometry",
};

function availabilityLabel(value: "recommended" | "available" | "preview") {
  if (value === "recommended") return "推奨";
  if (value === "preview") return "Preview監視";
  return "比較候補";
}

export function VideoPromptBuilder() {
  const { selectedMovieId, addPrompt } = useProduction();
  const { addToast } = useToast();
  const [modelId, setModelId] = useState<VideoModelId>("seedance-2.0-mini");
  const [intent, setIntent] = useState<VideoPromptIntent>(starterIntent);
  const [copied, setCopied] = useState<"prompt" | "negative" | "all" | null>(null);

  const model = VIDEO_MODELS.find((item) => item.id === modelId) ?? VIDEO_MODELS[0];
  const compiled = useMemo(() => compileVideoPrompt(modelId, intent), [modelId, intent]);

  function update<K extends keyof VideoPromptIntent>(key: K, value: VideoPromptIntent[K]) {
    setIntent((prev) => ({ ...prev, [key]: value }));
  }

  async function copy(text: string, kind: "prompt" | "negative" | "all") {
    await navigator.clipboard.writeText(text);
    setCopied(kind);
    window.setTimeout(() => setCopied(null), 1500);
  }

  function saveToPromptBank() {
    const title = intent.title.trim() || `${model.label} ${intent.mode.toUpperCase()} ${intent.durationSec}s`;
    addPrompt({
      promptId: generateId("prompt"),
      title,
      target: "video",
      tool: model.toolLabel,
      prompt: compiled.prompt,
      negativePrompt: compiled.negativePrompt,
      relatedSceneIds: [],
      relatedMovieIds: selectedMovieId !== "all" ? [selectedMovieId] : [],
      status: "draft",
      resultAssetIds: [],
      notes: [
        `Generated by Video Prompt Builder / model=${model.label}`,
        `mode=${intent.mode}, duration=${intent.durationSec}s, ratio=${intent.aspectRatio}, realism=${intent.realism}`,
        ...compiled.modelNotes,
        ...(compiled.warnings.length ? [`Warnings: ${compiled.warnings.join(" / ")}`] : []),
      ].join("\n"),
    });
    addToast("プロンプト管理へ保存しました", "success");
  }

  const fullCopy = [
    `[MODEL] ${model.label}`,
    `[MODE] ${intent.mode} / ${intent.durationSec}s / ${intent.aspectRatio}`,
    "",
    compiled.prompt,
    "",
    `[AVOID] ${compiled.negativePrompt}`,
  ].join("\n");

  return (
    <div>
      <Header
        title="動画プロンプトビルダー"
        description="ショット意図からモデル別プロンプトを組み立て、AIっぽさと手戻りを減らします"
        showMovieSelector
      />

      <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)] gap-6">
        <section className="bg-white dark:bg-navy-800 rounded-xl border border-sand-200 dark:border-navy-600 shadow-sm p-6 space-y-5">
          <div>
            <label className="form-label">生成モデル</label>
            <select value={modelId} onChange={(e) => setModelId(e.target.value as VideoModelId)} className="form-input">
              {VIDEO_MODELS.map((item) => (
                <option key={item.id} value={item.id}>{item.label} — {availabilityLabel(item.availability)}</option>
              ))}
            </select>
            <div className="mt-3 rounded-lg bg-sand-50 dark:bg-navy-700 p-3 text-xs text-navy-500 dark:text-navy-300 space-y-1">
              <p><strong>向いている用途:</strong> {model.bestFor}</p>
              <p><strong>書き方:</strong> {model.promptStrategy}</p>
              <p><strong>尺:</strong> {model.durationHint}</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="form-label">生成モード</label>
              <select value={intent.mode} onChange={(e) => update("mode", e.target.value as VideoGenerationMode)} className="form-input">
                <option value="i2v">Image to Video</option>
                <option value="t2v">Text to Video</option>
                <option value="first-last">First / Last Frame</option>
              </select>
            </div>
            <div>
              <label className="form-label">タイトル（任意）</label>
              <input value={intent.title} onChange={(e) => update("title", e.target.value)} className="form-input" placeholder="例: 雲海 slow push-in v1" />
            </div>
          </div>

          {intent.mode === "t2v" && (
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="form-label">被写体</label>
                <input value={intent.subject} onChange={(e) => update("subject", e.target.value)} className="form-input" placeholder="例: an airplane wing above a sea of clouds" />
              </div>
              <div>
                <label className="form-label">環境</label>
                <input value={intent.environment} onChange={(e) => update("environment", e.target.value)} className="form-input" placeholder="例: soft morning sky at cruising altitude" />
              </div>
            </div>
          )}

          <div>
            <label className="form-label">主動作 — 1ショット1つ</label>
            <textarea value={intent.action} onChange={(e) => update("action", e.target.value)} className="form-input" rows={3} placeholder="何が、どの方向へ、どの程度動くか" />
            <p className="text-xs text-navy-400 mt-1">I2Vでは静止画の内容を長く説明せず、動き・時間変化を中心にします。</p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="form-label">カメラ</label>
              <input list="camera-presets" value={intent.camera} onChange={(e) => update("camera", e.target.value)} className="form-input" />
              <datalist id="camera-presets">
                {cameraPresets.map((value) => <option key={value} value={value} />)}
              </datalist>
            </div>
            <div>
              <label className="form-label">動きの速さ</label>
              <select value={intent.pace} onChange={(e) => update("pace", e.target.value as MotionPace)} className="form-input">
                <option value="locked">固定</option>
                <option value="subtle">ごく僅か</option>
                <option value="slow">ゆっくり</option>
                <option value="medium">中程度</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="form-label">光</label>
              <input list="lighting-presets" value={intent.lighting} onChange={(e) => update("lighting", e.target.value)} className="form-input" />
              <datalist id="lighting-presets">
                {lightingPresets.map((value) => <option key={value} value={value} />)}
              </datalist>
            </div>
            <div>
              <label className="form-label">ムード</label>
              <input value={intent.mood} onChange={(e) => update("mood", e.target.value)} className="form-input" />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div>
              <label className="form-label">尺（秒）</label>
              <input type="number" min={2} max={30} value={intent.durationSec} onChange={(e) => update("durationSec", Number(e.target.value) || 5)} className="form-input" />
            </div>
            <div>
              <label className="form-label">比率</label>
              <select value={intent.aspectRatio} onChange={(e) => update("aspectRatio", e.target.value)} className="form-input">
                <option value="16:9">16:9</option>
                <option value="9:16">9:16</option>
                <option value="1:1">1:1</option>
                <option value="4:3">4:3</option>
                <option value="3:4">3:4</option>
              </select>
            </div>
            <div>
              <label className="form-label">自然さ</label>
              <select value={intent.realism} onChange={(e) => update("realism", e.target.value as RealismProfile)} className="form-input">
                <option value="natural-film">自然なフィルム</option>
                <option value="documentary">観察的・ドキュメンタリー</option>
                <option value="polished">整った広告映像</option>
              </select>
            </div>
          </div>

          <div>
            <label className="form-label">参照素材の役割</label>
            <textarea value={intent.referenceNotes} onChange={(e) => update("referenceNotes", e.target.value)} className="form-input" rows={2} placeholder="例: composition=画像A / camera motion=参考動画B / color mood=画像C" />
            <p className="text-xs text-navy-400 mt-1">参照を増やす時は「何を参照するか」を役割別に書き、全部を真似させないのが安定します。</p>
          </div>

          <div className="flex flex-wrap gap-5 text-sm text-navy-600 dark:text-navy-200">
            <label className="inline-flex items-center gap-2">
              <input type="checkbox" checked={intent.captionSpace} onChange={(e) => update("captionSpace", e.target.checked)} />
              テロップ余白を固定
            </label>
            <label className="inline-flex items-center gap-2">
              <input type="checkbox" checked={intent.loop} onChange={(e) => update("loop", e.target.checked)} />
              ソフトループ前提
            </label>
          </div>
        </section>

        <section className="space-y-4">
          {compiled.warnings.length > 0 && (
            <div className="rounded-xl border border-amber-200 dark:border-amber-700 bg-amber-50 dark:bg-amber-900/20 p-4">
              <h2 className="text-sm font-bold text-amber-800 dark:text-amber-300 mb-2">生成前の注意</h2>
              <ul className="space-y-1 text-xs text-amber-700 dark:text-amber-300 list-disc pl-5">
                {compiled.warnings.map((warning) => <li key={warning}>{warning}</li>)}
              </ul>
            </div>
          )}

          <div className="bg-white dark:bg-navy-800 rounded-xl border border-sand-200 dark:border-navy-600 shadow-sm p-5">
            <div className="flex items-center justify-between gap-3 mb-3">
              <div>
                <p className="text-xs text-navy-400">MODEL-SPECIFIC PROMPT</p>
                <h2 className="font-bold text-navy-800 dark:text-sand-100">{model.label}</h2>
              </div>
              <div className="flex gap-2">
                <button onClick={() => void copy(compiled.prompt, "prompt")} className="px-3 py-1.5 text-xs rounded-lg border border-sand-200 dark:border-navy-600 text-navy-600 dark:text-navy-200 hover:bg-sand-50 dark:hover:bg-navy-700">
                  {copied === "prompt" ? "✓ コピー済み" : "プロンプトをコピー"}
                </button>
                <button onClick={() => void copy(fullCopy, "all")} className="px-3 py-1.5 text-xs rounded-lg bg-navy-700 text-white hover:bg-navy-800">
                  {copied === "all" ? "✓ コピー済み" : "全部コピー"}
                </button>
              </div>
            </div>
            <pre className="text-sm text-navy-700 dark:text-navy-200 bg-sand-50 dark:bg-navy-700 rounded-lg p-4 whitespace-pre-wrap break-words font-mono leading-relaxed select-all">{compiled.prompt}</pre>

            <div className="mt-4 flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-navy-400">AVOID / NEGATIVE</p>
              <button onClick={() => void copy(compiled.negativePrompt, "negative")} className="text-xs text-navy-500 hover:text-navy-700 dark:text-navy-300">
                {copied === "negative" ? "✓ コピー済み" : "コピー"}
              </button>
            </div>
            <pre className="text-xs text-red-700 dark:text-red-300 bg-red-50 dark:bg-red-900/20 rounded-lg p-3 whitespace-pre-wrap break-words font-mono">{compiled.negativePrompt}</pre>

            <button onClick={saveToPromptBank} className="mt-4 w-full px-4 py-2.5 text-sm rounded-lg bg-navy-700 text-white hover:bg-navy-800 font-medium">
              プロンプト管理へ保存
            </button>
          </div>

          <div className="bg-white dark:bg-navy-800 rounded-xl border border-sand-200 dark:border-navy-600 shadow-sm p-5">
            <h2 className="font-bold text-navy-800 dark:text-sand-100 mb-3">AIっぽさを減らすQA</h2>
            <ol className="space-y-2 text-sm text-navy-600 dark:text-navy-200 list-decimal pl-5">
              {compiled.qaChecklist.map((item) => <li key={item}>{item}</li>)}
            </ol>
          </div>

          <div className="bg-sand-50 dark:bg-navy-800 rounded-xl border border-sand-200 dark:border-navy-600 p-5">
            <h2 className="font-bold text-navy-800 dark:text-sand-100 mb-2">運用ルール</h2>
            <ul className="space-y-1.5 text-sm text-navy-600 dark:text-navy-200 list-disc pl-5">
              <li>まずMini/Fastで複数案を比較し、構図や動きが決まってから高品質モデルへ進む。</li>
              <li>AI素材は本編の主役ではなく、3〜5秒前後の背景・つなぎ素材として使う。</li>
              <li>人物・家族・友人・犬は実写真・実動画を優先し、AIで置換しない。</li>
              <li>重要な文字・ロゴ・テロップは生成映像に焼き込まず、CapCut / Motion Studio側で載せる。</li>
              <li>同じ失敗が3回続いたらプロンプトを長くするのではなく、静止画・参照素材・ショット設計を見直す。</li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  );
}
