import {useMemo, useState} from "react";
import {requestMotionZukanSceneFocus} from "../data/motionZukanSceneFocus";
import type {SceneProjectId} from "../data/visualSceneComposer";
import {createHash} from "../lib/browserHash";
import {downloadText} from "../lib/exporters";

type Verdict = "NOT_RUN" | "PASS" | "FAIL";
type RhythmAxis = "openingPace" | "midsectionVariety" | "emotionalHold" | "endingBreathingRoom" | "transitionCadence" | "overallRhythm";
type SceneRhythm = {
  order:number; sceneId:string; sourceRevision:string; productionRole:string|null; patternId:string|null; timingRevision:string|null;
  durationFrames:number; durationSeconds:number; startFrame:number; startSeconds:number; endFrameExclusive:number; endSeconds:number;
  transitionIn:{transition:string;durationFrames:number;durationSeconds:number}|null;
  transitionOut:{transition:string;durationFrames:number;durationSeconds:number}|null;
  overlapFrames:number; overlapSeconds:number; exclusiveFrames:number; exclusiveSeconds:number; overlapRatio:number;
};
type RhythmPass = {
  schemaVersion:"wedding-movie-production-rhythm-pass/v1";
  authority:"DERIVED_WHOLE_PROJECT_RHYTHM_MAP_FROM_CURRENT_RENDERED_REAL_MEDIA_PREVIEW";
  projectId:SceneProjectId;
  source:{previewManifestSha256:string;renderSha256:string};
  fps:number;
  scenes:SceneRhythm[];
  transitions:Array<{fromSceneId:string;toSceneId:string;transition:string;durationFrames:number;durationSeconds:number}>;
  timeline:{totalFrames:number;durationSeconds:number;rawSceneFrames:number;rawSceneSeconds:number;crossDissolveOverlapFrames:number;crossDissolveOverlapSeconds:number};
  mechanicalReviewCues:Array<{code:string;sceneId?:string;fromSceneId?:string;toSceneId?:string;rule:string;valueSeconds?:number;overlapRatio?:number;ratio?:number}>;
  humanReview:{performed:false;axes:Record<RhythmAxis,"NOT_RUN">};
  summary:{sceneCount:number;transitionCount:number;mechanicalReviewCueCount:number;humanRhythmReview:"NOT_RUN";productionReady:false};
  evidenceBoundary:{humanRhythmReviewPerformed:false;humanVisualQa:"NOT_RUN";remotionStudioGuiActual:"NOT_RUN";palmierGuiActual:"NOT_RUN";macDaVinciGuiActual:"NOT_RUN";productionReady:false};
};
type RhythmCurrentness = {
  schemaVersion:"wedding-movie-production-rhythm-pass-currentness/v1";
  authority:"LIVE_REVALIDATION_OF_PRODUCTION_RHYTHM_PASS_AGAINST_CURRENT_RENDERED_REAL_MEDIA_PREVIEW";
  projectId:SceneProjectId; state:"CURRENT"|"STALE";
  source:{rhythmPassSha256:string|null;previewManifestSha256:string|null;renderSha256:string|null};
  checks:Record<string,boolean>; mismatches:string[];
  evidenceBoundary:{humanRhythmReviewPerformed:false;humanVisualQa:"NOT_RUN";remotionStudioGuiActual:"NOT_RUN";palmierGuiActual:"NOT_RUN";macDaVinciGuiActual:"NOT_RUN";productionReady:false};
};
type HumanAxis={verdict:Verdict;notes:string};
const AXES:Array<{key:RhythmAxis;label:string;prompt:string}>=[
  {key:"openingPace",label:"Opening pace",prompt:"冒頭が遅すぎず、視聴者が自然に入れるか"},
  {key:"midsectionVariety",label:"Midsection variety",prompt:"中盤が同じ長さ・同じ切替の連打になっていないか"},
  {key:"emotionalHold",label:"Emotional hold",prompt:"感情を見せたい写真・言葉に十分な余韻があるか"},
  {key:"endingBreathingRoom",label:"Ending breathing room",prompt:"終盤が詰まりすぎず、締めに呼吸できる間があるか"},
  {key:"transitionCadence",label:"Transition cadence",prompt:"Cross Dissolveの頻度・長さが映像テンポを邪魔していないか"},
  {key:"overallRhythm",label:"Overall rhythm",prompt:"Opening/Profile全体を通して意図した緩急になっているか"},
];
const initialAxes=()=>Object.fromEntries(AXES.map(({key})=>[key,{verdict:"NOT_RUN",notes:""}])) as Record<RhythmAxis,HumanAxis>;
function validRhythm(value:unknown,projectId:SceneProjectId):value is RhythmPass{if(!value||typeof value!=="object")return false;const v=value as Partial<RhythmPass>;return v.schemaVersion==="wedding-movie-production-rhythm-pass/v1"&&v.authority==="DERIVED_WHOLE_PROJECT_RHYTHM_MAP_FROM_CURRENT_RENDERED_REAL_MEDIA_PREVIEW"&&v.projectId===projectId&&Array.isArray(v.scenes)&&Array.isArray(v.transitions)&&Array.isArray(v.mechanicalReviewCues)&&v.humanReview?.performed===false&&v.summary?.humanRhythmReview==="NOT_RUN"&&v.summary?.productionReady===false&&v.evidenceBoundary?.humanRhythmReviewPerformed===false&&v.evidenceBoundary?.humanVisualQa==="NOT_RUN"&&v.evidenceBoundary?.remotionStudioGuiActual==="NOT_RUN"&&v.evidenceBoundary?.palmierGuiActual==="NOT_RUN"&&v.evidenceBoundary?.macDaVinciGuiActual==="NOT_RUN"&&v.evidenceBoundary?.productionReady===false;}
function validCurrentness(value:unknown,projectId:SceneProjectId):value is RhythmCurrentness{if(!value||typeof value!=="object")return false;const v=value as Partial<RhythmCurrentness>;return v.schemaVersion==="wedding-movie-production-rhythm-pass-currentness/v1"&&v.authority==="LIVE_REVALIDATION_OF_PRODUCTION_RHYTHM_PASS_AGAINST_CURRENT_RENDERED_REAL_MEDIA_PREVIEW"&&v.projectId===projectId&&(v.state==="CURRENT"||v.state==="STALE")&&Array.isArray(v.mismatches)&&!!v.checks&&v.evidenceBoundary?.humanRhythmReviewPerformed===false&&v.evidenceBoundary?.humanVisualQa==="NOT_RUN"&&v.evidenceBoundary?.remotionStudioGuiActual==="NOT_RUN"&&v.evidenceBoundary?.palmierGuiActual==="NOT_RUN"&&v.evidenceBoundary?.macDaVinciGuiActual==="NOT_RUN"&&v.evidenceBoundary?.productionReady===false;}
const fmt=(seconds:number)=>`${seconds.toFixed(2)}s`;

export function WeddingProductionRhythmReviewCard({projectId}:{projectId:SceneProjectId}){
  const [rhythm,setRhythm]=useState<RhythmPass|null>(null); const [rhythmSha,setRhythmSha]=useState<string|null>(null);
  const [currentness,setCurrentness]=useState<RhythmCurrentness|null>(null); const [currentnessSha,setCurrentnessSha]=useState<string|null>(null);
  const [previewSha,setPreviewSha]=useState<string|null>(null); const [renderSha,setRenderSha]=useState<string|null>(null);
  const [axes,setAxes]=useState<Record<RhythmAxis,HumanAxis>>(initialAxes); const [reviewer,setReviewer]=useState(""); const [reviewedAt,setReviewedAt]=useState(""); const [performed,setPerformed]=useState(false);
  const [selectedScene,setSelectedScene]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  async function loadRhythm(file:File|null){if(!file)return;setError(null);try{const b=await file.arrayBuffer();const v=JSON.parse(new TextDecoder().decode(b));if(!validRhythm(v,projectId))throw new Error("rhythm pass schema / authority / evidence boundary mismatch");setRhythm(v);setRhythmSha(await createHash(b));setCurrentness(null);setCurrentnessSha(null);setPreviewSha(null);setRenderSha(null);setAxes(initialAxes());setReviewer("");setReviewedAt("");setPerformed(false);setSelectedScene(v.scenes[0]?.sceneId??null);}catch(e){setRhythm(null);setRhythmSha(null);setError(e instanceof Error?e.message:"invalid rhythm pass");}}
  async function loadCurrentness(file:File|null){if(!file)return;setError(null);try{const b=await file.arrayBuffer();const v=JSON.parse(new TextDecoder().decode(b));if(!validCurrentness(v,projectId))throw new Error("rhythm currentness schema / authority / boundary mismatch");setCurrentness(v);setCurrentnessSha(await createHash(b));}catch(e){setCurrentness(null);setCurrentnessSha(null);setError(e instanceof Error?e.message:"invalid rhythm currentness");}}
  async function loadPreview(file:File|null){if(!file)return;setPreviewSha(await createHash(await file.arrayBuffer()));}
  async function loadRender(file:File|null){if(!file)return;setRenderSha(await createHash(await file.arrayBuffer()));}
  const gate=useMemo(()=>{if(!rhythm||!rhythmSha)return{state:"NOT_RUN" as const,reasons:["RHYTHM_PASS_NOT_LOADED"]};const reasons:string[]=[];if(!currentness)reasons.push("STRICT_CURRENTNESS_NOT_LOADED");else{if(currentness.state!=="CURRENT"||currentness.mismatches.length)reasons.push(...(currentness.mismatches.length?currentness.mismatches:["STRICT_CURRENTNESS_STALE"]));if(!Object.values(currentness.checks).every(Boolean))reasons.push("STRICT_CURRENTNESS_CHECK_FALSE");if(currentness.source.rhythmPassSha256!==rhythmSha)reasons.push("RHYTHM_PASS_SHA_MISMATCH");if(previewSha!==currentness.source.previewManifestSha256)reasons.push("PREVIEW_MANIFEST_SHA_NOT_CURRENT");if(renderSha!==currentness.source.renderSha256)reasons.push("RENDER_SHA_NOT_CURRENT");}return{state:reasons.length?"BLOCKED" as const:"CURRENT" as const,reasons};},[rhythm,rhythmSha,currentness,previewSha,renderSha]);
  const selected=rhythm?.scenes.find((scene)=>scene.sceneId===selectedScene)??null;
  const allReviewed=AXES.every(({key})=>axes[key].verdict!=="NOT_RUN"); const finalVerdict:Verdict=!allReviewed?"NOT_RUN":AXES.some(({key})=>axes[key].verdict==="FAIL")?"FAIL":"PASS";
  const canExport=gate.state==="CURRENT"&&performed&&allReviewed&&reviewer.trim().length>0&&reviewedAt.trim().length>0;
  function focusScene(scene:SceneRhythm){if(gate.state!=="CURRENT")return;requestMotionZukanSceneFocus({projectId,sceneId:scene.sceneId,sourceRevision:scene.sourceRevision,axis:"PACING",surface:"SCENE_TIMING_AND_A_B_COMPARE",requestedBy:"PROJECT_RHYTHM_CORRECTION_QUEUE"});}
  function exportReview(){if(!rhythm||!rhythmSha||!currentnessSha||!canExport)return;const output={schemaVersion:"wedding-movie-production-rhythm-human-review/v1",authority:"EXPLICIT_HUMAN_WHOLE_PROJECT_RHYTHM_REVIEW_BOUND_TO_CURRENT_RHYTHM_PASS",projectId,source:{rhythmPassSha256:rhythmSha,currentnessSha256:currentnessSha,previewManifestSha256:previewSha,renderSha256:renderSha},review:{performed:true,reviewer:reviewer.trim(),reviewedAt:reviewedAt.trim(),axes,finalVerdict},summary:{allAxesReviewed:true,failedAxes:AXES.filter(({key})=>axes[key].verdict==="FAIL").map(({key})=>key),productionReady:false},evidenceBoundary:{humanRhythmReviewPerformed:true,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"This artifact records only an explicit Human whole-project rhythm review against the SHA-bound CURRENT rhythm map. It does not promote GUI Actual evidence, Human visual QA, or productionReady."}};downloadText(`${projectId}-production-rhythm-human-review.json`,`${JSON.stringify(output,null,2)}\n`,`application/json`);}
  const strictCommand=`node --no-warnings motion-studio/scripts/verify-wedding-project-production-rhythm-pass-currentness.mts --rhythm-pass=out/qa/project-real-media-preview/${projectId}/${projectId}-production-rhythm-pass.json --strict-current --output=out/qa/project-real-media-preview/${projectId}/${projectId}-production-rhythm-pass-currentness.json`;
  return <section className="mt-3 border-2 border-violet-300 p-3 dark:border-violet-800" data-production-rhythm-review={projectId} data-production-rhythm-current={gate.state} data-human-rhythm-review={performed?finalVerdict:"NOT_RUN"}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-[8px] font-semibold tracking-[0.14em] text-violet-700 dark:text-violet-300">WHOLE-PROJECT PRODUCTION RHYTHM / {projectId.toUpperCase()}</p><p className="mt-1 text-[11px] font-semibold">Scene尺・exclusive hold・Cross Dissolve overlapを1本のtimelineで確認</p><p className="mt-1 text-[8px] opacity-70">mechanical cueは注意箇所の抽出だけで品質判定ではありません。Human reviewは明示操作までNOT_RUN。</p></div><span className="border border-violet-300 px-2 py-1 font-mono text-[8px]">{gate.state}</span></div>
    <div className="mt-3 grid gap-2 md:grid-cols-4"><label className="border p-2 text-[8px]">Rhythm pass<input className="mt-1 block w-full text-[8px]" type="file" accept="application/json" onChange={(e)=>void loadRhythm(e.target.files?.[0]??null)}/></label><label className="border p-2 text-[8px]">Strict currentness<input className="mt-1 block w-full text-[8px]" type="file" accept="application/json" onChange={(e)=>void loadCurrentness(e.target.files?.[0]??null)}/></label><label className="border p-2 text-[8px]">Current preview manifest<input className="mt-1 block w-full text-[8px]" type="file" accept="application/json" onChange={(e)=>void loadPreview(e.target.files?.[0]??null)}/></label><label className="border p-2 text-[8px]">Current rendered MP4<input className="mt-1 block w-full text-[8px]" type="file" accept="video/mp4" onChange={(e)=>void loadRender(e.target.files?.[0]??null)}/></label></div>
    <div className="mt-2 border p-2 text-[8px]"><p className="font-semibold">Canonical strict-current</p><code className="block overflow-x-auto whitespace-nowrap">{strictCommand}</code>{gate.reasons.length?<p className="mt-1 text-amber-700 dark:text-amber-300">{gate.reasons.join(" / ")}</p>:null}</div>
    {rhythm?<><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="border p-2 text-[8px]"><p className="opacity-60">ACTUAL RUNTIME</p><p className="font-mono text-[13px]">{fmt(rhythm.timeline.durationSeconds)} / {rhythm.timeline.totalFrames}f</p></div><div className="border p-2 text-[8px]"><p className="opacity-60">RAW SCENE TIME</p><p className="font-mono text-[13px]">{fmt(rhythm.timeline.rawSceneSeconds)}</p></div><div className="border p-2 text-[8px]"><p className="opacity-60">CROSS DISSOLVE OVERLAP</p><p className="font-mono text-[13px]">−{fmt(rhythm.timeline.crossDissolveOverlapSeconds)} / {rhythm.timeline.crossDissolveOverlapFrames}f</p></div></div>
      <div className="mt-3 flex h-12 w-full overflow-hidden border" data-production-rhythm-timeline>{rhythm.scenes.map((scene)=>{const width=Math.max(1,(scene.exclusiveSeconds/rhythm.timeline.durationSeconds)*100);return <button key={scene.sceneId} type="button" style={{width:`${width}%`}} className={`min-w-[18px] border-r px-1 text-[7px] ${selectedScene===scene.sceneId?"font-bold ring-2 ring-inset":""}`} title={`${scene.sceneId} ${fmt(scene.durationSeconds)} / exclusive ${fmt(scene.exclusiveSeconds)}`} onClick={()=>setSelectedScene(scene.sceneId)}>{scene.order}</button>;})}</div>
      <div className="mt-2 grid gap-1 sm:grid-cols-2 xl:grid-cols-3">{rhythm.scenes.map((scene)=><button key={scene.sceneId} type="button" className={`border p-2 text-left text-[7px] ${selectedScene===scene.sceneId?"border-violet-500":""}`} onClick={()=>setSelectedScene(scene.sceneId)} data-production-rhythm-scene={scene.sceneId}><div className="flex justify-between"><strong>{scene.order}. {scene.sceneId}</strong><span>{fmt(scene.durationSeconds)}</span></div><p>exclusive {fmt(scene.exclusiveSeconds)} / overlap {fmt(scene.overlapSeconds)} ({Math.round(scene.overlapRatio*100)}%)</p><p className="font-mono opacity-60">start {fmt(scene.startSeconds)} → end {fmt(scene.endSeconds)}</p></button>)}</div>
      {selected?<div className="mt-3 border border-violet-200 p-2 text-[8px]"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{selected.sceneId} / {selected.productionRole}</p><p>{fmt(selected.durationSeconds)} · exclusive {fmt(selected.exclusiveSeconds)} · overlap {fmt(selected.overlapSeconds)}</p><p>IN {selected.transitionIn?`${selected.transitionIn.transition} ${fmt(selected.transitionIn.durationSeconds)}`:"CUT/START"} / OUT {selected.transitionOut?`${selected.transitionOut.transition} ${fmt(selected.transitionOut.durationSeconds)}`:"CUT/END"}</p></div><button type="button" disabled={gate.state!=="CURRENT"} onClick={()=>focusScene(selected)} className="border border-violet-300 px-2 py-1 disabled:opacity-40">Timing/Rhythm editorへ</button></div></div>:null}
      <div className="mt-3 border border-amber-200 p-2"><p className="text-[8px] font-semibold">MECHANICAL REVIEW CUES / quality verdictではありません</p>{rhythm.mechanicalReviewCues.length===0?<p className="mt-1 text-[8px]">閾値上の注意cueなし。</p>:<div className="mt-1 grid gap-1">{rhythm.mechanicalReviewCues.map((cue,index)=>{const sceneId=cue.sceneId??cue.toSceneId??cue.fromSceneId;const scene=rhythm.scenes.find((item)=>item.sceneId===sceneId);return <div key={`${cue.code}:${index}`} className="flex flex-wrap items-center justify-between gap-2 border p-2 text-[7px]"><div><strong>{cue.code}</strong><p>{cue.rule}</p><p>{cue.sceneId??`${cue.fromSceneId} → ${cue.toSceneId}`}</p></div>{scene?<button type="button" disabled={gate.state!=="CURRENT"} onClick={()=>focusScene(scene)} className="border px-2 py-1 disabled:opacity-40">このSceneを調整</button>:null}</div>;})}</div>}</div>
    </>:null}
    <div className={`mt-3 border-2 p-3 ${gate.state==="CURRENT"?"border-emerald-300":"border-amber-300"}`} data-production-rhythm-human-operator><div className="flex flex-wrap justify-between gap-2"><div><p className="text-[8px] font-semibold">HUMAN WHOLE-MOVIE RHYTHM REVIEW</p><p className="text-[7px]">CURRENT authority確認後にのみ記録可能。PASSは自動入力しません。</p></div><span className="font-mono text-[8px]">{performed?finalVerdict:"NOT_RUN"}</span></div>
      <div className="mt-2 grid gap-2">{AXES.map(({key,label,prompt})=><div key={key} className="border p-2 text-[8px]"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{label}</strong><p className="opacity-70">{prompt}</p></div><div className="flex gap-1">{(["NOT_RUN","PASS","FAIL"] as Verdict[]).map((verdict)=><button key={verdict} type="button" disabled={gate.state!=="CURRENT"} onClick={()=>setAxes((current)=>({...current,[key]:{...current[key],verdict}}))} className={`border px-2 py-1 disabled:opacity-40 ${axes[key].verdict===verdict?"font-bold ring-1":""}`}>{verdict}</button>)}</div></div><input value={axes[key].notes} disabled={gate.state!=="CURRENT"} onChange={(e)=>setAxes((current)=>({...current,[key]:{...current[key],notes:e.target.value}}))} placeholder="Human note" className="mt-1 w-full border bg-transparent px-2 py-1"/></div>)}</div>
      <div className="mt-2 grid gap-2 sm:grid-cols-2"><input value={reviewer} disabled={gate.state!=="CURRENT"} onChange={(e)=>setReviewer(e.target.value)} placeholder="reviewer" className="border bg-transparent px-2 py-1 text-[8px]"/><input value={reviewedAt} disabled={gate.state!=="CURRENT"} onChange={(e)=>setReviewedAt(e.target.value)} placeholder="reviewedAt ISO 8601" className="border bg-transparent px-2 py-1 text-[8px]"/></div>
      <label className="mt-2 flex items-start gap-2 text-[8px]"><input type="checkbox" checked={performed} disabled={gate.state!=="CURRENT"} onChange={(e)=>setPerformed(e.target.checked)}/><span>実際にOpening/Profile全体の連続previewをHumanとして見て、この6軸を判定した</span></label>
      <button type="button" disabled={!canExport} onClick={exportReview} className="mt-2 border border-emerald-400 px-3 py-1 text-[8px] font-semibold disabled:opacity-40">Human rhythm review JSONを書き出す</button>
    </div>
    <p className="mt-2 border-l-2 border-amber-300 pl-2 text-[7px]">Remotion Studio GUI Actual = NOT_RUN / Palmier GUI Actual = NOT_RUN / Mac DaVinci GUI Actual = NOT_RUN / Human visual QA = NOT_RUN / productionReady = false。</p>{error?<p className="mt-2 text-[8px] text-red-700">{error}</p>:null}
  </section>;
}
