import {useEffect, useMemo, useState} from "react";
import {requestMotionZukanSceneFocus} from "../data/motionZukanSceneFocus";
import {
  loadMotionZukanComposerState,
  MOTION_ZUKAN_COMPOSER_CHANGED_EVENT,
  type SceneProjectId,
} from "../data/visualSceneComposer";
import {createHash} from "../lib/browserHash";

type SceneBinding={sceneId:string;sourceRevision:string;timingRevision:string|null;durationFrames:number;durationSeconds:number;returnTo:{axis:"PACING";surface:"SCENE_TIMING_AND_A_B_COMPARE"}};
type EdgeCandidate={fromSceneId:string;toSceneId:string;fromSourceRevision:string;toSourceRevision:string;fromTimingRevision:string|null;toTimingRevision:string|null;transition:string;durationFrames:number;durationSeconds:number;returnTo:{axis:"TRANSITION";surface:"SCENE_TIMING_AND_A_B_COMPARE";focusSceneId:string;focusSourceRevision:string}};
type HumanItem={id:string;kind:"HUMAN_AXIS_FAIL";axis:string;notes:string;scope:string;sceneBindings:[];edgeCandidates:EdgeCandidate[];selectionAuthority:"HUMAN_MUST_SELECT_EXACT_SCENE_OR_EDGE_BEFORE_EDIT";qualityVerdict:"FAIL"};
type MechanicalItem={id:string;kind:"MECHANICAL_CUE";code:string;rule:string;sceneBindings:SceneBinding[];selectionAuthority:"MECHANICAL_CUE_ONLY_NOT_QUALITY_VERDICT";qualityVerdict:null};
type Queue={schemaVersion:"wedding-movie-production-rhythm-correction-queue/v1";authority:"DERIVED_FROM_CURRENT_RHYTHM_PASS_AND_EXPLICIT_HUMAN_WHOLE_PROJECT_REVIEW_WITHOUT_AUTOMATIC_QUALITY_INFERENCE";projectId:SceneProjectId;source:{rhythmPassSha256:string;currentnessSha256:string;humanReviewSha256:string;previewManifestSha256:string;renderSha256:string};items:Array<HumanItem|MechanicalItem>;summary:{humanFailedAxisCount:number;mechanicalCueCount:number;actionableSceneBindingCount:number;humanTransitionEdgeCandidateCount?:number;requiresHumanSceneSelection:boolean;requiresHumanEdgeSelection?:boolean;productionReady:false};evidenceBoundary:{humanRhythmReviewPerformed:true;humanVisualQa:"NOT_RUN";remotionStudioGuiActual:"NOT_RUN";palmierGuiActual:"NOT_RUN";macDaVinciGuiActual:"NOT_RUN";productionReady:false}};
type Rhythm={schemaVersion:"wedding-movie-production-rhythm-pass/v1";projectId:SceneProjectId;scenes:Array<{sceneId:string;sourceRevision:string;timingRevision:string|null;durationSeconds:number;productionRole:string|null}>;evidenceBoundary:{remotionStudioGuiActual:"NOT_RUN";palmierGuiActual:"NOT_RUN";macDaVinciGuiActual:"NOT_RUN";productionReady:false}};
type Currentness={schemaVersion:"wedding-movie-production-rhythm-pass-currentness/v1";projectId:SceneProjectId;state:"CURRENT"|"STALE";source:{rhythmPassSha256:string|null;previewManifestSha256:string|null;renderSha256:string|null};checks:Record<string,boolean>;mismatches:string[];evidenceBoundary:{humanVisualQa:"NOT_RUN";remotionStudioGuiActual:"NOT_RUN";palmierGuiActual:"NOT_RUN";macDaVinciGuiActual:"NOT_RUN";productionReady:false}};
const validQueue=(v:unknown,projectId:SceneProjectId):v is Queue=>{if(!v||typeof v!=="object")return false;const q=v as Partial<Queue>;return q.schemaVersion==="wedding-movie-production-rhythm-correction-queue/v1"&&q.authority==="DERIVED_FROM_CURRENT_RHYTHM_PASS_AND_EXPLICIT_HUMAN_WHOLE_PROJECT_REVIEW_WITHOUT_AUTOMATIC_QUALITY_INFERENCE"&&q.projectId===projectId&&Array.isArray(q.items)&&q.items.every((item)=>item.kind!=="HUMAN_AXIS_FAIL"||Array.isArray(item.edgeCandidates))&&q.summary?.productionReady===false&&q.evidenceBoundary?.humanVisualQa==="NOT_RUN"&&q.evidenceBoundary?.remotionStudioGuiActual==="NOT_RUN"&&q.evidenceBoundary?.palmierGuiActual==="NOT_RUN"&&q.evidenceBoundary?.macDaVinciGuiActual==="NOT_RUN"&&q.evidenceBoundary?.productionReady===false;};
const validRhythm=(v:unknown,projectId:SceneProjectId):v is Rhythm=>!!v&&typeof v==="object"&&(v as Rhythm).schemaVersion==="wedding-movie-production-rhythm-pass/v1"&&(v as Rhythm).projectId===projectId&&Array.isArray((v as Rhythm).scenes)&&(v as Rhythm).evidenceBoundary?.productionReady===false;
const validCurrentness=(v:unknown,projectId:SceneProjectId):v is Currentness=>!!v&&typeof v==="object"&&(v as Currentness).schemaVersion==="wedding-movie-production-rhythm-pass-currentness/v1"&&(v as Currentness).projectId===projectId&&((v as Currentness).state==="CURRENT"||(v as Currentness).state==="STALE")&&Array.isArray((v as Currentness).mismatches);
const copyText=(value:string)=>{void navigator.clipboard?.writeText(value);};
const edgeKey=(edge:EdgeCandidate)=>`${edge.fromSceneId}->${edge.toSceneId}`;

export function WeddingProductionRhythmCorrectionQueueCard({projectId}:{projectId:SceneProjectId}){
  const [queue,setQueue]=useState<Queue|null>(null);const [queueSha,setQueueSha]=useState<string|null>(null);
  const [rhythm,setRhythm]=useState<Rhythm|null>(null);const [rhythmSha,setRhythmSha]=useState<string|null>(null);
  const [currentness,setCurrentness]=useState<Currentness|null>(null);const [currentnessSha,setCurrentnessSha]=useState<string|null>(null);
  const [humanSelections,setHumanSelections]=useState<Record<string,string>>({});const [humanEdgeSelections,setHumanEdgeSelections]=useState<Record<string,string>>({});const [error,setError]=useState<string|null>(null);
  const [composerChangeRevision,setComposerChangeRevision]=useState(0);
  useEffect(()=>{const onChanged=()=>setComposerChangeRevision((value)=>value+1);window.addEventListener(MOTION_ZUKAN_COMPOSER_CHANGED_EVENT,onChanged);return()=>window.removeEventListener(MOTION_ZUKAN_COMPOSER_CHANGED_EVENT,onChanged);},[]);
  async function loadJson(file:File|null,kind:"queue"|"rhythm"|"currentness"){if(!file)return;setError(null);try{const buffer=await file.arrayBuffer();const value=JSON.parse(new TextDecoder().decode(buffer));const sha=await createHash(buffer);if(kind==="queue"){if(!validQueue(value,projectId))throw new Error("invalid correction queue / evidence boundary");setQueue(value);setQueueSha(sha);setHumanSelections({});setHumanEdgeSelections({});}else if(kind==="rhythm"){if(!validRhythm(value,projectId))throw new Error("invalid rhythm pass");setRhythm(value);setRhythmSha(sha);}else{if(!validCurrentness(value,projectId))throw new Error("invalid rhythm currentness");setCurrentness(value);setCurrentnessSha(sha);}}catch(e){setError(e instanceof Error?e.message:"invalid JSON");}}
  const liveComposerBinding=useMemo(()=>{void composerChangeRevision;if(!rhythm)return{state:"NOT_RUN" as const,reasons:[] as string[]};const composer=loadMotionZukanComposerState();const reasons:string[]=[];for(const source of rhythm.scenes){const current=composer.scenes.find((scene)=>scene.projectId===projectId&&scene.sceneId===source.sceneId);if(!current)reasons.push(`LIVE_SCENE_MISSING:${source.sceneId}`);else if(current.updatedAt!==source.sourceRevision)reasons.push(`LIVE_SCENE_REVISION_DRIFT:${source.sceneId}`);}return{state:reasons.length?"STALE" as const:"CURRENT" as const,reasons};},[rhythm,projectId,composerChangeRevision]);
  const gate=useMemo(()=>{const reasons:string[]=[];if(!queue||!queueSha)reasons.push("CORRECTION_QUEUE_NOT_LOADED");if(!rhythm||!rhythmSha)reasons.push("RHYTHM_PASS_NOT_LOADED");if(!currentness||!currentnessSha)reasons.push("CURRENTNESS_NOT_LOADED");if(queue&&rhythmSha&&queue.source.rhythmPassSha256!==rhythmSha)reasons.push("QUEUE_RHYTHM_SHA_MISMATCH");if(queue&&currentnessSha&&queue.source.currentnessSha256!==currentnessSha)reasons.push("QUEUE_CURRENTNESS_SHA_MISMATCH");if(currentness){if(currentness.state!=="CURRENT"||currentness.mismatches.length||!Object.values(currentness.checks??{}).every(Boolean))reasons.push("RHYTHM_CURRENTNESS_NOT_CURRENT");if(rhythmSha&&currentness.source.rhythmPassSha256!==rhythmSha)reasons.push("CURRENTNESS_RHYTHM_SHA_MISMATCH");if(queue&&queue.source.previewManifestSha256!==currentness.source.previewManifestSha256)reasons.push("PREVIEW_SHA_MISMATCH");if(queue&&queue.source.renderSha256!==currentness.source.renderSha256)reasons.push("RENDER_SHA_MISMATCH");}if(liveComposerBinding.state==="STALE")reasons.push(...liveComposerBinding.reasons);return{state:reasons.length?"BLOCKED" as const:"BOUND" as const,reasons};},[queue,queueSha,rhythm,rhythmSha,currentness,currentnessSha,liveComposerBinding]);
  function navigate(binding:SceneBinding){if(gate.state!=="BOUND")return;requestMotionZukanSceneFocus({projectId,sceneId:binding.sceneId,sourceRevision:binding.sourceRevision,axis:"PACING",surface:"SCENE_TIMING_AND_A_B_COMPARE",requestedBy:"PROJECT_RHYTHM_CORRECTION_QUEUE"});}
  function navigateHuman(item:HumanItem){if(!rhythm||gate.state!=="BOUND")return;const sceneId=humanSelections[item.id];const scene=rhythm.scenes.find((candidate)=>candidate.sceneId===sceneId);if(!scene)return;requestMotionZukanSceneFocus({projectId,sceneId:scene.sceneId,sourceRevision:scene.sourceRevision,axis:"PACING",surface:"SCENE_TIMING_AND_A_B_COMPARE",requestedBy:"PROJECT_RHYTHM_CORRECTION_QUEUE"});}
  function navigateHumanEdge(item:HumanItem){if(gate.state!=="BOUND")return;const selected=humanEdgeSelections[item.id];const edge=item.edgeCandidates.find((candidate)=>edgeKey(candidate)===selected);if(!edge)return;requestMotionZukanSceneFocus({projectId,sceneId:edge.returnTo.focusSceneId,sourceRevision:edge.returnTo.focusSourceRevision,axis:"TRANSITION",surface:"SCENE_TIMING_AND_A_B_COMPARE",requestedBy:"PROJECT_RHYTHM_CORRECTION_QUEUE"});}
  const selectedManifestPath=`out/production/${projectId}/${projectId}-selected-scene-render-manifest.json`;
  const readinessAuditPath=`out/production/${projectId}/${projectId}-production-readiness-audit.json`;
  const qaOutputDir=`out/qa/project-real-media-preview/${projectId}`;
  const refreshVisualQaCommand=`node --no-warnings motion-studio/scripts/refresh-wedding-project-real-media-visual-qa.mts --selected-manifest=${selectedManifestPath} --readiness-audit=${readinessAuditPath} --output-dir=${qaOutputDir}`;
  const rebuildRhythmCommand=`node --no-warnings motion-studio/scripts/wedding-project-production-rhythm-pass.mts --preview-manifest=${qaOutputDir}/${projectId}-real-media-preview-manifest.json --output=${qaOutputDir}/${projectId}-production-rhythm-pass.json`;
  const revalidateRhythmCommand=`node --no-warnings motion-studio/scripts/verify-wedding-project-production-rhythm-pass-currentness.mts --rhythm-pass=${qaOutputDir}/${projectId}-production-rhythm-pass.json --strict-current --output=${qaOutputDir}/${projectId}-production-rhythm-pass-currentness.json`;
  return <section className="mt-3 border-2 border-fuchsia-300 p-3 dark:border-fuchsia-800" data-production-rhythm-correction-queue={projectId} data-production-rhythm-correction-binding={gate.state} data-production-rhythm-live-composer={liveComposerBinding.state}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-[8px] font-semibold tracking-[0.14em] text-fuchsia-700 dark:text-fuchsia-300">RHYTHM CORRECTION QUEUE / {projectId.toUpperCase()}</p><p className="mt-1 text-[9px]">Human FAILは自動でScene/edgeを決めません。mechanical cueだけexact revision-bound Sceneへ移動できます。</p></div><span className="border px-2 py-1 font-mono text-[8px]">{gate.state}</span></div>
    <div className="mt-2 grid gap-2 md:grid-cols-3"><label className="border p-2 text-[8px]">Correction queue<input type="file" accept="application/json" className="mt-1 block w-full" onChange={(e)=>void loadJson(e.target.files?.[0]??null,"queue")}/></label><label className="border p-2 text-[8px]">Current rhythm pass<input type="file" accept="application/json" className="mt-1 block w-full" onChange={(e)=>void loadJson(e.target.files?.[0]??null,"rhythm")}/></label><label className="border p-2 text-[8px]">Strict currentness<input type="file" accept="application/json" className="mt-1 block w-full" onChange={(e)=>void loadJson(e.target.files?.[0]??null,"currentness")}/></label></div>
    {gate.reasons.length?<p className="mt-2 border-l-2 border-amber-300 pl-2 text-[8px]">{gate.reasons.join(" / ")}</p>:null}
    {queue?<div className="mt-3 grid gap-2">{queue.items.map((item)=>item.kind==="MECHANICAL_CUE"?<article key={item.id} className="border p-2 text-[8px]" data-rhythm-correction-kind="MECHANICAL_CUE"><div className="flex justify-between gap-2"><div><strong>{item.code}</strong><p>{item.rule}</p><p className="opacity-60">mechanical cue / quality verdictではありません</p></div><span>{item.sceneBindings.length} Scene</span></div><div className="mt-1 flex flex-wrap gap-1">{item.sceneBindings.map((binding)=><button key={`${item.id}:${binding.sceneId}`} type="button" disabled={gate.state!=="BOUND"} onClick={()=>navigate(binding)} className="border px-2 py-1 disabled:opacity-40">{binding.sceneId} · {binding.durationSeconds.toFixed(2)}s → Timing/Rhythm</button>)}</div></article>:<article key={item.id} className="border p-2 text-[8px]" data-rhythm-correction-kind="HUMAN_AXIS_FAIL" data-rhythm-human-axis={item.axis}><strong>{item.axis} = FAIL</strong><p>{item.notes||"Human noteなし"}</p><p className="opacity-60">scope: {item.scope} / exact {item.axis==="transitionCadence"?"edge":"Scene"}はHuman選択必須</p>{item.axis==="transitionCadence"?<div className="mt-1 flex flex-wrap gap-1" data-rhythm-transition-edge-selector><select disabled={gate.state!=="BOUND"} value={humanEdgeSelections[item.id]??""} onChange={(e)=>setHumanEdgeSelections((current)=>({...current,[item.id]:e.target.value}))} className="border bg-transparent px-2 py-1"><option value="">Scene edgeを選択</option>{item.edgeCandidates.map((edge)=><option key={edgeKey(edge)} value={edgeKey(edge)}>{edge.fromSceneId} → {edge.toSceneId} · {edge.transition} · {edge.durationFrames}f</option>)}</select><button type="button" disabled={gate.state!=="BOUND"||!humanEdgeSelections[item.id]} onClick={()=>navigateHumanEdge(item)} className="border px-2 py-1 disabled:opacity-40">Human-selected EdgeをTransition editorへ</button></div>:<div className="mt-1 flex flex-wrap gap-1"><select disabled={gate.state!=="BOUND"} value={humanSelections[item.id]??""} onChange={(e)=>setHumanSelections((current)=>({...current,[item.id]:e.target.value}))} className="border bg-transparent px-2 py-1"><option value="">Sceneを選択</option>{rhythm?.scenes.map((scene)=><option key={scene.sceneId} value={scene.sceneId}>{scene.sceneId} · {scene.durationSeconds.toFixed(2)}s · {scene.productionRole??"role n/a"}</option>)}</select><button type="button" disabled={gate.state!=="BOUND"||!humanSelections[item.id]} onClick={()=>navigateHuman(item)} className="border px-2 py-1 disabled:opacity-40">Human-selected SceneをTiming/Rhythmへ</button></div>}</article>)}</div>:null}
    {rhythm&&liveComposerBinding.state==="STALE"?<div className="mt-3 border-2 border-amber-300 p-2 text-[8px]" data-production-rhythm-correction-refresh-required><p className="font-semibold">TIMING EDIT DETECTED → OLD RHYTHM EVIDENCE STALE</p><p className="mt-1">Scene revisionがloaded rhythm passから変わりました。古いqueueで追加修正せず、fresh render → fresh rhythm pass → strict-current → Human whole-movie reviewをNOT_RUNから再実施してください。</p><div className="mt-2 grid gap-1"><button type="button" onClick={()=>copyText(refreshVisualQaCommand)} className="border px-2 py-1 text-left">1. fresh real-media render + QA stills + NOT_RUN visual review commandをコピー</button><code className="overflow-x-auto whitespace-nowrap">{refreshVisualQaCommand}</code><button type="button" onClick={()=>copyText(rebuildRhythmCommand)} className="border px-2 py-1 text-left">2. fresh rhythm pass commandをコピー</button><code className="overflow-x-auto whitespace-nowrap">{rebuildRhythmCommand}</code><button type="button" onClick={()=>copyText(revalidateRhythmCommand)} className="border px-2 py-1 text-left">3. fresh rhythm strict-current commandをコピー</button><code className="overflow-x-auto whitespace-nowrap">{revalidateRhythmCommand}</code></div><p className="mt-2 font-semibold">4. Motion Zukanへfresh rhythm/currentnessを読み込み、Human whole-project rhythm reviewをNOT_RUNから再実施</p></div>:null}
    <p className="mt-2 border-l-2 border-amber-300 pl-2 text-[7px]">Remotion Studio GUI Actual = NOT_RUN / Palmier GUI Actual = NOT_RUN / Mac DaVinci GUI Actual = NOT_RUN / Human visual QA = NOT_RUN / productionReady = false。Scene/edge revision driftはloaded queueを即BLOCKし、silent rebaseしません。</p>{error?<p className="mt-2 text-[8px] text-red-700">{error}</p>:null}
  </section>;
}
