// AUTO-GENERATED by scripts/sync-production-stage-blocker-codes.mjs
// Stable codes only. Raw Motion Studio blocker details stay out of Dashboard snapshots.

export const movieProductionStageBlockerCodes = {
  "schemaVersion": "wedding-movie-production-stage-blocker-codes/v1",
  "authority": "MOTION_STUDIO_STABLE_STAGE_BLOCKER_CODES",
  "source": {
    "opening": "motion-studio/scripts/opening-v1-production-status.mts#stages.*.blockerCodes",
    "profile": "motion-studio/scripts/profile-v1-production-status.mts#stages.*.blockerCodes"
  },
  "projects": {
    "opening": {
      "stages": {
        "media": [
          "PHOTO_MISSING",
          "BGM_NOT_READY",
          "BGM_INTAKE_RECEIPT_STALE",
          "BGM_INTAKE:BGM_RECEIPT_MISSING"
        ]
      }
    },
    "profile": {
      "stages": {
        "assembly": [
          "MEDIA_MISSING",
          "MEDIA_INTAKE_RECEIPT_STALE",
          "MEDIA_INTAKE:RECEIPT_MISSING",
          "BGM_RIGHTS:PROFILE_BGM_FILE_MISSING",
          "BGM_RIGHTS:PROFILE_BGM_INTAKE_RECEIPT_STALE",
          "BGM_RIGHTS:PROFILE_BGM_INTAKE_BGM_RECEIPT_MISSING",
          "BGM_RIGHTS:PROFILE_BGM_RIGHTS_APPROVAL_NOT_RUN",
          "STRUCTURE_REVIEW:STRUCTURE_REVIEW_EVIDENCE_MISSING",
          "REAL_MEDIA_REVIEW:REAL_MEDIA_REVIEW_EVIDENCE_MISSING"
        ]
      }
    }
  },
  "guardrails": [
    "RAW_BLOCKER_DETAIL != GENERATED_BLOCKER_CODE",
    "ABSOLUTE_PATH_MUST_NOT_ENTER_GENERATED_BLOCKER_CODES",
    "GENERATED_BLOCKER_CODE_VISIBLE != BLOCKER_RESOLVED"
  ]
} as const;
