// AUTO-GENERATED by scripts/sync-opening-production-status.mjs
// Motion Studio production status is the authority. Do not edit by hand.

export const openingProductionStatus = {
  "source": {
    "status": "motion-studio/scripts/opening-v1-production-status.mts"
  },
  "overallState": "MEDIA_REQUIRED",
  "stages": {
    "media": {
      "state": "BLOCKED"
    },
    "previewRender": {
      "state": "NOT_RUN"
    },
    "previewReview": {
      "state": "NOT_RUN"
    },
    "finalRender": {
      "state": "NOT_RUN"
    },
    "productionBundle": {
      "state": "NOT_RUN"
    },
    "davinciFinishing": {
      "state": "NOT_RUN"
    },
    "finalDeliveryApproval": {
      "state": "NOT_RUN"
    }
  },
  "readiness": {
    "finalRenderEligible": false,
    "mixReady": false,
    "humanPreviewApproved": false,
    "finalRenderQaPass": false,
    "productionBundleCurrent": false,
    "macDaVinciActualVerified": false,
    "readyForFinalDeliveryApproval": false,
    "finalDeliveryApproved": false,
    "productionReady": false
  },
  "handoff": {
    "palmier": {
      "contractVersion": "opening-v1-palmier-handoff/v2",
      "current": false,
      "sourceAuthorities": [
        "src/data/openingV1.ts#openingV1Scenes",
        "src/data/openingV1Sound.ts#openingV1SoundCues"
      ],
      "artifacts": {
        "sceneTimeline": {
          "path": "out/handoff/opening-v1/opening-v1-palmier-timeline.csv",
          "shaBound": true,
          "carries": [
            "scene_boundary",
            "replacement_policy",
            "final_render_sha256"
          ]
        },
        "soundCues": {
          "path": "out/handoff/opening-v1/opening-v1-palmier-sound-cues.csv",
          "shaBound": true,
          "carries": [
            "bgm",
            "ambience_j_cut",
            "start_end",
            "volume",
            "note",
            "final_render_sha256"
          ]
        }
      }
    }
  },
  "nextActions": [
    "実写真11枚をcanonical filenameで投入",
    "pnpm sync:photos",
    "pnpm opening:assembly-preflight"
  ]
} as const;
