// AUTO-GENERATED by scripts/sync-opening-production-gate.mjs
// Source of truth remains in motion-studio. Do not edit by hand.

export const openingProductionGate = {
  "source": {
    "photos": "motion-studio/src/data/photoLibrary.generated.ts",
    "photoResolver": "motion-studio/src/data/openingV1Media.ts",
    "audio": "motion-studio/src/data/assets.ts"
  },
  "expectedPhotoCount": 11,
  "resolvedPhotoCount": 0,
  "photoMissingCount": 11,
  "photoSlots": [
    {
      "key": "okinawa-01",
      "resolved": false,
      "path": null
    },
    {
      "key": "okinawa-02",
      "resolved": false,
      "path": null
    },
    {
      "key": "okinawa-03",
      "resolved": false,
      "path": null
    },
    {
      "key": "seoul-01",
      "resolved": false,
      "path": null
    },
    {
      "key": "seoul-02",
      "resolved": false,
      "path": null
    },
    {
      "key": "seoul-03",
      "resolved": false,
      "path": null
    },
    {
      "key": "hawaii-01",
      "resolved": false,
      "path": null
    },
    {
      "key": "hawaii-02",
      "resolved": false,
      "path": null
    },
    {
      "key": "hawaii-03",
      "resolved": false,
      "path": null
    },
    {
      "key": "hero-01",
      "resolved": false,
      "path": null
    },
    {
      "key": "hero-02",
      "resolved": false,
      "path": null
    }
  ],
  "bgm": {
    "assetId": "opening-bgm-main",
    "status": "missing",
    "playable": false
  },
  "ambience": [
    {
      "assetId": "opening-okinawa-sea",
      "status": "missing",
      "playable": false
    },
    {
      "assetId": "opening-seoul-street",
      "status": "missing",
      "playable": false
    },
    {
      "assetId": "opening-hawaii-ocean",
      "status": "missing",
      "playable": false
    },
    {
      "assetId": "opening-arrival-roomtone",
      "status": "missing",
      "playable": false
    }
  ],
  "finalBlocked": true,
  "nextAction": "実写真11枚を motion-studio/public/photos/opening/ へ入れ、pnpm sync:photos を実行する"
} as const;
