// AUTO-GENERATED by scripts/sync-opening-audio-listening-status.mjs
// Motion Studio Human audio review status is the authority. Do not edit by hand.

export const openingAudioListeningStatus = {
  "schemaVersion": "opening-v1-audio-listening-review-status/v1",
  "authority": "DERIVED_OPENING_AUDIO_LISTENING_REVIEW_STATUS",
  "state": "NOT_RUN",
  "evidencePath": "out/qa/opening-v1-audio-listening-review.json",
  "blockers": [
    "OPENING_AUDIO_LISTENING_REVIEW_NOT_RUN"
  ],
  "humanAudioQaComplete": false,
  "remotionStudioActual": "NOT_RUN",
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false,
  "recovery": [
    "rights-cleared Opening previewを最後まで人間が再生",
    "node --no-warnings scripts/opening-v1-audio-listening-review.mts --init",
    "audibility / balance / startIntegrity / endIntegrity / pictureSync をHuman QA",
    "node --no-warnings scripts/opening-v1-audio-listening-review.mts --strict"
  ],
  "guardrails": [
    "BGM_RIGHTS_CLEARED != HUMAN_AUDIO_LISTENING_PASS",
    "PREVIEW_OR_BGM_SHA_CHANGED => HUMAN_AUDIO_LISTENING_REVIEW_STALE",
    "HUMAN_AUDIO_LISTENING_PASS != REMOTION_STUDIO_ACTUAL_VERIFIED",
    "HUMAN_AUDIO_LISTENING_PASS != MAC_DAVINCI_ACTUAL_VERIFIED",
    "HUMAN_AUDIO_LISTENING_PASS != PRODUCTION_READY"
  ]
} as const;
