// AUTO-GENERATED by scripts/sync-opening-production-gate.mjs
// Source of truth remains in motion-studio. Do not edit by hand.

export const openingProductionGate = {
  "source": {
    "preflight": "motion-studio/scripts/opening-v1-assembly-preflight.mts",
    "cropQaPreflight": "motion-studio/scripts/opening-v1-crop-qa-preflight.mts",
    "cropReview": "motion-studio/scripts/opening-v1-crop-review-evidence.mts",
    "photoResolver": "motion-studio/src/data/openingV1Media.ts",
    "photoPresentation": "motion-studio/src/data/openingV1PhotoPresentation.ts",
    "audio": "motion-studio/src/data/assets.ts"
  },
  "expectedPhotoCount": 11,
  "resolvedPhotoCount": 0,
  "photoMissingCount": 11,
  "photos": {
    "ready": false,
    "fileReady": false,
    "intakeReceiptCurrent": false,
    "intakeReceiptPath": "out/intake/opening-media-intake.json",
    "intakeReceiptVerifiedCount": 0,
    "intakeReceiptExpectedCount": 11,
    "intakeReceiptBlockerCodes": [
      "RECEIPT_MISSING"
    ],
    "cropQa": {
      "precedence": "SCENE > ASSET > DEFAULT",
      "metadataValid": true,
      "assetHintCount": 0,
      "coverCount": 7,
      "coverPresentCount": 0,
      "humanCropQaState": "NOT_RUN",
      "humanCropQaReviewedCount": 0,
      "humanCropQaRequiredCount": 0,
      "humanCropQaBlockerCodes": [
        "OPENING_CROP_REVIEW_EVIDENCE_MISSING"
      ],
      "evidencePath": "out/qa/opening-v1-crop-review-evidence.json",
      "macStudioActualState": "NOT_RUN",
      "macDaVinciActualState": "NOT_RUN",
      "productionReady": false
    }
  },
  "photoSlots": [
    {
      "key": "okinawa-01",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "okinawa-02",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "okinawa-03",
      "resolved": false,
      "path": null,
      "cropQaRequired": false,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "seoul-01",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "seoul-02",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "seoul-03",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "hawaii-01",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "hawaii-02",
      "resolved": false,
      "path": null,
      "cropQaRequired": false,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "hawaii-03",
      "resolved": false,
      "path": null,
      "cropQaRequired": true,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "cover",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "hero-01",
      "resolved": false,
      "path": null,
      "cropQaRequired": false,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    },
    {
      "key": "hero-02",
      "resolved": false,
      "path": null,
      "cropQaRequired": false,
      "humanCropQaState": "NOT_RUN",
      "scenePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain"
      },
      "assetHint": null,
      "effectivePresentation": {
        "focus": {
          "x": 50,
          "y": 50
        },
        "fit": "contain",
        "focusSource": "scene",
        "fitSource": "scene"
      }
    }
  ],
  "bgm": {
    "assetId": "opening-bgm-main",
    "status": "missing",
    "playable": false,
    "fileExists": true,
    "intakeReceiptCurrent": false,
    "intakeReceiptPath": "out/intake/opening-bgm-intake.json",
    "intakeReceiptBlockerCodes": [
      "BGM_RECEIPT_MISSING"
    ],
    "ready": false
  },
  "ambience": [
    {
      "assetId": "opening-okinawa-sea",
      "status": "missing",
      "playable": false,
      "fileExists": false,
      "ready": false
    },
    {
      "assetId": "opening-seoul-street",
      "status": "missing",
      "playable": false,
      "fileExists": false,
      "ready": false
    },
    {
      "assetId": "opening-hawaii-ocean",
      "status": "missing",
      "playable": false,
      "fileExists": false,
      "ready": false
    },
    {
      "assetId": "opening-arrival-roomtone",
      "status": "missing",
      "playable": false,
      "fileExists": false,
      "ready": false
    }
  ],
  "finalBlocked": true,
  "nextAction": "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\"",
  "nextActions": [
    "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\"",
    "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\" --apply --overwrite --receipt out/intake/opening-media-intake.json",
    "node --no-warnings scripts/verify-production-media-intake-receipt.mts --project opening",
    "pnpm prepare:opening-v1",
    "node --no-warnings scripts/intake-production-bgm.mts --project opening --source \"/ABS/PATH/TO/opening-bgm.mp3\"",
    "node --no-warnings scripts/intake-production-bgm.mts --project opening --source \"/ABS/PATH/TO/opening-bgm.mp3\" --apply --receipt out/intake/opening-bgm-intake.json",
    "node --no-warnings scripts/verify-production-bgm-intake-receipt.mts --project opening"
  ]
} as const;
