// AUTO-GENERATED by scripts/sync-opening-production-status.mjs
// Motion Studio production status is the authority. Do not edit by hand.

export const openingProductionStatus = {
  "source": {
    "status": "motion-studio/scripts/opening-v1-production-status.mts"
  },
  "overallState": "MEDIA_REQUIRED",
  "stages": {
    "media": {
      "state": "BLOCKED"
    },
    "previewRender": {
      "state": "NOT_RUN"
    },
    "previewReview": {
      "state": "NOT_RUN"
    },
    "finalRender": {
      "state": "NOT_RUN"
    },
    "productionBundle": {
      "state": "NOT_RUN"
    },
    "davinciFinishing": {
      "state": "NOT_RUN"
    },
    "finalDeliveryApproval": {
      "state": "NOT_RUN"
    }
  },
  "readiness": {
    "finalRenderEligible": false,
    "mixReady": false,
    "humanPreviewApproved": false,
    "finalRenderQaPass": false,
    "productionBundleCurrent": false,
    "macDaVinciActualVerified": false,
    "readyForFinalDeliveryApproval": false,
    "finalDeliveryApproved": false,
    "productionReady": false
  }
} as const;
