// AUTO-GENERATED by scripts/sync-opening-crop-review-gate.mjs
// Human evidence lives under motion-studio/out and is never manufactured by this file.

export const openingCropReviewGate = {
  "source": "motion-studio/scripts/opening-v1-crop-review-evidence.mts",
  "state": "NOT_RUN",
  "blockers": [
    "OPENING_CROP_REVIEW_EVIDENCE_MISSING"
  ],
  "reviewedCount": 0,
  "requiredCount": 0,
  "macStudioActual": "NOT_RUN",
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false,
  "audit": {
    "evidencePath": "motion-studio/out/qa/opening-v1-crop-review-evidence.json",
    "evidenceExists": false,
    "evidenceSha256": null,
    "parseState": "MISSING",
    "boundAt": null,
    "bindingFingerprintSha256": null,
    "slots": [],
    "overall": "NOT_RUN",
    "macStudioActual": "NOT_RUN",
    "macDaVinciActual": "NOT_RUN",
    "productionReady": false
  }
} as const;
