// AUTO-GENERATED by scripts/sync-opening-davinci-actual-binding-audit.mjs
// Read-only audit of Opening recovery-bound Mac DaVinci Actual/final approval. Do not edit by hand.

export const openingDavinciActualBindingAudit = {
  "schemaVersion": "opening-v1-davinci-actual-binding-audit/v1",
  "authority": "DERIVED_DAVINCI_ACTUAL_BINDING_AUDIT",
  "state": "NOT_RUN",
  "current": false,
  "productionReady": false,
  "recovery": {
    "path": "out/handoff/opening-v1/opening-v1-davinci-production-recovery.json",
    "exists": false,
    "sha256": null,
    "sourceRenderSha256": null,
    "cropReviewEvidenceSha256": null,
    "cropReviewBindingFingerprintSha256": null
  },
  "actualEvidence": {
    "path": "out/qa/opening-v1-davinci-finishing-evidence.json",
    "exists": false,
    "sha256": null,
    "boundAt": null,
    "boundRecoverySha256": null,
    "boundSourceRenderSha256": null,
    "boundCropReviewEvidenceSha256": null,
    "boundCropReviewBindingFingerprintSha256": null,
    "reviewOverall": "NOT_RUN",
    "reviewer": null,
    "allChecksPass": false,
    "allChecksNotRun": false
  },
  "finalApproval": {
    "path": "out/qa/opening-v1-final-delivery-approval.json",
    "exists": false,
    "sha256": null,
    "current": false,
    "decision": "NOT_RUN",
    "productionReady": false,
    "boundRecoverySha256": null,
    "boundDavinciEvidenceSha256": null
  },
  "mismatches": [],
  "guardrails": [
    "ACTUAL_EVIDENCE_EXISTS != MAC_DAVINCI_ACTUAL_VERIFIED",
    "RECOVERY_SIDECAR_CHANGED => ACTUAL_EVIDENCE_STALE",
    "SOURCE_RENDER_CHANGED => ACTUAL_EVIDENCE_STALE",
    "CROP_REVIEW_CHANGED => ACTUAL_EVIDENCE_STALE",
    "ACTUAL_EVIDENCE_OR_RECOVERY_CHANGED => FINAL_APPROVAL_STALE",
    "CURRENT_PASS != FINAL_DELIVERY_APPROVED"
  ]
} as const;
