// AUTO-GENERATED by scripts/sync-opening-production-gate.mjs
// Source of truth remains in motion-studio. Do not edit by hand.

export const openingProductionGate = {
  "source": {
    "preflight": "motion-studio/scripts/opening-v1-assembly-preflight.mts",
    "photoResolver": "motion-studio/src/data/openingV1Media.ts",
    "audio": "motion-studio/src/data/assets.ts"
  },
  "expectedPhotoCount": 11,
  "resolvedPhotoCount": 0,
  "photoMissingCount": 11,
  "photos": {
    "ready": false,
    "fileReady": false,
    "intakeReceiptCurrent": false,
    "intakeReceiptPath": "out/intake/opening-media-intake.json",
    "intakeReceiptVerifiedCount": 0,
    "intakeReceiptExpectedCount": 11,
    "intakeReceiptBlockerCodes": [
      "RECEIPT_MISSING"
    ]
  },
  "photoSlots": [
    {"key":"okinawa-01","resolved":false,"path":null},
    {"key":"okinawa-02","resolved":false,"path":null},
    {"key":"okinawa-03","resolved":false,"path":null},
    {"key":"seoul-01","resolved":false,"path":null},
    {"key":"seoul-02","resolved":false,"path":null},
    {"key":"seoul-03","resolved":false,"path":null},
    {"key":"hawaii-01","resolved":false,"path":null},
    {"key":"hawaii-02","resolved":false,"path":null},
    {"key":"hawaii-03","resolved":false,"path":null},
    {"key":"hero-01","resolved":false,"path":null},
    {"key":"hero-02","resolved":false,"path":null}
  ],
  "bgm": {
    "assetId": "opening-bgm-main",
    "status": "missing",
    "playable": false,
    "fileExists": false,
    "intakeReceiptCurrent": false,
    "intakeReceiptPath": "out/intake/opening-bgm-intake.json",
    "intakeReceiptBlockerCodes": ["BGM_RECEIPT_MISSING"],
    "ready": false
  },
  "ambience": [
    {"assetId":"opening-okinawa-sea","status":"missing","playable":false,"fileExists":false,"ready":false},
    {"assetId":"opening-seoul-street","status":"missing","playable":false,"fileExists":false,"ready":false},
    {"assetId":"opening-hawaii-ocean","status":"missing","playable":false,"fileExists":false,"ready":false},
    {"assetId":"opening-arrival-roomtone","status":"missing","playable":false,"fileExists":false,"ready":false}
  ],
  "finalBlocked": true,
  "nextAction": "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\"",
  "nextActions": [
    "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\"",
    "node --no-warnings scripts/intake-production-media.mts --project opening --source \"/ABS/PATH/TO/opening-media\" --apply --overwrite --receipt out/intake/opening-media-intake.json",
    "node --no-warnings scripts/verify-production-media-intake-receipt.mts --project opening",
    "pnpm prepare:opening-v1",
    "node --no-warnings scripts/intake-production-bgm.mts --project opening --source \"/ABS/PATH/TO/opening-bgm.mp3\"",
    "node --no-warnings scripts/intake-production-bgm.mts --project opening --source \"/ABS/PATH/TO/opening-bgm.mp3\" --apply --receipt out/intake/opening-bgm-intake.json",
    "node --no-warnings scripts/verify-production-bgm-intake-receipt.mts --project opening"
  ]
} as const;
