// AUTO-GENERATED by scripts/sync-profile-real-media-review-gate.mjs
// Human evidence lives under motion-studio/out and is never manufactured by this file.

export const profileRealMediaReviewGate = {
  "source": "motion-studio/scripts/profile-v1-real-media-review.mts",
  "state": "NOT_RUN",
  "humanReviewComplete": false,
  "blockers": [
    "REAL_MEDIA_REVIEW_EVIDENCE_MISSING"
  ],
  "mediaExpected": 17,
  "mediaReviewed": 0,
  "bgmReviewed": false,
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false
} as const;
