// AUTO-GENERATED by scripts/sync-profile-production-gate.mjs
// Source of truth remains in motion-studio + 01_profile-movie/chapter-plan.md. Do not edit by hand.

export const profileProductionGate = {
  "source": {
    "preflight": "motion-studio/scripts/profile-v1-assembly-preflight.mts",
    "plan": "motion-studio/src/data/profileV1ProductionPlan.ts",
    "chapterPlan": "01_profile-movie/chapter-plan.md",
    "structureReview": "motion-studio/scripts/profile-v1-full-structure-review.mts"
  },
  "chapterCount": 5,
  "chapters": [
    {
      "chapterId": "departure",
      "order": 1,
      "title": "出発",
      "role": "旅行テーマの世界観を提示してプロフィール本編へ出発する。",
      "editIntent": [
        "10秒試作から成立確認",
        "BGMと短いテロップを合わせる",
        "AI背景は仮素材に限定可能"
      ],
      "requiredCount": 3,
      "readyCount": 0,
      "ready": false
    },
    {
      "chapterId": "separate-journeys",
      "order": 2,
      "title": "それぞれの旅",
      "role": "新郎新婦それぞれの幼少期から学生・友人期までの歩みを見せる。",
      "editIntent": [
        "写真中心",
        "ゆっくりズーム",
        "テロップは短く"
      ],
      "requiredCount": 4,
      "readyCount": 0,
      "ready": false
    },
    {
      "chapterId": "intersection",
      "order": 3,
      "title": "交差",
      "role": "出会い・交際・同棲を、二人の写真と航路表現でつなぐ。",
      "editIntent": [
        "写真の感情を優先",
        "地図や航路で章切り替え"
      ],
      "requiredCount": 3,
      "readyCount": 0,
      "ready": false
    },
    {
      "chapterId": "adventure",
      "order": 4,
      "title": "冒険",
      "role": "旅行・犬・楽しい思い出を明るくテンポ良く見せる。",
      "editIntent": [
        "前章より少しテンポを上げる",
        "笑いと明るさを入れる"
      ],
      "requiredCount": 4,
      "readyCount": 0,
      "ready": false
    },
    {
      "chapterId": "arrival",
      "order": 5,
      "title": "到着",
      "role": "現在・入籍・結婚式から披露宴入場へつなぐ。",
      "editIntent": [
        "現在の二人を主役にする",
        "横浜・会場へ接続",
        "光や到着の演出で締める"
      ],
      "requiredCount": 3,
      "readyCount": 0,
      "ready": false
    }
  ],
  "expectedMediaCount": 17,
  "resolvedMediaCount": 0,
  "mediaMissingCount": 17,
  "mediaSlots": [
    {
      "id": "departure-airport",
      "chapterId": "departure",
      "label": "空港",
      "kind": "photo-or-video",
      "canonicalStem": "departure-airport",
      "file": null,
      "ready": false
    },
    {
      "id": "departure-runway",
      "chapterId": "departure",
      "label": "滑走路",
      "kind": "photo-or-video",
      "canonicalStem": "departure-runway",
      "file": null,
      "ready": false
    },
    {
      "id": "departure-window-clouds",
      "chapterId": "departure",
      "label": "飛行機窓・雲",
      "kind": "photo-or-video",
      "canonicalStem": "departure-window-clouds",
      "file": null,
      "ready": false
    },
    {
      "id": "groom-childhood",
      "chapterId": "separate-journeys",
      "label": "新郎 幼少期・家族",
      "kind": "photo",
      "canonicalStem": "groom-childhood",
      "file": null,
      "ready": false
    },
    {
      "id": "groom-school-friends",
      "chapterId": "separate-journeys",
      "label": "新郎 学生・友人",
      "kind": "photo",
      "canonicalStem": "groom-school-friends",
      "file": null,
      "ready": false
    },
    {
      "id": "bride-childhood",
      "chapterId": "separate-journeys",
      "label": "新婦 幼少期・家族",
      "kind": "photo",
      "canonicalStem": "bride-childhood",
      "file": null,
      "ready": false
    },
    {
      "id": "bride-school-friends",
      "chapterId": "separate-journeys",
      "label": "新婦 学生・友人",
      "kind": "photo",
      "canonicalStem": "bride-school-friends",
      "file": null,
      "ready": false
    },
    {
      "id": "couple-early",
      "chapterId": "intersection",
      "label": "出会い・交際初期",
      "kind": "photo",
      "canonicalStem": "couple-early",
      "file": null,
      "ready": false
    },
    {
      "id": "couple-daily",
      "chapterId": "intersection",
      "label": "日常・同棲",
      "kind": "photo",
      "canonicalStem": "couple-daily",
      "file": null,
      "ready": false
    },
    {
      "id": "couple-trip",
      "chapterId": "intersection",
      "label": "二人の旅行",
      "kind": "photo",
      "canonicalStem": "couple-trip",
      "file": null,
      "ready": false
    },
    {
      "id": "adventure-hawaii",
      "chapterId": "adventure",
      "label": "ハワイ",
      "kind": "photo",
      "canonicalStem": "adventure-hawaii",
      "file": null,
      "ready": false
    },
    {
      "id": "adventure-trip",
      "chapterId": "adventure",
      "label": "旅行",
      "kind": "photo",
      "canonicalStem": "adventure-trip",
      "file": null,
      "ready": false
    },
    {
      "id": "adventure-dog",
      "chapterId": "adventure",
      "label": "犬との思い出",
      "kind": "photo",
      "canonicalStem": "adventure-dog",
      "file": null,
      "ready": false
    },
    {
      "id": "adventure-fun",
      "chapterId": "adventure",
      "label": "楽しい思い出",
      "kind": "photo",
      "canonicalStem": "adventure-fun",
      "file": null,
      "ready": false
    },
    {
      "id": "arrival-current-couple",
      "chapterId": "arrival",
      "label": "現在の二人",
      "kind": "photo",
      "canonicalStem": "arrival-current-couple",
      "file": null,
      "ready": false
    },
    {
      "id": "arrival-registration",
      "chapterId": "arrival",
      "label": "入籍",
      "kind": "photo",
      "canonicalStem": "arrival-registration",
      "file": null,
      "ready": false
    },
    {
      "id": "arrival-yokohama",
      "chapterId": "arrival",
      "label": "横浜・会場",
      "kind": "photo-or-video",
      "canonicalStem": "arrival-yokohama",
      "file": null,
      "ready": false
    }
  ],
  "bgm": {
    "assetId": "profile-bgm-main",
    "path": "public/audio/profile/bgm-main.mp3",
    "fileExists": false,
    "rightsState": "NOT_RUN",
    "ready": false
  },
  "structureReview": {
    "state": "NOT_RUN",
    "evidencePath": "out/qa/profile-v1-full-structure-review.json",
    "boundPreviewSha256": null,
    "currentPreviewSha256": null,
    "reviewer": null,
    "reviewedAt": null,
    "blockers": [
      "STRUCTURE_REVIEW_EVIDENCE_MISSING"
    ],
    "humanReviewComplete": false
  },
  "blockingGatePass": false,
  "qa": {
    "structurePreview": "NOT_RUN",
    "preview": "NOT_RUN",
    "humanContent": "NOT_RUN",
    "audio": "NOT_RUN",
    "macDaVinciActual": "NOT_RUN"
  },
  "productionReady": false,
  "nextActions": [
    "Profile実素材を public/profile/ へcanonical stem名で投入",
    "node --no-warnings scripts/profile-v1-assembly-preflight.mts"
  ]
} as const;
