// AUTO-GENERATED by scripts/sync-profile-generated-accents.mjs
// Motion Studio generated-accent manifest is the authority. Do not edit by hand.

export const profileGeneratedAccents = {
  "schemaVersion": "profile-v1-generated-accent-manifest/v1",
  "authority": "MOTION_STUDIO_CANONICAL_GENERATED_ACCENTS",
  "count": 3,
  "accents": [
    {
      "slotId": "departure-boarding-title",
      "chapterId": "departure",
      "label": "搭乗券風テロップ",
      "kind": "graphic",
      "required": false,
      "canonicalStem": "departure-boarding-title",
      "note": "Motion Studio側で生成可能な固定グラフィック。",
      "implementation": "PROFILE_BOARDING_TITLE_CARD",
      "canonicalReuse": "COMPOSITION_SPECIFIC_GRAPHIC",
      "source": "MOTION_STUDIO_GENERATED",
      "realMediaRequired": false
    },
    {
      "slotId": "intersection-route",
      "chapterId": "intersection",
      "label": "地図・航路",
      "kind": "graphic",
      "required": false,
      "canonicalStem": "intersection-route",
      "note": "Motion Zukan route-line等で生成可能。",
      "implementation": "MOTION_ZUKAN_ROUTE_LINE",
      "canonicalReuse": "TransitionWipeEngine/route-line",
      "source": "MOTION_STUDIO_GENERATED",
      "realMediaRequired": false
    },
    {
      "slotId": "arrival-door-light",
      "chapterId": "arrival",
      "label": "光・到着・扉",
      "kind": "graphic",
      "required": false,
      "canonicalStem": "arrival-door-light",
      "note": "Motion Studioで生成可能な演出。",
      "implementation": "OPENING_DOOR_LIGHT_REUSE",
      "canonicalReuse": "DoorLight",
      "source": "MOTION_STUDIO_GENERATED",
      "realMediaRequired": false
    }
  ],
  "productionEvidence": {
    "visualSmokeOnly": true,
    "humanRealMediaQa": "NOT_RUN",
    "macDaVinciActual": "NOT_RUN",
    "productionReady": false
  },
  "guardrails": [
    "GENERATED_ACCENT_IMPLEMENTED != HUMAN_REAL_MEDIA_QA_PASS",
    "VISUAL_SMOKE_PASS != MAC_DAVINCI_ACTUAL_VERIFIED",
    "OPTIONAL_GENERATED_ROLE != REQUIRED_REAL_MEDIA_SLOT"
  ]
} as const;
