// AUTO-GENERATED by scripts/sync-profile-production-status.mjs
// Motion Studio production status is the authority. Do not edit by hand.

export const profileProductionStatus = {
  "source": {
    "status": "motion-studio/scripts/profile-v1-production-status.mts",
    "palmierHandoff": "motion-studio/scripts/profile-v1-palmier-handoff-contract.mts",
    "davinciHandoff": "motion-studio/scripts/profile-v1-davinci-handoff-contract.mts"
  },
  "overallState": "ASSEMBLY_REQUIRED",
  "stages": {
    "assembly": {
      "state": "BLOCKED",
      "detail": "Generated accent contracts or assembly inputs/Human QA are not all ready.",
      "recovery": [
        "node --no-warnings scripts/intake-production-media.mts --project profile --source \"/ABS/PATH/TO/profile-media\"",
        "node --no-warnings scripts/intake-production-media.mts --project profile --source \"/ABS/PATH/TO/profile-media\" --apply --overwrite --receipt out/intake/profile-media-intake.json",
        "node --no-warnings scripts/verify-production-media-intake-receipt.mts --project profile",
        "pnpm prepare:profile-v1",
        "node --no-warnings scripts/intake-production-bgm.mts --project profile --source \"/ABS/PATH/TO/profile-bgm.mp3\"",
        "node --no-warnings scripts/intake-production-bgm.mts --project profile --source \"/ABS/PATH/TO/profile-bgm.mp3\" --apply --receipt out/intake/profile-bgm-intake.json",
        "node --no-warnings scripts/verify-production-bgm-intake-receipt.mts --project profile"
      ]
    },
    "finalRender": {
      "state": "NOT_RUN",
      "detail": "Blocked by full production preflight readiness.",
      "path": "out/profile/profile_v1.mp4",
      "recovery": [
        "pnpm render:profile-v1",
        "pnpm check:profile-render"
      ]
    },
    "finalRenderReview": {
      "state": "NOT_RUN",
      "detail": "Blocked until final render QA passes.",
      "path": "out/qa/profile-v1-final-render-review.json",
      "recovery": [
        "pnpm profile:final-render-review:init",
        "pnpm profile:final-render-review:strict"
      ]
    },
    "productionBundle": {
      "state": "NOT_RUN",
      "detail": "Blocked until current Human final-render review passes.",
      "path": "out/handoff/profile-v1/profile-v1-production-bundle.json",
      "recovery": [
        "pnpm export:profile-v1-production-bundle"
      ]
    },
    "davinciFinishing": {
      "state": "NOT_RUN",
      "detail": "Blocked until production bundle is current.",
      "path": "out/qa/profile-v1-davinci-finishing-evidence.json",
      "recovery": [
        "pnpm profile:davinci-finishing:init",
        "pnpm profile:davinci-finishing:strict"
      ]
    },
    "finalDeliveryApproval": {
      "state": "NOT_RUN",
      "detail": "Blocked until Mac DaVinci Actual is verified.",
      "path": "out/qa/profile-v1-final-delivery-approval.json",
      "recovery": [
        "pnpm profile:final-delivery-approval:init",
        "pnpm profile:final-delivery-approval:strict"
      ]
    }
  },
  "readiness": {
    "assemblyReady": false,
    "finalRenderQaPass": false,
    "humanFinalRenderReviewPass": false,
    "bundleCurrent": false,
    "macDaVinciActual": "NOT_RUN",
    "finalDeliveryApproved": false,
    "productionReady": false
  },
  "sourceRevalidation": {
    "realMediaPreview": {
      "state": "NOT_RUN",
      "blockers": [],
      "recovery": [
        "pnpm render:profile-v1:real-media-preview",
        "pnpm profile:real-media-review:init"
      ]
    },
    "finalRender": {
      "state": "NOT_RUN",
      "blockers": [],
      "recovery": []
    },
    "guardrails": [
      "SOURCE_CHANGED => RE_RENDER_REQUIRED",
      "RE_RENDER_REQUIRED => RE_REVIEW_REQUIRED",
      "OLD_HUMAN_REVIEW != CURRENT_RENDER_IMPLEMENTATION"
    ]
  },
  "handoff": {
    "palmier": {
      "contractVersion": "profile-v1-palmier-handoff/v1",
      "current": false,
      "sourceAuthorities": [
        "src/data/profileV1ProductionPlan.ts#profileV1Chapters",
        "src/data/profileV1GeneratedAccentRegistry.ts#profileV1GeneratedAccentImplementations"
      ],
      "artifacts": {
        "sceneTimeline": {
          "path": "out/handoff/profile-v1/profile-v1-palmier-timeline.csv",
          "shaBound": true,
          "carries": [
            "chapter_boundary",
            "chapter_role",
            "edit_intent",
            "generated_accent_routes",
            "final_render_sha256"
          ]
        }
      }
    },
    "davinci": {
      "contractVersion": "profile-v1-davinci-handoff/v1",
      "current": false,
      "sourceAuthorities": [
        "scripts/export-profile-v1-production-bundle.mts#bundle.davinci",
        "scripts/export-wedding-davinci-production-recovery.mts",
        "src/data/profileV1GeneratedAccentRegistry.ts#profileV1GeneratedAccentImplementations",
        "scripts/profile-v1-davinci-finishing-evidence.mts"
      ],
      "upstreamPalmier": {
        "timelinePath": "out/handoff/profile-v1/profile-v1-palmier-timeline.csv",
        "generatedAccentAuthority": "PROFILE_V1_GENERATED_ACCENT_REGISTRY"
      },
      "handoffAsset": {
        "path": "out/profile/profile_v1.mp4",
        "expectedSha256": null,
        "shaBound": true,
        "intendedUse": "FINISHING_AND_OUTPUT_QA"
      },
      "generatedAccentRoutes": [
        {
          "slotId": "departure-boarding-title",
          "chapterId": "departure",
          "implementation": "PROFILE_BOARDING_TITLE_CARD",
          "canonicalReuse": "COMPOSITION_SPECIFIC_GRAPHIC"
        },
        {
          "slotId": "intersection-route",
          "chapterId": "intersection",
          "implementation": "MOTION_ZUKAN_ROUTE_LINE",
          "canonicalReuse": "TransitionWipeEngine/route-line"
        },
        {
          "slotId": "arrival-door-light",
          "chapterId": "arrival",
          "implementation": "OPENING_DOOR_LIGHT_REUSE",
          "canonicalReuse": "DoorLight"
        }
      ],
      "productionRecovery": {
        "path": "out/handoff/profile-v1/profile-v1-davinci-production-recovery.json",
        "schemaVersion": "wedding-davinci-production-recovery-export/v1",
        "authority": "FINAL_RENDER_BOUND_DAVINCI_RECOVERY",
        "sourceRenderSha256": null,
        "actualState": "NOT_RUN",
        "requiredCurrent": true
      },
      "actualEvidence": {
        "path": "out/qa/profile-v1-davinci-finishing-evidence.json",
        "schemaVersion": "profile-v1-davinci-finishing-evidence/v1",
        "authority": "MAC_DAVINCI_ACTUAL_EVIDENCE",
        "commands": {
          "init": "pnpm profile:davinci-finishing:init",
          "status": "pnpm profile:davinci-finishing",
          "strict": "pnpm profile:davinci-finishing:strict"
        },
        "requiredChecks": [
          "source_render_sha_readback",
          "resolve_version_project_timeline",
          "timeline_insertion",
          "duration_and_fps",
          "color_finish",
          "audio_finish",
          "title_safe_and_framing",
          "playback_1x",
          "playback_half_speed",
          "export_duration_dimensions_fps_audio",
          "watched_with_sound",
          "human_overall_review"
        ]
      },
      "productionReady": false
    }
  },
  "nextActions": [
    "node --no-warnings scripts/intake-production-media.mts --project profile --source \"/ABS/PATH/TO/profile-media\"",
    "node --no-warnings scripts/intake-production-media.mts --project profile --source \"/ABS/PATH/TO/profile-media\" --apply --overwrite --receipt out/intake/profile-media-intake.json",
    "node --no-warnings scripts/verify-production-media-intake-receipt.mts --project profile",
    "pnpm prepare:profile-v1",
    "node --no-warnings scripts/intake-production-bgm.mts --project profile --source \"/ABS/PATH/TO/profile-bgm.mp3\"",
    "node --no-warnings scripts/intake-production-bgm.mts --project profile --source \"/ABS/PATH/TO/profile-bgm.mp3\" --apply --receipt out/intake/profile-bgm-intake.json",
    "node --no-warnings scripts/verify-production-bgm-intake-receipt.mts --project profile"
  ]
} as const;
