// AUTO-GENERATED by scripts/sync-profile-real-media-review-gate.mjs
// Human evidence lives under motion-studio/out and is never manufactured by this file.

export const profileRealMediaReviewGate = {
  "source": "motion-studio/scripts/profile-v1-real-media-review.mts",
  "state": "NOT_RUN",
  "humanReviewComplete": false,
  "blockers": [
    "REAL_MEDIA_REVIEW_EVIDENCE_MISSING"
  ],
  "mediaExpected": 17,
  "mediaReviewed": 0,
  "bgmReviewed": false,
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false,
  "audit": {
    "evidencePath": "motion-studio/out/qa/profile-v1-real-media-review.json",
    "evidenceExists": false,
    "evidenceSha256": null,
    "parseState": "MISSING",
    "boundAt": null,
    "preview": null,
    "previewSourceFingerprintSha256": null,
    "previewSources": [],
    "runtimeManifestSha256": null,
    "productionPlanSha256": null,
    "previewComponentSha256": null,
    "canonicalPlanFingerprint": null,
    "media": [],
    "chapters": [],
    "review": {
      "overall": "NOT_RUN",
      "reviewedAt": null
    }
  }
} as const;
