// AUTO-GENERATED by scripts/sync-profile-assembly-review-readiness.mjs
// Motion Studio Profile assembly preflight is the authority. Do not edit by hand.

export const profileAssemblyReviewReadiness = {
  "source": "motion-studio/scripts/profile-v1-assembly-preflight.mts",
  "finalRenderEligible": false,
  "assemblyReady": false,
  "structureReview": {
    "state": "NOT_RUN",
    "humanReviewComplete": false,
    "evidencePath": "out/qa/profile-v1-full-structure-review.json",
    "blockers": [
      "STRUCTURE_REVIEW_EVIDENCE_MISSING"
    ]
  },
  "realMediaReview": {
    "state": "NOT_RUN",
    "humanReviewComplete": false,
    "evidencePath": "",
    "blockers": [
      "REAL_MEDIA_REVIEW_EVIDENCE_MISSING"
    ],
    "reviewedCount": 0,
    "expectedCount": 17
  },
  "audioReview": {
    "state": "NOT_RUN",
    "humanReviewComplete": false,
    "evidencePath": "out/qa/profile-v1-audio-listening-review.json",
    "blockers": [
      "PROFILE_AUDIO_LISTENING_REVIEW_EVIDENCE_MISSING"
    ]
  },
  "guardrails": [
    "FINAL_RENDER_ELIGIBLE != HUMAN_QA_COMPLETE",
    "STRUCTURE_REVIEW_PASS != REAL_MEDIA_REVIEW_PASS",
    "REAL_MEDIA_REVIEW_PASS != AUDIO_REVIEW_PASS",
    "DASHBOARD_STATUS != GUI_ACTUAL_EVIDENCE"
  ]
} as const;
