// AUTO-GENERATED by scripts/sync-start-sync-listening-review-gate.mjs
// Human listening evidence remains local/ignored; lyrics and audio are never copied into this snapshot.

export const startSyncListeningReviewGate = {
  "source": "motion-studio/scripts/japanese-friends-opening-start-sync-listening-review.mts",
  "state": "NOT_RUN",
  "humanReviewComplete": false,
  "blockers": [
    "START_SYNC_LISTENING_REVIEW_EVIDENCE_MISSING"
  ],
  "phrasesReviewed": 0,
  "phrasesExpected": 30,
  "rightsCleared": false,
  "publicationApproved": false,
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false,
  "manifest": {
    "path": "movie-dashboard/public/demo-renders/japanese-friends-opening-start-sync-v1.manifest.json",
    "sha256": "2560ce2fcf2016b767ab56a126c7cc34d3fbe5437a98bd2dae0ff98a27603bde",
    "generatedAt": "2026-08-31T13:14:58.150Z",
    "artifact": {
      "file": "japanese-friends-opening-start-sync-v1.mp4",
      "sha256": "d585d11c09f59f03d5216c87034b0e0c0afec7c143ea66da81fb455696d0d458",
      "byteSize": 243627709
    },
    "source": {
      "title": "StaRt",
      "editEndSeconds": 145.6,
      "bpm": 187.5
    },
    "timing": {
      "lyricPhraseCount": 30,
      "measuredThreeHitPhraseCount": 4,
      "verifiedByListening": false,
      "humanReviewRequired": true
    },
    "qa": {
      "status": "AUTOMATED_PASSED",
      "checks": [
        "resolution",
        "fps",
        "duration",
        "audio-format",
        "black-detect",
        "silence-detect"
      ]
    }
  },
  "mediaPath": "/demo-renders/japanese-friends-opening-start-sync-v1.mp4",
  "audit": {
    "evidencePath": "motion-studio/out/qa/japanese-friends-opening-start-sync-listening-review.json",
    "evidenceExists": false,
    "evidenceSha256": null,
    "parseState": "MISSING",
    "boundAt": null,
    "manifestSha256": null,
    "artifactSha256": null,
    "sourceAudioSha256": null,
    "lyricTimingFingerprintSha256": null,
    "phraseCount": 30,
    "measuredThreeHitPhraseCount": 4,
    "phrases": [],
    "checks": {
      "fullPlayback": "NOT_RUN",
      "lyricTimingOverall": "NOT_RUN",
      "measuredThreeHitTiming": "NOT_RUN",
      "transitionRhythm": "NOT_RUN",
      "endingLockupTiming": "NOT_RUN",
      "audioVisualSync": "NOT_RUN"
    },
    "review": {
      "overall": "NOT_RUN",
      "reviewer": null,
      "reviewedAt": null,
      "notes": ""
    }
  }
} as const;
