// AUTO-GENERATED by scripts/sync-start-sync-listening-review-gate.mjs
// Human listening evidence remains local/ignored; lyrics and audio are never copied into this snapshot.

export const startSyncListeningReviewGate = {
  "source": "motion-studio/scripts/japanese-friends-opening-start-sync-listening-review.mts",
  "state": "NOT_RUN",
  "humanReviewComplete": false,
  "blockers": [
    "START_SYNC_LISTENING_REVIEW_EVIDENCE_MISSING"
  ],
  "phrasesReviewed": 0,
  "phrasesExpected": 30,
  "rightsCleared": false,
  "publicationApproved": false,
  "macDaVinciActual": "NOT_RUN",
  "productionReady": false,
  "manifest": {
    "path": "movie-dashboard/public/demo-renders/japanese-friends-opening-start-sync-v1.manifest.json",
    "sha256": "dd3e0e36538057de817f8378f174568dfd94ff3533e42626c1bc1819e9fe462a",
    "generatedAt": "2026-08-31T02:44:43.970Z",
    "artifact": {
      "file": "japanese-friends-opening-start-sync-v1.mp4",
      "sha256": "47583a4ab4ebf031a8d8cb6aac5712835a73526911842733bc8a66dac6307ee6",
      "byteSize": 161470450
    },
    "source": {
      "title": "StaRt",
      "editEndSeconds": 145.6,
      "bpm": 187.5
    },
    "timing": {
      "lyricPhraseCount": 30,
      "measuredThreeHitPhraseCount": 4,
      "verifiedByListening": false,
      "humanReviewRequired": true
    },
    "qa": {
      "status": "AUTOMATED_PASSED",
      "checks": [
        "resolution",
        "fps",
        "duration",
        "audio-format",
        "black-detect",
        "silence-detect"
      ]
    }
  },
  "mediaPath": "/demo-renders/japanese-friends-opening-start-sync-v1.mp4",
  "audit": {
    "evidencePath": "motion-studio/out/qa/japanese-friends-opening-start-sync-listening-review.json",
    "evidenceExists": false,
    "evidenceSha256": null,
    "parseState": "MISSING",
    "boundAt": null,
    "manifestSha256": null,
    "artifactSha256": null,
    "sourceAudioSha256": null,
    "lyricTimingFingerprintSha256": null,
    "phraseCount": 30,
    "measuredThreeHitPhraseCount": 4,
    "phrases": [],
    "checks": {
      "fullPlayback": "NOT_RUN",
      "lyricTimingOverall": "NOT_RUN",
      "measuredThreeHitTiming": "NOT_RUN",
      "transitionRhythm": "NOT_RUN",
      "endingLockupTiming": "NOT_RUN",
      "audioVisualSync": "NOT_RUN"
    },
    "review": {
      "overall": "NOT_RUN",
      "reviewer": null,
      "reviewedAt": null,
      "notes": ""
    }
  }
} as const;
