// AUTO-GENERATED by scripts/sync-wedding-final-approval-completion-readiness.mjs
// Read-only snapshot of the canonical final approval completion binding gate. Do not edit by hand.

export const weddingFinalApprovalCompletionReadiness = {
  "schemaVersion": "wedding-final-approval-completion-dashboard/v1",
  "authority": "MOTION_STUDIO_DERIVED_FINAL_APPROVAL_COMPLETION_READINESS",
  "generatedFrom": "motion-studio/scripts/wedding-davinci-delivery-readiness.mts --json",
  "opening": {
    "state": "BLOCKED",
    "current": false,
    "bindingPath": "out/qa/opening-v1-final-approval-completion-binding.json",
    "bindingSha256": null,
    "finalApprovalSha256": null,
    "completionReceiptSha256": null,
    "transitionProofSha256": null,
    "recoverySha256": null,
    "finishingEvidenceSha256": null,
    "writeCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-approval-completion-binding.mts --movie=opening --write",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-approval-completion-binding.mts --movie=opening"
  },
  "profile": {
    "state": "BLOCKED",
    "current": false,
    "bindingPath": "out/qa/profile-v1-final-approval-completion-binding.json",
    "bindingSha256": null,
    "finalApprovalSha256": null,
    "completionReceiptSha256": null,
    "transitionProofSha256": null,
    "recoverySha256": null,
    "finishingEvidenceSha256": null,
    "writeCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-approval-completion-binding.mts --movie=profile --write",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-approval-completion-binding.mts --movie=profile"
  },
  "guardrails": [
    "DERIVED_BINDING != HUMAN_FINAL_APPROVAL",
    "DERIVED_BINDING != LIVE_MAC_DAVINCI_GUI_ACTUAL",
    "CURRENT_REQUIRES_HUMAN_FINAL_APPROVAL_AND_ACTUAL_COMPLETION_ON_SAME_RECOVERY",
    "FINAL_APPROVAL_OR_COMPLETION_RECEIPT_SHA_CHANGED => BINDING_STALE"
  ]
} as const;
