// AUTO-GENERATED by scripts/sync-wedding-project-motion-provenance-preflight.mjs
// Motion Studio Project Motion provenance preflight for Motion Zukan display. Do not edit by hand.

export const weddingProjectMotionProvenancePreflight = {
  "schemaVersion": "wedding-project-motion-dashboard-preflight/v1",
  "authority": "MOTION_STUDIO_DERIVED_PROJECT_MOTION_PROVENANCE_PREFLIGHT",
  "opening": {
    "state": "NOT_APPLICABLE",
    "current": false,
    "applicable": false,
    "command": "node --no-warnings scripts/verify-wedding-project-motion-production-provenance.mts --movie=opening",
    "error": null
  },
  "profile": {
    "state": "NOT_APPLICABLE",
    "current": false,
    "applicable": false,
    "command": "node --no-warnings scripts/verify-wedding-project-motion-production-provenance.mts --movie=profile",
    "error": null
  },
  "guardrails": [
    "GENERATED_DASHBOARD_SNAPSHOT != LIVE_MAC_GUI_ACTUAL",
    "PROJECT_MOTION_CURRENT_REQUIRES_CANONICAL_PROVENANCE_VERIFIER_PASS",
    "PROJECT_MOTION_INVALID => FINAL_DELIVERY_BLOCKED",
    "NOT_APPLICABLE != VERIFIED",
    "CI_MUST_NOT_PROMOTE_MAC_GUI_ACTUAL"
  ]
} as const;
