// AUTO-GENERATED by scripts/sync-wedding-davinci-actual-completion-readiness.mjs
// Read-only snapshot of the canonical DaVinci Actual completion receipt gate. Do not edit by hand.

export const weddingDavinciActualCompletionReadiness = {
  "schemaVersion": "wedding-davinci-actual-completion-dashboard/v1",
  "authority": "MOTION_STUDIO_DERIVED_DAVINCI_ACTUAL_COMPLETION_READINESS",
  "generatedFrom": "motion-studio/scripts/wedding-davinci-delivery-readiness.mts --json",
  "opening": {
    "state": "BLOCKED",
    "current": false,
    "receiptPath": "out/qa/opening-v1-davinci-actual-completion-receipt.json",
    "receiptSha256": null,
    "recoverySha256": null,
    "finishingEvidenceSha256": null,
    "transitionEvidenceSha256": null,
    "transitionProofSha256": null,
    "writeCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-actual-completion-receipt.mts --movie=opening --write",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-actual-completion-receipt.mts --movie=opening"
  },
  "profile": {
    "state": "BLOCKED",
    "current": false,
    "receiptPath": "out/qa/profile-v1-davinci-actual-completion-receipt.json",
    "receiptSha256": null,
    "recoverySha256": null,
    "finishingEvidenceSha256": null,
    "transitionEvidenceSha256": null,
    "transitionProofSha256": null,
    "writeCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-actual-completion-receipt.mts --movie=profile --write",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-actual-completion-receipt.mts --movie=profile"
  },
  "guardrails": [
    "RECEIPT_DERIVED_ONLY != LIVE_MAC_DAVINCI_GUI_ACTUAL",
    "CURRENT_REQUIRES_FINISHING_AND_TRANSITION_HUMAN_PASS_ON_SAME_RECOVERY_SHA",
    "FINISHING_OR_TRANSITION_EVIDENCE_SHA_CHANGED => COMPLETION_RECEIPT_STALE",
    "COMPLETION_RECEIPT_CURRENT_REQUIRED_BEFORE_FINAL_DELIVERY_READY"
  ]
} as const;
