// AUTO-GENERATED by scripts/sync-wedding-final-delivery-evidence-manifest-readiness.mjs
// Read-only snapshot. Canonical currentness remains the Motion Studio CLI strict verifier.

export const weddingFinalDeliveryEvidenceManifestReadiness = {
  "schemaVersion": "wedding-final-delivery-evidence-manifest-dashboard/v1",
  "authority": "MOTION_STUDIO_DERIVED_FINAL_DELIVERY_EVIDENCE_MANIFEST_READINESS",
  "generatedFrom": "node --no-warnings scripts/wedding-final-delivery-evidence-manifest-currentness.mts --json",
  "state": "NOT_RUN",
  "current": false,
  "manifestPath": "out/handoff/wedding/wedding-final-delivery-evidence-manifest.json",
  "mismatches": [
    "FINAL_DELIVERY_EVIDENCE_MANIFEST_MISSING"
  ],
  "manifestSha256": null,
  "readinessSha256": null,
  "openingEvidenceChainSha256": null,
  "profileEvidenceChainSha256": null,
  "writeCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-delivery-evidence-manifest.mts --write",
  "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-delivery-evidence-manifest-currentness.mts --strict-current",
  "guardrails": [
    "GENERATED_DASHBOARD_SNAPSHOT != LIVE_MAC_DAVINCI_GUI_ACTUAL",
    "CURRENT_REQUIRES_CANONICAL_CLI_STRICT_CURRENT",
    "MISSING_MANIFEST => NOT_RUN",
    "ANY_BOUND_SHA_DRIFT => STALE",
    "HUMAN_FINAL_APPROVAL_NOT_PROMOTED_BY_DASHBOARD"
  ]
} as const;
