// AUTO-GENERATED by scripts/sync-wedding-project-remotion-identity-preflight.mjs
// Motion Studio Project Remotion identity preflight for Motion Zukan display. Do not edit by hand.

export const weddingProjectRemotionIdentityPreflight = {
  "schemaVersion": "wedding-project-remotion-identity-dashboard-preflight/v1",
  "authority": "MOTION_STUDIO_DERIVED_PROJECT_REMOTION_IDENTITY_PREFLIGHT",
  "opening": {
    "state": "NOT_APPLICABLE",
    "current": false,
    "applicable": false,
    "command": "node --no-warnings scripts/verify-wedding-production-handoff-provenance.mts --movie=opening",
    "resolveSidecarSha256": null,
    "receiptSha256": null,
    "sourceBatchSha256": null,
    "error": null
  },
  "profile": {
    "state": "NOT_APPLICABLE",
    "current": false,
    "applicable": false,
    "command": "node --no-warnings scripts/verify-wedding-production-handoff-provenance.mts --movie=profile",
    "resolveSidecarSha256": null,
    "receiptSha256": null,
    "sourceBatchSha256": null,
    "error": null
  },
  "guardrails": [
    "GENERATED_DASHBOARD_SNAPSHOT != LIVE_MAC_GUI_ACTUAL",
    "PROJECT_REMOTION_IDENTITY_CURRENT_REQUIRES_CANONICAL_PRODUCTION_HANDOFF_VERIFIER_PASS",
    "PROJECT_REMOTION_IDENTITY_INVALID => GUI_ACTUAL_START_BLOCKED",
    "PROJECT_REMOTION_IDENTITY_NOT_APPLICABLE != VERIFIED",
    "CI_MUST_NOT_PROMOTE_MAC_GUI_ACTUAL"
  ]
} as const;
