// AUTO-GENERATED by scripts/sync-wedding-davinci-transition-actual-readiness.mjs
// Read-only snapshot of the canonical transition Actual delivery gate. Do not edit by hand.

export const weddingDavinciTransitionActualReadiness = {
  "schemaVersion": "wedding-davinci-transition-actual-dashboard/v1",
  "authority": "MOTION_STUDIO_DERIVED_TRANSITION_ACTUAL_READINESS",
  "generatedFrom": "motion-studio/scripts/wedding-davinci-delivery-readiness.mts --json",
  "opening": {
    "state": "BLOCKED",
    "current": false,
    "evidencePath": "out/qa/opening-v1-davinci-transition-actual-evidence.json",
    "evidenceSha256": null,
    "transitionProofSha256": null,
    "edgeCount": null,
    "crossDissolveCount": null,
    "reviewOverall": "NOT_RUN",
    "initCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-transition-actual-evidence.mts --movie=opening --init",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-transition-actual-evidence.mts --movie=opening --strict",
    "finalGateCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-delivery-transition-gate.mts --movie=opening"
  },
  "profile": {
    "state": "BLOCKED",
    "current": false,
    "evidencePath": "out/qa/profile-v1-davinci-transition-actual-evidence.json",
    "evidenceSha256": null,
    "transitionProofSha256": null,
    "edgeCount": null,
    "crossDissolveCount": null,
    "reviewOverall": "NOT_RUN",
    "initCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-transition-actual-evidence.mts --movie=profile --init",
    "strictCommand": "cd motion-studio && node --no-warnings scripts/wedding-davinci-transition-actual-evidence.mts --movie=profile --strict",
    "finalGateCommand": "cd motion-studio && node --no-warnings scripts/wedding-final-delivery-transition-gate.mts --movie=profile"
  },
  "guardrails": [
    "GENERATED_DASHBOARD_SNAPSHOT != LIVE_MAC_DAVINCI_GUI_ACTUAL",
    "NOT_RUN != PASS",
    "CURRENT_REQUIRES_CANONICAL_CLI_STRICT",
    "EVIDENCE_OR_TRANSITION_PROOF_SHA_CHANGED => DASHBOARD_SNAPSHOT_STALE"
  ]
} as const;
