import {spawnSync} from 'node:child_process';
import {readFileSync, writeFileSync} from 'node:fs';
import {join, relative, resolve} from 'node:path';

const motionStudioRoot = process.cwd();
const repoRoot = resolve(motionStudioRoot, '..');
const outputPath = join(repoRoot, 'movie-dashboard/src/generated/weddingProjectRemotionStageStatus.ts');

type MovieId = 'opening' | 'profile';
type CheckerReport = {
  movieId: MovieId;
  state: 'NOT_STAGED' | 'STAGED_CURRENT' | 'HANDOFF_CURRENT' | 'INVALID';
  blocker: string | null;
  detail: string | null;
  checks: {
    stageVerification: 'NOT_RUN' | 'CURRENT' | 'INVALID';
    handoffVerification: 'NOT_RUN' | 'CURRENT' | 'INVALID';
  };
  next: {kind: string; command: string};
  canonicalArtifacts: Record<string, string>;
};

const runChecker = (movieId: MovieId): CheckerReport => {
  const result = spawnSync(
    process.execPath,
    ['--no-warnings', join(motionStudioRoot, 'scripts/check-wedding-project-remotion-production-stage-status.mts'), `--movie=${movieId}`, '--json'],
    {cwd: motionStudioRoot, encoding: 'utf8'},
  );
  if (result.status !== 0) {
    throw new Error(`stage status checker failed for ${movieId}: ${result.stderr || result.stdout}`);
  }
  return JSON.parse(result.stdout) as CheckerReport;
};

const normalizePath = (path: string) => relative(repoRoot, path).replaceAll('\\', '/');
const normalize = (report: CheckerReport) => ({
  movieId: report.movieId,
  state: report.state,
  blocker: report.blocker,
  detail: report.detail,
  checks: report.checks,
  next: report.next,
  canonicalArtifacts: Object.fromEntries(Object.entries(report.canonicalArtifacts).map(([key, path]) => [key, normalizePath(path)])),
});

const snapshot = {
  schemaVersion: 'wedding-project-remotion-stage-status-dashboard/v1',
  authority: 'GENERATED_FROM_READ_ONLY_CANONICAL_STAGE_STATUS_CHECKER',
  opening: normalize(runChecker('opening')),
  profile: normalize(runChecker('profile')),
  evidenceBoundary: {
    macRemotionStudioGuiActual: 'NOT_RUN_UNLESS_HUMAN_EXECUTED',
    macDavinciResolveGuiActual: 'NOT_RUN_UNLESS_HUMAN_EXECUTED',
    productionReadyPromotedBySnapshot: false,
  },
} as const;

const rendered = `// AUTO-GENERATED by generate-wedding-project-remotion-stage-status-dashboard.mts\n// Do not hand-edit. Regenerate from motion-studio canonical artifacts.\n\nexport const weddingProjectRemotionStageStatus = ${JSON.stringify(snapshot, null, 2)} as const;\n`;

if (process.argv.includes('--check')) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== rendered) {
    console.error('BLOCK / WEDDING_PROJECT_REMOTION_STAGE_STATUS_DASHBOARD_DRIFT');
    process.exit(2);
  }
  console.log('PASS / WEDDING_PROJECT_REMOTION_STAGE_STATUS_DASHBOARD_CURRENT');
} else {
  writeFileSync(outputPath, rendered);
  console.log(`wrote=${relative(repoRoot, outputPath)}`);
}
