import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {aliases, orderedKeys} from '../src/data/openingV1PhotoRoles.ts';
import {profileV1RequiredMediaSlots} from '../src/data/profileV1ProductionPlan.ts';

const studioRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(studioRoot, '..');
const outputPath = join(repoRoot, 'movie-dashboard/src/data/weddingMediaIntakeChecklist.generated.ts');
const check = process.argv.includes('--check');

const payload = {
  schemaVersion: 'wedding-media-intake-checklist/v1',
  authority: 'MOTION_STUDIO_INTAKE_SPECS',
  opening: {
    projectId: 'opening',
    expectedCount: orderedKeys.length,
    targetDirectory: 'motion-studio/public/photos/opening',
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
    slots: orderedKeys.map((id) => ({
      id,
      canonicalStem: id,
      kind: 'photo',
      aliases: aliases[id],
    })),
  },
  profile: {
    projectId: 'profile',
    expectedCount: profileV1RequiredMediaSlots.length,
    targetDirectory: 'motion-studio/public/profile',
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.mp4', '.mov', '.m4v', '.webm'],
    slots: profileV1RequiredMediaSlots.map((slot) => ({
      id: slot.id,
      canonicalStem: slot.canonicalStem,
      kind: slot.kind,
      aliases: [slot.canonicalStem],
      chapterId: slot.chapterId,
      label: slot.label,
      note: slot.note,
    })),
  },
  evidenceBoundary: {
    humanQaState: 'NOT_RUN',
    macDaVinciActualState: 'NOT_RUN',
    productionReady: false,
  },
} as const;

const content = `// AUTO-GENERATED by motion-studio/scripts/generate-wedding-media-intake-checklist-dashboard.mts\n// Source authority: openingV1PhotoRoles.ts + profileV1ProductionPlan.ts. Do not edit by hand.\n\nexport const weddingMediaIntakeChecklist = ${JSON.stringify(payload, null, 2)} as const;\n`;

if (check) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== content) {
    console.error('weddingMediaIntakeChecklist.generated.ts is stale');
    process.exit(1);
  }
  console.log('Wedding media intake checklist dashboard is current.');
} else {
  writeFileSync(outputPath, content, 'utf8');
  console.log(`Wrote ${outputPath}`);
}
