import {existsSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import {dirname, extname, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {profileV1RequiredMediaSlots} from '../src/data/profileV1ProductionPlan.ts';

const studioRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const mediaRoot = join(studioRoot, 'public/profile');
const outputPath = join(studioRoot, 'src/data/profileV1RuntimeMedia.generated.ts');
const mediaExts = new Set(['.jpg', '.jpeg', '.png', '.webp', '.mp4', '.mov', '.m4v', '.webm']);

const normalizeStem = (file: string) => {
  const ext = extname(file);
  return file.slice(0, file.length - ext.length).toLowerCase().replaceAll('_', '-');
};

const files = existsSync(mediaRoot)
  ? readdirSync(mediaRoot)
      .filter((file) => !file.startsWith('.'))
      .filter((file) => statSync(join(mediaRoot, file)).isFile())
      .filter((file) => mediaExts.has(extname(file).toLowerCase()))
      .sort((a, b) => a.localeCompare(b, 'en'))
  : [];
const byStem = new Map(files.map((file) => [normalizeStem(file), file]));

const slots = profileV1RequiredMediaSlots.map((slot) => {
  const file = byStem.get(slot.canonicalStem) ?? null;
  return {
    id: slot.id,
    chapterId: slot.chapterId,
    label: slot.label,
    kind: slot.kind,
    canonicalStem: slot.canonicalStem,
    file,
    staticFilePath: file ? `profile/${file}` : null,
    extension: file ? extname(file).toLowerCase() : null,
    resolved: Boolean(file),
  };
});

const snapshot = {
  schemaVersion: 'profile-v1-runtime-media/v1',
  authority: 'GENERATED_FROM_CANONICAL_PROFILE_MEDIA_DIRECTORY',
  sourceDirectory: relative(studioRoot, mediaRoot).replaceAll('\\', '/'),
  expectedCount: slots.length,
  resolvedCount: slots.filter((slot) => slot.resolved).length,
  missingCount: slots.filter((slot) => !slot.resolved).length,
  slots,
};

const output = `// AUTO-GENERATED by scripts/sync-profile-v1-runtime-media.mts\n// Source authority: public/profile + src/data/profileV1ProductionPlan.ts. Do not edit by hand.\n\nexport const profileV1RuntimeMedia = ${JSON.stringify(snapshot, null, 2)} as const;\n`;

if (process.argv.includes('--write')) {
  writeFileSync(outputPath, output, 'utf8');
  console.log(`Profile V1 runtime media synced: ${snapshot.resolvedCount}/${snapshot.expectedCount}`);
  process.exit(0);
}

if (!existsSync(outputPath)) {
  console.error('Profile V1 runtime media generated file missing. Run: node --no-warnings scripts/sync-profile-v1-runtime-media.mts --write');
  process.exit(1);
}

const current = await import('node:fs').then(({readFileSync}) => readFileSync(outputPath, 'utf8'));
if (current !== output) {
  console.error(`Profile V1 runtime media stale: ${snapshot.resolvedCount}/${snapshot.expectedCount}`);
  console.error('Run: node --no-warnings scripts/sync-profile-v1-runtime-media.mts --write');
  process.exit(1);
}

console.log(`Profile V1 runtime media current: ${snapshot.resolvedCount}/${snapshot.expectedCount}`);
