import {createHash} from 'node:crypto';
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {profileV1RuntimeMedia} from '../src/data/profileV1RuntimeMedia.generated.ts';

const studioRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const evidencePath = join(studioRoot, 'out/qa/profile-v1-real-media-review.json');
const outputPath = join(studioRoot, 'src/data/profileV1FramingVerdicts.generated.ts');
const mode = process.argv.includes('--write') ? 'write' : 'check';

type QaState = 'NOT_RUN' | 'PASS' | 'FAIL';
type Framing = {fit: 'cover' | 'contain'; objectPosition?: string};
type MediaEvidence = {
  slot?: unknown;
  qa?: {crop?: QaState; focus?: QaState};
  framing?: {fit?: unknown; focusX?: unknown; focusY?: unknown};
};
type ReviewEvidence = {media?: MediaEvidence[]};

const shaFile = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
const canonicalIds = profileV1RuntimeMedia.slots.map((slot) => slot.id);

const validPercent = (value: unknown): value is number =>
  typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 100;

export const approvedFramingFor = (media: MediaEvidence | undefined): Framing | null => {
  if (!media || media.qa?.crop !== 'PASS' || media.qa?.focus !== 'PASS') return null;
  const fit = media.framing?.fit;
  if (fit !== 'cover' && fit !== 'contain') return null;

  const focusX = media.framing?.focusX;
  const focusY = media.framing?.focusY;
  if (focusX == null && focusY == null) return {fit};
  if (!validPercent(focusX) || !validPercent(focusY)) return null;
  return {fit, objectPosition: `${focusX}% ${focusY}%`};
};

const readEvidence = (): {evidence: ReviewEvidence | null; sourceEvidence: string | null} => {
  if (!existsSync(evidencePath)) return {evidence: null, sourceEvidence: null};
  try {
    return {
      evidence: JSON.parse(readFileSync(evidencePath, 'utf8')) as ReviewEvidence,
      sourceEvidence: shaFile(evidencePath),
    };
  } catch {
    throw new Error('PROFILE_FRAMING_EVIDENCE_INVALID_JSON');
  }
};

const render = () => {
  const {evidence, sourceEvidence} = readEvidence();
  const mediaBySlot = new Map(
    Array.isArray(evidence?.media)
      ? evidence.media
          .filter((item): item is MediaEvidence & {slot: string} => typeof item?.slot === 'string')
          .map((item) => [item.slot, item])
      : [],
  );

  const decisions = canonicalIds.map((slotId) => [slotId, approvedFramingFor(mediaBySlot.get(slotId))] as const);
  const approvedCount = decisions.filter(([, framing]) => framing !== null).length;
  const lines = decisions.map(([slotId, framing]) => {
    const serialized = framing ? JSON.stringify(framing) : 'null';
    return `    ${JSON.stringify(slotId)}: ${serialized},`;
  });

  return `// AUTO-GENERATED by scripts/sync-profile-v1-framing-verdicts.mts\n// Source authority: out/qa/profile-v1-real-media-review.json Human crop/focus verdicts.\n// Do not edit by hand. Missing/unapproved Human evidence intentionally resolves to null.\n\nexport type ProfileV1ApprovedFraming = {\n  fit: 'cover' | 'contain';\n  objectPosition?: string;\n};\n\nexport const profileV1FramingVerdicts = {\n  schemaVersion: 'profile-v1-framing-verdicts/v1',\n  authority: 'GENERATED_FROM_HUMAN_REAL_MEDIA_REVIEW',\n  sourceEvidence: ${sourceEvidence ? JSON.stringify(sourceEvidence) : 'null'},\n  approvedCount: ${approvedCount},\n  decisions: {\n${lines.join('\n')}\n  },\n} as const;\n\nexport const getProfileV1ApprovedFraming = (slotId: string): ProfileV1ApprovedFraming | null => {\n  const decisions = profileV1FramingVerdicts.decisions as Record<string, ProfileV1ApprovedFraming | null>;\n  return decisions[slotId] ?? null;\n};\n`;
};

const expected = render();
if (mode === 'write') {
  writeFileSync(outputPath, expected);
  console.log(`Profile framing verdicts written: ${relative(studioRoot, outputPath)}.`);
  process.exit(0);
}

if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== expected) {
  console.error('PROFILE_FRAMING_VERDICTS_STALE: run node --no-warnings scripts/sync-profile-v1-framing-verdicts.mts --write');
  process.exit(1);
}
console.log('Profile framing verdicts CURRENT. Unapproved Human crop/focus decisions remain null.');
