import {existsSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import {dirname, extname, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {profileV1RequiredMediaSlots} from '../src/data/profileV1ProductionPlan.ts';

const studioRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const mediaRoot = join(studioRoot, 'public/profile');
const outputPath = join(studioRoot, 'src/data/profileV1RuntimeMedia.generated.ts');
const imageExts = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const videoExts = new Set(['.mp4', '.mov', '.m4v', '.webm']);
const mediaExts = new Set([...imageExts, ...videoExts]);

const normalizeStem = (file: string) => {
  const ext = extname(file);
  return file.slice(0, file.length - ext.length).toLowerCase().replaceAll('_', '-');
};

const files = existsSync(mediaRoot)
  ? readdirSync(mediaRoot)
      .filter((file) => !file.startsWith('.'))
      .filter((file) => statSync(join(mediaRoot, file)).isFile())
      .filter((file) => mediaExts.has(extname(file).toLowerCase()))
      .sort((a, b) => a.localeCompare(b, 'en'))
  : [];

const filesByStem = new Map<string, string[]>();
for (const file of files) {
  const stem = normalizeStem(file);
  const existing = filesByStem.get(stem) ?? [];
  existing.push(file);
  filesByStem.set(stem, existing);
}

const acceptsKind = (kind: (typeof profileV1RequiredMediaSlots)[number]['kind'], file: string) => {
  const ext = extname(file).toLowerCase();
  if (kind === 'photo') return imageExts.has(ext);
  if (kind === 'video') return videoExts.has(ext);
  if (kind === 'photo-or-video') return imageExts.has(ext) || videoExts.has(ext);
  return false;
};

const ambiguities: {id: string; canonicalStem: string; compatibleFiles: string[]}[] = [];
const incompatibilities: {id: string; canonicalStem: string; kind: string; incompatibleFiles: string[]}[] = [];

const slots = profileV1RequiredMediaSlots.map((slot) => {
  const candidates = filesByStem.get(slot.canonicalStem) ?? [];
  const compatibleFiles = candidates.filter((file) => acceptsKind(slot.kind, file));
  const incompatibleFiles = candidates.filter((file) => !acceptsKind(slot.kind, file));

  if (compatibleFiles.length > 1) {
    ambiguities.push({id: slot.id, canonicalStem: slot.canonicalStem, compatibleFiles});
  }
  if (incompatibleFiles.length > 0) {
    incompatibilities.push({
      id: slot.id,
      canonicalStem: slot.canonicalStem,
      kind: slot.kind,
      incompatibleFiles,
    });
  }

  // Exactly one kind-compatible file is required. Zero stays missing; two or more stay
  // unresolved so extension order can never silently decide which real memory is used.
  const file = compatibleFiles.length === 1 ? compatibleFiles[0] : null;
  return {
    id: slot.id,
    chapterId: slot.chapterId,
    label: slot.label,
    kind: slot.kind,
    canonicalStem: slot.canonicalStem,
    file,
    staticFilePath: file ? `profile/${file}` : null,
    extension: file ? extname(file).toLowerCase() : null,
    resolved: Boolean(file),
  };
});

const snapshot = {
  schemaVersion: 'profile-v1-runtime-media/v2',
  authority: 'GENERATED_FROM_CANONICAL_PROFILE_MEDIA_DIRECTORY',
  sourceDirectory: relative(studioRoot, mediaRoot).replaceAll('\\', '/'),
  expectedCount: slots.length,
  resolvedCount: slots.filter((slot) => slot.resolved).length,
  missingCount: slots.filter((slot) => !slot.resolved).length,
  ambiguousCount: ambiguities.length,
  incompatibleCount: incompatibilities.length,
  ambiguities,
  incompatibilities,
  slots,
};

const output = `// AUTO-GENERATED by scripts/sync-profile-v1-runtime-media.mts\n// Source authority: public/profile + src/data/profileV1ProductionPlan.ts. Do not edit by hand.\n\nexport const profileV1RuntimeMedia = ${JSON.stringify(snapshot, null, 2)} as const;\n`;

if (process.argv.includes('--write')) {
  writeFileSync(outputPath, output, 'utf8');
  console.log(
    `Profile V1 runtime media synced: ${snapshot.resolvedCount}/${snapshot.expectedCount}; ` +
      `ambiguous=${snapshot.ambiguousCount}; incompatible=${snapshot.incompatibleCount}`,
  );
  process.exit(0);
}

if (!existsSync(outputPath)) {
  console.error('Profile V1 runtime media generated file missing. Run: node --no-warnings scripts/sync-profile-v1-runtime-media.mts --write');
  process.exit(1);
}

const current = await import('node:fs').then(({readFileSync}) => readFileSync(outputPath, 'utf8'));
if (current !== output) {
  console.error(
    `Profile V1 runtime media stale: ${snapshot.resolvedCount}/${snapshot.expectedCount}; ` +
      `ambiguous=${snapshot.ambiguousCount}; incompatible=${snapshot.incompatibleCount}`,
  );
  console.error('Run: node --no-warnings scripts/sync-profile-v1-runtime-media.mts --write');
  process.exit(1);
}

console.log(
  `Profile V1 runtime media current: ${snapshot.resolvedCount}/${snapshot.expectedCount}; ` +
    `ambiguous=${snapshot.ambiguousCount}; incompatible=${snapshot.incompatibleCount}`,
);
