import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function flag(name:string){return process.argv.includes(`--${name}`);}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
function load(path:string,code:string){if(!existsSync(path))throw new Error(`${code}_NOT_FOUND:${path}`);try{return JSON.parse(readFileSync(path,"utf8"));}catch{throw new Error(`${code}_INVALID:${path}`);}}
function add(list:string[],code:string,detail?:string){list.push(detail?`${code}:${detail}`:code);}
const selectionArg=arg("selection");if(!selectionArg){console.error("BGM_RHYTHM_HUMAN_SELECTION_CURRENTNESS_SELECTION_REQUIRED");process.exit(1);}const selectionPath=resolve(selectionArg);let selection:any;try{selection=load(selectionPath,"BGM_RHYTHM_HUMAN_SELECTION_CURRENTNESS_SELECTION");}catch(e){console.error(e instanceof Error?e.message:String(e));process.exit(1);}const mismatches:string[]=[];
if(selection.schemaVersion!=="wedding-movie-bgm-rhythm-human-selection/v1"||selection.authority!=="HUMAN_SELECTED_BGM_CUE_AND_CURRENT_RHYTHM_EVENT_FOR_MANUAL_EDIT")add(mismatches,"SELECTION_SCHEMA_MISMATCH");if(selection.projectId!=="opening"&&selection.projectId!=="profile")add(mismatches,"SELECTION_PROJECT_INVALID");if(selection.selection?.performed!==true||selection.summary?.humanSelection!=="PERFORMED"||selection.summary?.automaticSnapApplied!==false||selection.summary?.editApplied!==false||selection.evidenceBoundary?.humanSelectionPerformed!==true||selection.evidenceBoundary?.automaticEditPointSelection!==false||selection.evidenceBoundary?.automaticSnapApplied!==false||selection.evidenceBoundary?.editApplied!==false||selection.evidenceBoundary?.remotionStudioGuiActual!=="NOT_RUN"||selection.evidenceBoundary?.palmierGuiActual!=="NOT_RUN"||selection.evidenceBoundary?.macDaVinciGuiActual!=="NOT_RUN"||selection.evidenceBoundary?.productionReady!==false)add(mismatches,"SELECTION_EVIDENCE_BOUNDARY_INVALID");
const alignmentPath=selection.source?.alignmentPath?resolve(selection.source.alignmentPath):null;let alignment:any=null;if(!alignmentPath||!existsSync(alignmentPath))add(mismatches,"ALIGNMENT_MISSING",String(alignmentPath??"null"));else{if(sha256(alignmentPath)!==selection.source?.alignmentSha256)add(mismatches,"ALIGNMENT_SHA_DRIFT");try{alignment=JSON.parse(readFileSync(alignmentPath,"utf8"));}catch{add(mismatches,"ALIGNMENT_INVALID");}}
const currentnessPath=selection.source?.alignmentCurrentnessPath?resolve(selection.source.alignmentCurrentnessPath):null;let currentness:any=null;if(!currentnessPath||!existsSync(currentnessPath))add(mismatches,"ALIGNMENT_CURRENTNESS_MISSING",String(currentnessPath??"null"));else{if(sha256(currentnessPath)!==selection.source?.alignmentCurrentnessSha256)add(mismatches,"ALIGNMENT_CURRENTNESS_SHA_DRIFT");try{currentness=JSON.parse(readFileSync(currentnessPath,"utf8"));}catch{add(mismatches,"ALIGNMENT_CURRENTNESS_INVALID");}}
if(alignment){if(alignment.schemaVersion!=="wedding-movie-bgm-rhythm-alignment/v1"||alignment.projectId!==selection.projectId)add(mismatches,"ALIGNMENT_SCHEMA_MISMATCH");const event=alignment.events?.find((x:any)=>x.id===selection.selection?.event?.id);const cue=alignment.cues?.find((x:any)=>x.id===selection.selection?.cue?.id);if(!event)add(mismatches,"SELECTED_EVENT_MISSING");if(!cue)add(mismatches,"SELECTED_CUE_MISSING");if(event&&(Number(event.frame)!==Number(selection.selection?.event?.frame)||event.kind!==selection.selection?.event?.kind))add(mismatches,"SELECTED_EVENT_DRIFT");if(cue&&(Number(cue.frame)!==Number(selection.selection?.cue?.frame)||cue.type!==selection.selection?.cue?.type))add(mismatches,"SELECTED_CUE_DRIFT");const pair=alignment.alignmentCandidates?.find((x:any)=>x.eventId===selection.selection?.event?.id&&x.cueId===selection.selection?.cue?.id);if(!pair)add(mismatches,"SELECTED_PAIR_NO_LONGER_CANDIDATE");if(alignment.source?.rhythmPassSha256!==selection.source?.rhythmPassSha256)add(mismatches,"RHYTHM_BINDING_DRIFT");if(alignment.source?.bgmCueMapSha256!==selection.source?.bgmCueMapSha256)add(mismatches,"CUE_MAP_BINDING_DRIFT");if(alignment.source?.bgmSha256!==selection.source?.bgmSha256)add(mismatches,"BGM_BINDING_DRIFT");}
if(currentness){if(currentness.schemaVersion!=="wedding-movie-bgm-rhythm-alignment-currentness/v1"||currentness.projectId!==selection.projectId||currentness.state!=="CURRENT")add(mismatches,"ALIGNMENT_NOT_CURRENT");if(currentness.source?.alignmentSha256!==selection.source?.alignmentSha256)add(mismatches,"CURRENTNESS_ALIGNMENT_BINDING_DRIFT");if(Array.isArray(currentness.mismatches)&&currentness.mismatches.length)add(mismatches,"ALIGNMENT_CURRENTNESS_HAS_MISMATCHES");if(currentness.checks&&!Object.values(currentness.checks).every(Boolean))add(mismatches,"ALIGNMENT_CURRENTNESS_CHECK_FALSE");}
const state=mismatches.length?"STALE":"CURRENT";const output=resolve(arg("output")??`out/qa/project-real-media-preview/${selection.projectId??"unknown"}/${selection.projectId??"unknown"}-bgm-rhythm-human-selection-currentness.json`);const result={schemaVersion:"wedding-movie-bgm-rhythm-human-selection-currentness/v1",authority:"LIVE_REVALIDATION_OF_HUMAN_BGM_RHYTHM_SELECTION_AGAINST_EXACT_ALIGNMENT_AND_CUE_EVENT_PAIR",generatedAt:new Date().toISOString(),projectId:selection.projectId??null,state,source:{selectionPath,selectionSha256:existsSync(selectionPath)?sha256(selectionPath):null,alignmentPath,alignmentSha256:alignmentPath&&existsSync(alignmentPath)?sha256(alignmentPath):null,alignmentCurrentnessPath:currentnessPath,alignmentCurrentnessSha256:currentnessPath&&existsSync(currentnessPath)?sha256(currentnessPath):null},selection:{eventId:selection.selection?.event?.id??null,cueId:selection.selection?.cue?.id??null,editTarget:selection.selection?.editTarget??null},checks:{alignmentExact:!mismatches.some(x=>x.startsWith("ALIGNMENT_")&&x!=="ALIGNMENT_NOT_CURRENT"),alignmentCurrent:!mismatches.some(x=>x.startsWith("ALIGNMENT_NOT_CURRENT")||x.startsWith("CURRENTNESS_")),selectedPairExact:!mismatches.some(x=>x.startsWith("SELECTED_")),bgmBindingsExact:!mismatches.some(x=>x.endsWith("BINDING_DRIFT")),evidenceBoundaryValid:!mismatches.includes("SELECTION_EVIDENCE_BOUNDARY_INVALID")},mismatches,evidenceBoundary:{humanSelectionPerformed:true,automaticEditPointSelection:false,automaticSnapApplied:false,editApplied:false,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"CURRENT means the recorded Human cue/event choice still points to the exact same CURRENT alignment and revision-bound edit target. It does not apply the timing/transition edit or promote GUI/Human visual QA evidence."}};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({output,state,mismatchCount:mismatches.length,mismatches},null,2));if(flag("strict-current")&&state!=="CURRENT")process.exit(2);