import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function flag(name:string){return process.argv.includes(`--${name}`);}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
function load(path:string,code:string){if(!existsSync(path))throw new Error(`${code}_FILE_NOT_FOUND:${path}`);try{return JSON.parse(readFileSync(path,"utf8"));}catch{throw new Error(`${code}_JSON_INVALID:${path}`);}}
function push(items:string[],code:string,detail?:string){items.push(detail?`${code}:${detail}`:code);}
const alignmentArg=arg("alignment");const rhythmCurrentnessArg=arg("rhythm-currentness");if(!alignmentArg){console.error("BGM_RHYTHM_CURRENTNESS_ALIGNMENT_REQUIRED");process.exit(1);}if(!rhythmCurrentnessArg){console.error("BGM_RHYTHM_CURRENTNESS_RHYTHM_CURRENTNESS_REQUIRED");process.exit(1);}
const alignmentPath=resolve(alignmentArg);const rhythmCurrentnessPath=resolve(rhythmCurrentnessArg);let alignment:any;let rhythmCurrentness:any;try{alignment=load(alignmentPath,"BGM_RHYTHM_CURRENTNESS_ALIGNMENT");rhythmCurrentness=load(rhythmCurrentnessPath,"BGM_RHYTHM_CURRENTNESS_RHYTHM");}catch(error){console.error(error instanceof Error?error.message:String(error));process.exit(1);}
const mismatches:string[]=[];
if(alignment.schemaVersion!=="wedding-movie-bgm-rhythm-alignment/v1"||alignment.authority!=="DERIVED_ALIGNMENT_DISTANCES_FROM_CURRENT_RHYTHM_AND_HUMAN_BGM_CUES")push(mismatches,"ALIGNMENT_SCHEMA_MISMATCH");
if(alignment.projectId!=="opening"&&alignment.projectId!=="profile")push(mismatches,"ALIGNMENT_PROJECT_INVALID");
if(alignment.summary?.humanSelection!=="NOT_RUN"||alignment.summary?.productionReady!==false||alignment.evidenceBoundary?.humanSelectionPerformed!==false||alignment.evidenceBoundary?.remotionStudioGuiActual!=="NOT_RUN"||alignment.evidenceBoundary?.palmierGuiActual!=="NOT_RUN"||alignment.evidenceBoundary?.macDaVinciGuiActual!=="NOT_RUN")push(mismatches,"ALIGNMENT_EVIDENCE_BOUNDARY_INVALID");
if(rhythmCurrentness.schemaVersion!=="wedding-movie-production-rhythm-pass-currentness/v1"||rhythmCurrentness.authority!=="LIVE_REVALIDATION_OF_PRODUCTION_RHYTHM_PASS_AGAINST_CURRENT_RENDERED_REAL_MEDIA_PREVIEW"||rhythmCurrentness.projectId!==alignment.projectId)push(mismatches,"RHYTHM_CURRENTNESS_SCHEMA_MISMATCH");
if(rhythmCurrentness.state!=="CURRENT")push(mismatches,"RHYTHM_CURRENTNESS_NOT_CURRENT");
const rhythmPath=alignment.source?.rhythmPassPath?resolve(alignment.source.rhythmPassPath):null;
if(!rhythmPath||!existsSync(rhythmPath))push(mismatches,"RHYTHM_PASS_MISSING",String(rhythmPath??"null"));else {const live=sha256(rhythmPath);if(live!==alignment.source?.rhythmPassSha256)push(mismatches,"RHYTHM_PASS_SHA_DRIFT");if(live!==rhythmCurrentness.source?.rhythmPassSha256)push(mismatches,"RHYTHM_CURRENTNESS_BINDING_DRIFT");}
const cuePath=alignment.source?.bgmCueMapPath?resolve(alignment.source.bgmCueMapPath):null;let cueMap:any=null;if(!cuePath||!existsSync(cuePath))push(mismatches,"BGM_CUE_MAP_MISSING",String(cuePath??"null"));else {const live=sha256(cuePath);if(live!==alignment.source?.bgmCueMapSha256)push(mismatches,"BGM_CUE_MAP_SHA_DRIFT");try{cueMap=JSON.parse(readFileSync(cuePath,"utf8"));}catch{push(mismatches,"BGM_CUE_MAP_JSON_INVALID");}}
if(cueMap){if(cueMap.schemaVersion!=="wedding-movie-bgm-cue-map/v1"||cueMap.authority!=="HUMAN_MARKED_BGM_CUES_BOUND_TO_CURRENT_APPROVED_AUDIO"||cueMap.projectId!==alignment.projectId)push(mismatches,"BGM_CUE_MAP_SCHEMA_MISMATCH");if(cueMap.revision!==alignment.revision&&false)push(mismatches,"UNUSED");const audioPath=cueMap.source?.audioPath?resolve(cueMap.source.audioPath):null;if(!audioPath||!existsSync(audioPath))push(mismatches,"BGM_AUDIO_MISSING",String(audioPath??"null"));else {const liveAudio=sha256(audioPath);if(liveAudio!==cueMap.source?.audioSha256)push(mismatches,"BGM_AUDIO_SHA_DRIFT");if(liveAudio!==alignment.source?.bgmSha256)push(mismatches,"ALIGNMENT_BGM_BINDING_DRIFT");}}
const previewPath=alignment.source?.previewManifestPath?resolve(alignment.source.previewManifestPath):null;if(!previewPath||!existsSync(previewPath))push(mismatches,"PREVIEW_MANIFEST_MISSING",String(previewPath??"null"));else {const live=sha256(previewPath);if(live!==alignment.source?.previewManifestSha256)push(mismatches,"PREVIEW_MANIFEST_SHA_DRIFT");if(live!==rhythmCurrentness.source?.previewManifestSha256)push(mismatches,"PREVIEW_CURRENTNESS_BINDING_DRIFT");}
const state=mismatches.length===0?"CURRENT":"STALE";const output=resolve(arg("output")??`out/qa/project-real-media-preview/${alignment.projectId??"unknown"}/${alignment.projectId??"unknown"}-bgm-rhythm-alignment-currentness.json`);const result={schemaVersion:"wedding-movie-bgm-rhythm-alignment-currentness/v1",authority:"LIVE_REVALIDATION_OF_BGM_RHYTHM_ALIGNMENT_AGAINST_CURRENT_RHYTHM_AND_AUDIO",generatedAt:new Date().toISOString(),projectId:alignment.projectId??null,state,source:{alignmentPath,alignmentSha256:existsSync(alignmentPath)?sha256(alignmentPath):null,rhythmCurrentnessPath,rhythmCurrentnessSha256:existsSync(rhythmCurrentnessPath)?sha256(rhythmCurrentnessPath):null,rhythmPassPath:rhythmPath,rhythmPassSha256:rhythmPath&&existsSync(rhythmPath)?sha256(rhythmPath):null,bgmCueMapPath:cuePath,bgmCueMapSha256:cuePath&&existsSync(cuePath)?sha256(cuePath):null,previewManifestPath:previewPath,previewManifestSha256:previewPath&&existsSync(previewPath)?sha256(previewPath):null,bgmSha256:cueMap?.source?.audioPath&&existsSync(resolve(cueMap.source.audioPath))?sha256(resolve(cueMap.source.audioPath)):null},checks:{rhythmCurrent:!mismatches.some((x)=>x.startsWith("RHYTHM_")),cueMapCurrent:!mismatches.some((x)=>x.startsWith("BGM_CUE_")),bgmCurrent:!mismatches.some((x)=>x.startsWith("BGM_AUDIO_")||x.startsWith("ALIGNMENT_BGM_")),previewCurrent:!mismatches.some((x)=>x.startsWith("PREVIEW_")),evidenceBoundaryValid:!mismatches.includes("ALIGNMENT_EVIDENCE_BOUNDARY_INVALID")},mismatches,evidenceBoundary:{humanSelectionPerformed:false,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"CURRENT proves only that the alignment still references the exact CURRENT rhythm authority, preview manifest, Human cue map, and BGM bytes. It never chooses an edit point, judges musical quality, or promotes Human/GUI Actual evidence."}};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({output,state,mismatchCount:mismatches.length,mismatches},null,2));if(flag("strict-current")&&state!=="CURRENT")process.exit(2);