import {createHash} from "node:crypto";
import {existsSync,readFileSync,writeFileSync,mkdirSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function fail(code:string,detail?:string):never{console.error(`${code}${detail?`: ${detail}`:""}`);process.exit(1);}
function load(path:string,code:string){if(!existsSync(path))fail(`${code}_NOT_FOUND`,path);try{return JSON.parse(readFileSync(path,"utf8"));}catch{fail(`${code}_INVALID`,path);}}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
const handoffArg=arg("handoff");if(!handoffArg)fail("NLE_MARKER_CURRENTNESS_HANDOFF_REQUIRED");const handoffPath=resolve(handoffArg);const handoff=load(handoffPath,"NLE_MARKER_CURRENTNESS_HANDOFF");if(handoff.schemaVersion!=="wedding-movie-nle-musical-marker-handoff/v1"||handoff.authority!=="CURRENT_MUSICAL_AND_MOVIE_MARKERS_FOR_PALMIER_DAVINCI_HANDOFF")fail("NLE_MARKER_CURRENTNESS_SCHEMA_MISMATCH");
const mismatches:string[]=[];function check(cond:boolean,code:string){if(!cond)mismatches.push(code);}
const alignmentPath=resolve(String(handoff.source?.alignmentPath??""));const currentnessPath=resolve(String(handoff.source?.alignmentCurrentnessPath??""));check(existsSync(alignmentPath),"ALIGNMENT_MISSING");check(existsSync(currentnessPath),"ALIGNMENT_CURRENTNESS_MISSING");let alignment:any=null;let currentness:any=null;if(existsSync(alignmentPath)){alignment=load(alignmentPath,"NLE_MARKER_CURRENTNESS_ALIGNMENT");check(sha256(alignmentPath)===handoff.source?.alignmentSha256,"ALIGNMENT_SHA_DRIFT");check(alignment.projectId===handoff.projectId,"ALIGNMENT_PROJECT_DRIFT");check(Number(alignment.fps)===Number(handoff.fps),"FPS_DRIFT");check(alignment.source?.bgmSha256===handoff.source?.bgmSha256,"BGM_SHA_DRIFT");check(alignment.source?.rhythmPassSha256===handoff.source?.rhythmPassSha256,"RHYTHM_PASS_SHA_DRIFT");check(alignment.source?.bgmCueMapSha256===handoff.source?.bgmCueMapSha256,"BGM_CUE_MAP_SHA_DRIFT");}
if(existsSync(currentnessPath)){currentness=load(currentnessPath,"NLE_MARKER_CURRENTNESS_ALIGNMENT_CURRENTNESS");check(sha256(currentnessPath)===handoff.source?.alignmentCurrentnessSha256,"ALIGNMENT_CURRENTNESS_SHA_DRIFT");check(currentness.state==="CURRENT","ALIGNMENT_NOT_CURRENT");check(currentness.source?.alignmentSha256===handoff.source?.alignmentSha256,"ALIGNMENT_CURRENTNESS_BINDING_STALE");}
const selectionPathValue=handoff.source?.humanSelectionPath;if(selectionPathValue){const selectionPath=resolve(String(selectionPathValue));check(existsSync(selectionPath),"HUMAN_SELECTION_MISSING");if(existsSync(selectionPath)){const selection=load(selectionPath,"NLE_MARKER_CURRENTNESS_HUMAN_SELECTION");check(sha256(selectionPath)===handoff.source?.humanSelectionSha256,"HUMAN_SELECTION_SHA_DRIFT");check(selection.projectId===handoff.projectId,"HUMAN_SELECTION_PROJECT_DRIFT");check(selection.source?.alignmentSha256===handoff.source?.alignmentSha256,"HUMAN_SELECTION_ALIGNMENT_STALE");check(selection.selection?.performed===true,"HUMAN_SELECTION_NOT_PERFORMED");}}
const markerIds=new Set<string>();for(const m of handoff.markers??[]){check(Number.isInteger(Number(m.frame))&&Number(m.frame)>=0,"MARKER_FRAME_INVALID");check(typeof m.timecode==="string"&&/^\d{2}:\d{2}:\d{2}:\d{2}$/.test(m.timecode),"MARKER_TIMECODE_INVALID");check(!markerIds.has(String(m.id)),"MARKER_ID_DUPLICATE");markerIds.add(String(m.id));if(m.category==="BGM_CUE")check(m.source?.bgmSha256===handoff.source?.bgmSha256,"MARKER_BGM_SHA_DRIFT");}
const state=mismatches.length?"STALE":"CURRENT";const output=resolve(arg("output")??handoffPath.replace(/\.json$/,"-currentness.json"));const result={schemaVersion:"wedding-movie-nle-musical-marker-handoff-currentness/v1",authority:"LIVE_REVALIDATION_OF_NLE_MUSICAL_MARKER_HANDOFF_INPUT_IDENTITIES",generatedAt:new Date().toISOString(),projectId:handoff.projectId,state,source:{handoffPath,handoffSha256:sha256(handoffPath),alignmentSha256:handoff.source?.alignmentSha256,alignmentCurrentnessSha256:handoff.source?.alignmentCurrentnessSha256,humanSelectionSha256:handoff.source?.humanSelectionSha256??null,bgmSha256:handoff.source?.bgmSha256},mismatches,summary:{markerCount:Array.isArray(handoff.markers)?handoff.markers.length:0,palmierImportActual:"NOT_RUN",daVinciImportActual:"NOT_RUN",productionReady:false},evidenceBoundary:{palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"CURRENT means the marker sidecar is still bound to the exact alignment/currentness/optional Human selection inputs. It does not prove Palmier or DaVinci GUI import."}};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({output,state,mismatches,markerCount:result.summary.markerCount,palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false},null,2));if(arg("strict-current")!==null&&state!=="CURRENT")process.exit(2);