import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function fail(code:string,detail?:string):never{console.error(`${code}${detail?`: ${detail}`:""}`);process.exit(1);}
function load(path:string,code:string){if(!existsSync(path))fail(`${code}_NOT_FOUND`,path);try{return JSON.parse(readFileSync(path,"utf8"));}catch{fail(`${code}_INVALID`,path);}}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
function stableSha(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
function tc(frame:number,fps:number){const total=Math.max(0,Math.round(frame));const f=total%fps;const seconds=Math.floor(total/fps);const s=seconds%60;const minutes=Math.floor(seconds/60);const m=minutes%60;const h=Math.floor(minutes/60);return [h,m,s,f].map((x)=>String(x).padStart(2,"0")).join(":");}
function csv(v:unknown){const s=String(v??"");return `"${s.replaceAll('"','""')}"`;}
const alignmentArg=arg("alignment");const currentnessArg=arg("alignment-currentness");if(!alignmentArg)fail("NLE_MARKER_HANDOFF_ALIGNMENT_REQUIRED");if(!currentnessArg)fail("NLE_MARKER_HANDOFF_CURRENTNESS_REQUIRED");
const alignmentPath=resolve(alignmentArg);const currentnessPath=resolve(currentnessArg);const alignment=load(alignmentPath,"NLE_MARKER_HANDOFF_ALIGNMENT");const currentness=load(currentnessPath,"NLE_MARKER_HANDOFF_CURRENTNESS");
if(alignment.schemaVersion!=="wedding-movie-bgm-rhythm-alignment/v1"||alignment.authority!=="DERIVED_ALIGNMENT_DISTANCES_FROM_CURRENT_RHYTHM_AND_HUMAN_BGM_CUES")fail("NLE_MARKER_HANDOFF_ALIGNMENT_SCHEMA_MISMATCH");
if(currentness.schemaVersion!=="wedding-movie-bgm-rhythm-alignment-currentness/v1"||currentness.authority!=="LIVE_REVALIDATION_OF_BGM_RHYTHM_ALIGNMENT_AGAINST_CURRENT_RHYTHM_AND_AUDIO"||currentness.projectId!==alignment.projectId||currentness.state!=="CURRENT")fail("NLE_MARKER_HANDOFF_ALIGNMENT_NOT_CURRENT");
const alignmentSha=sha256(alignmentPath);const currentnessSha=sha256(currentnessPath);if(currentness.source?.alignmentSha256!==alignmentSha)fail("NLE_MARKER_HANDOFF_CURRENTNESS_BINDING_STALE");
const selectionArg=arg("human-selection");let selection:any=null;let selectionPath:string|null=null;let selectionSha:string|null=null;if(selectionArg){selectionPath=resolve(selectionArg);selection=load(selectionPath,"NLE_MARKER_HANDOFF_HUMAN_SELECTION");selectionSha=sha256(selectionPath);if(selection.schemaVersion!=="wedding-movie-bgm-rhythm-human-selection/v1"||selection.authority!=="HUMAN_SELECTED_BGM_CUE_AND_CURRENT_RHYTHM_EVENT_FOR_MANUAL_EDIT"||selection.projectId!==alignment.projectId||selection.source?.alignmentSha256!==alignmentSha||selection.selection?.performed!==true)fail("NLE_MARKER_HANDOFF_HUMAN_SELECTION_STALE");}
const fps=Number(alignment.fps);if(!Number.isInteger(fps)||fps<=0)fail("NLE_MARKER_HANDOFF_FPS_INVALID");
const markers:any[]=[];
for(const cue of alignment.cues??[]){markers.push({id:`bgm:${cue.id}`,category:"BGM_CUE",subtype:cue.type,label:cue.label||cue.type,frame:Number(cue.frame),seconds:Number(cue.frame)/fps,timecode:tc(Number(cue.frame),fps),source:{cueId:cue.id,bgmSha256:alignment.source?.bgmSha256},humanMarked:true});}
for(const event of alignment.events??[]){const base={id:`movie:${event.id}`,category:"MOVIE_EVENT",subtype:event.kind,label:event.kind.replaceAll("_"," "),frame:Number(event.frame),seconds:Number(event.frame)/fps,timecode:tc(Number(event.frame),fps),humanMarked:false};if(event.kind==="TRANSITION_MIDPOINT")markers.push({...base,source:{eventId:event.id,fromSceneId:event.fromSceneId,toSceneId:event.toSceneId,fromSourceRevision:event.fromSourceRevision,toSourceRevision:event.toSourceRevision,fromTimingRevision:event.fromTimingRevision,toTimingRevision:event.toTimingRevision,transition:event.transition,durationFrames:event.durationFrames}});else markers.push({...base,source:{eventId:event.id,sceneId:event.sceneId,sourceRevision:event.sourceRevision,timingRevision:event.timingRevision}});}
if(selection){const e=selection.selection.event;const c=selection.selection.cue;markers.push({id:`decision:${selection.revision}`,category:"HUMAN_EDIT_TARGET",subtype:e.kind,label:`EDIT TARGET: ${e.id} → ${c.type} ${c.label||c.id}`,frame:Number(e.frame),seconds:Number(e.frame)/fps,timecode:tc(Number(e.frame),fps),source:{selectionRevision:selection.revision,selectionSha256:selectionSha,eventId:e.id,cueId:c.id,distanceFrames:selection.selection.distanceFrames,distanceSeconds:selection.selection.distanceSeconds,editTarget:selection.selection.editTarget},humanMarked:true});}
markers.sort((a,b)=>a.frame-b.frame||a.category.localeCompare(b.category)||a.id.localeCompare(b.id));
const identity={projectId:alignment.projectId,alignmentSha256:alignmentSha,alignmentCurrentnessSha256:currentnessSha,humanSelectionSha256:selectionSha,bgmSha256:alignment.source?.bgmSha256,fps,markers:markers.map((m)=>[m.id,m.category,m.subtype,m.frame,m.source])};
const output=resolve(arg("output")??`out/qa/project-real-media-preview/${alignment.projectId}/${alignment.projectId}-nle-musical-marker-handoff.json`);const csvOutput=resolve(arg("csv-output")??output.replace(/\.json$/,".csv"));
const result={schemaVersion:"wedding-movie-nle-musical-marker-handoff/v1",authority:"CURRENT_MUSICAL_AND_MOVIE_MARKERS_FOR_PALMIER_DAVINCI_HANDOFF",generatedAt:new Date().toISOString(),projectId:alignment.projectId,revision:stableSha(identity),fps,source:{alignmentPath,alignmentSha256:alignmentSha,alignmentCurrentnessPath:currentnessPath,alignmentCurrentnessSha256:currentnessSha,rhythmPassSha256:alignment.source?.rhythmPassSha256,bgmCueMapSha256:alignment.source?.bgmCueMapSha256,bgmSha256:alignment.source?.bgmSha256,humanSelectionPath:selectionPath,humanSelectionSha256:selectionSha},markers,summary:{markerCount:markers.length,bgmCueCount:markers.filter((m)=>m.category==="BGM_CUE").length,movieEventCount:markers.filter((m)=>m.category==="MOVIE_EVENT").length,humanEditTargetCount:markers.filter((m)=>m.category==="HUMAN_EDIT_TARGET").length,palmierImportActual:"NOT_RUN",daVinciImportActual:"NOT_RUN",productionReady:false},evidenceBoundary:{automaticBeatDetection:false,automaticEditPointSelection:false,automaticSnapApplied:false,editApplied:false,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"This handoff transports exact current Human-marked musical cues and revision-bound movie events as marker sidecars. Generating JSON/CSV is not evidence that Palmier or DaVinci imported them successfully."}};
mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);mkdirSync(dirname(csvOutput),{recursive:true});const rows=[["Timecode","Frame","Seconds","Category","Subtype","Name","Note","MarkerId"].map(csv).join(",")];for(const m of markers){const note=m.category==="HUMAN_EDIT_TARGET"?`Human-selected edit target; no automatic edit applied. ${m.source.distanceFrames}f / ${m.source.distanceSeconds}s from selected cue.`:m.category==="BGM_CUE"?"Human-marked BGM cue bound to approved audio SHA.":"Current movie rhythm event bound to Scene/timing revision.";rows.push([m.timecode,m.frame,Number(m.seconds.toFixed(6)),m.category,m.subtype,m.label,note,m.id].map(csv).join(","));}writeFileSync(csvOutput,`${rows.join("\n")}\n`);console.log(JSON.stringify({output,csvOutput,projectId:result.projectId,revision:result.revision,markerCount:markers.length,humanEditTargetCount:result.summary.humanEditTargetCount,palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false},null,2));