import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function fail(code:string,detail?:string):never{console.error(`${code}${detail?`: ${detail}`:""}`);process.exit(1);}
function load(path:string,missing:string,invalid:string){if(!existsSync(path))fail(missing,path);try{return JSON.parse(readFileSync(path,"utf8"));}catch{fail(invalid,path);}}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
function stableSha(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
const rhythmArg=arg("rhythm-pass");const cueArg=arg("bgm-cue-map");if(!rhythmArg)fail("BGM_RHYTHM_ALIGNMENT_RHYTHM_PASS_REQUIRED");if(!cueArg)fail("BGM_RHYTHM_ALIGNMENT_CUE_MAP_REQUIRED");
const rhythmPath=resolve(rhythmArg);const cuePath=resolve(cueArg);const rhythm=load(rhythmPath,"BGM_RHYTHM_ALIGNMENT_RHYTHM_PASS_NOT_FOUND","BGM_RHYTHM_ALIGNMENT_RHYTHM_PASS_INVALID");const cueMap=load(cuePath,"BGM_RHYTHM_ALIGNMENT_CUE_MAP_NOT_FOUND","BGM_RHYTHM_ALIGNMENT_CUE_MAP_INVALID");
if(rhythm.schemaVersion!=="wedding-movie-production-rhythm-pass/v1"||rhythm.authority!=="DERIVED_WHOLE_PROJECT_RHYTHM_MAP_FROM_CURRENT_RENDERED_REAL_MEDIA_PREVIEW")fail("BGM_RHYTHM_ALIGNMENT_RHYTHM_SCHEMA_MISMATCH");
if(cueMap.schemaVersion!=="wedding-movie-bgm-cue-map/v1"||cueMap.authority!=="HUMAN_MARKED_BGM_CUES_BOUND_TO_CURRENT_APPROVED_AUDIO")fail("BGM_RHYTHM_ALIGNMENT_CUE_SCHEMA_MISMATCH");
if(rhythm.projectId!==cueMap.projectId)fail("BGM_RHYTHM_ALIGNMENT_PROJECT_MISMATCH");
if(rhythm.evidenceBoundary?.remotionStudioGuiActual!=="NOT_RUN"||cueMap.evidenceBoundary?.remotionStudioGuiActual!=="NOT_RUN"||cueMap.evidenceBoundary?.palmierGuiActual!=="NOT_RUN"||cueMap.evidenceBoundary?.macDaVinciGuiActual!=="NOT_RUN")fail("BGM_RHYTHM_ALIGNMENT_EVIDENCE_BOUNDARY_INVALID");
const fps=Number(rhythm.fps);if(fps!==Number(cueMap.audio?.fps)||fps<=0)fail("BGM_RHYTHM_ALIGNMENT_FPS_MISMATCH");
const previewPath=resolve(String(rhythm.source?.previewManifestPath??""));if(!existsSync(previewPath))fail("BGM_RHYTHM_ALIGNMENT_PREVIEW_NOT_FOUND",previewPath);if(sha256(previewPath)!==rhythm.source?.previewManifestSha256)fail("BGM_RHYTHM_ALIGNMENT_PREVIEW_SHA_DRIFT");
const preview=load(previewPath,"BGM_RHYTHM_ALIGNMENT_PREVIEW_NOT_FOUND","BGM_RHYTHM_ALIGNMENT_PREVIEW_INVALID");if(preview.identity?.bgmSha256!==cueMap.source?.audioSha256)fail("BGM_RHYTHM_ALIGNMENT_BGM_SHA_MISMATCH");
if(!Array.isArray(rhythm.scenes)||!Array.isArray(rhythm.transitions)||!Array.isArray(cueMap.cues)||cueMap.cues.length===0)fail("BGM_RHYTHM_ALIGNMENT_INPUTS_INCOMPLETE");
const cues=cueMap.cues.map((c:any)=>({id:c.id,type:c.type,label:c.label,frame:Number(c.frame),seconds:Number(c.seconds)}));
function nearest(frame:number){let best:any=null;for(const cue of cues){const distanceFrames=frame-cue.frame;const abs=Math.abs(distanceFrames);if(!best||abs<best.absDistanceFrames||(abs===best.absDistanceFrames&&cue.frame<best.cue.frame))best={cue,distanceFrames,absDistanceFrames:abs};}return {cueId:best.cue.id,cueType:best.cue.type,cueLabel:best.cue.label,cueFrame:best.cue.frame,cueSeconds:best.cue.seconds,distanceFrames:best.distanceFrames,distanceSeconds:Number((best.distanceFrames/fps).toFixed(6)),absDistanceFrames:best.absDistanceFrames};}
const events:any[]=[];
for(const scene of rhythm.scenes){const startFrame=Number(scene.startFrame);const endFrame=Number(scene.endFrameExclusive);events.push({id:`scene:${scene.sceneId}:start`,kind:"SCENE_START",sceneId:scene.sceneId,sourceRevision:scene.sourceRevision,timingRevision:scene.timingRevision,frame:startFrame,seconds:startFrame/fps,nearestCue:nearest(startFrame)});events.push({id:`scene:${scene.sceneId}:end`,kind:"SCENE_END",sceneId:scene.sceneId,sourceRevision:scene.sourceRevision,timingRevision:scene.timingRevision,frame:endFrame,seconds:endFrame/fps,nearestCue:nearest(endFrame)});}
for(const t of rhythm.transitions){const from=rhythm.scenes.find((s:any)=>s.sceneId===t.fromSceneId);const to=rhythm.scenes.find((s:any)=>s.sceneId===t.toSceneId);if(!from||!to)fail("BGM_RHYTHM_ALIGNMENT_TRANSITION_SCENE_MISSING",`${t.fromSceneId}->${t.toSceneId}`);const durationFrames=Number(t.durationFrames??0);const midpointFrame=t.transition==="CROSS_DISSOLVE"?Number(to.startFrame)+Math.floor(durationFrames/2):Number(to.startFrame);events.push({id:`edge:${t.fromSceneId}->${t.toSceneId}:mid`,kind:"TRANSITION_MIDPOINT",fromSceneId:t.fromSceneId,toSceneId:t.toSceneId,fromSourceRevision:from.sourceRevision,toSourceRevision:to.sourceRevision,fromTimingRevision:from.timingRevision,toTimingRevision:to.timingRevision,transition:t.transition,durationFrames,frame:midpointFrame,seconds:midpointFrame/fps,nearestCue:nearest(midpointFrame)});}
const alignmentCandidates=events.slice().sort((a,b)=>a.nearestCue.absDistanceFrames-b.nearestCue.absDistanceFrames||a.frame-b.frame).map((event,index)=>({rank:index+1,eventId:event.id,eventKind:event.kind,sceneId:event.sceneId??null,fromSceneId:event.fromSceneId??null,toSceneId:event.toSceneId??null,cueId:event.nearestCue.cueId,cueType:event.nearestCue.cueType,distanceFrames:event.nearestCue.distanceFrames,distanceSeconds:event.nearestCue.distanceSeconds,selectionState:"NOT_SELECTED",selectionAuthority:"HUMAN_MUST_SELECT_TARGET_EVENT_AND_CUE_BEFORE_EDIT",qualityVerdict:"NOT_RUN"}));
const identity={projectId:rhythm.projectId,rhythmPassSha256:sha256(rhythmPath),bgmCueMapSha256:sha256(cuePath),previewManifestSha256:rhythm.source.previewManifestSha256,bgmSha256:cueMap.source.audioSha256,rhythmTiming:rhythm.scenes.map((s:any)=>[s.sceneId,s.sourceRevision,s.timingRevision,s.startFrame,s.endFrameExclusive]),cueRevision:cueMap.revision};
const output=resolve(arg("output")??`out/qa/project-real-media-preview/${rhythm.projectId}/${rhythm.projectId}-bgm-rhythm-alignment.json`);const result={schemaVersion:"wedding-movie-bgm-rhythm-alignment/v1",authority:"DERIVED_ALIGNMENT_DISTANCES_FROM_CURRENT_RHYTHM_AND_HUMAN_BGM_CUES",generatedAt:new Date().toISOString(),projectId:rhythm.projectId,source:{rhythmPassPath:rhythmPath,rhythmPassSha256:sha256(rhythmPath),bgmCueMapPath:cuePath,bgmCueMapSha256:sha256(cuePath),previewManifestPath:previewPath,previewManifestSha256:sha256(previewPath),bgmSha256:cueMap.source.audioSha256},revision:stableSha(identity),fps,cues,events,alignmentCandidates,humanSelection:{performed:false,reviewer:null,reviewedAt:null,selectedEventId:null,selectedCueId:null,notes:""},summary:{eventCount:events.length,cueCount:cues.length,candidateCount:alignmentCandidates.length,humanSelection:"NOT_RUN",productionReady:false},evidenceBoundary:{automaticBeatDetection:false,automaticEditPointSelection:false,alignmentDistanceIsQualityVerdict:false,humanSelectionPerformed:false,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"Distances expose how current Scene boundaries and transition midpoints relate to Human-marked BGM cues. Ranking is proximity only, never an automatic recommendation or quality verdict. A Human must choose an event/cue before timing or transition edits."}};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({output,projectId:rhythm.projectId,revision:result.revision,eventCount:events.length,cueCount:cues.length,humanSelection:"NOT_RUN",productionReady:false},null,2));