#!/usr/bin/env node
import {createHash} from "node:crypto";
import {existsSync, readFileSync, writeFileSync} from "node:fs";
import {dirname, resolve} from "node:path";
import {mkdirSync} from "node:fs";

const args=process.argv.slice(2);
const arg=(name:string)=>{const prefix=`--${name}=`;const found=args.find((value)=>value.startsWith(prefix));return found?.slice(prefix.length)??null;};
const fail=(message:string):never=>{console.error(message);process.exit(1);};
const readJson=(path:string)=>JSON.parse(readFileSync(path,"utf8"));
const sha256=(path:string)=>createHash("sha256").update(readFileSync(path)).digest("hex");
const rhythmPath=resolve(arg("rhythm-pass")??fail("--rhythm-pass is required"));
const currentnessPath=resolve(arg("currentness")??fail("--currentness is required"));
const reviewPath=resolve(arg("human-review")??fail("--human-review is required"));
for(const path of [rhythmPath,currentnessPath,reviewPath]) if(!existsSync(path)) fail(`missing input: ${path}`);
const rhythm=readJson(rhythmPath);
const currentness=readJson(currentnessPath);
const review=readJson(reviewPath);
if(rhythm.schemaVersion!=="wedding-movie-production-rhythm-pass/v1"||rhythm.authority!=="DERIVED_WHOLE_PROJECT_RHYTHM_MAP_FROM_CURRENT_RENDERED_REAL_MEDIA_PREVIEW") fail("invalid rhythm pass authority");
if(currentness.schemaVersion!=="wedding-movie-production-rhythm-pass-currentness/v1"||currentness.authority!=="LIVE_REVALIDATION_OF_PRODUCTION_RHYTHM_PASS_AGAINST_CURRENT_RENDERED_REAL_MEDIA_PREVIEW") fail("invalid currentness authority");
if(review.schemaVersion!=="wedding-movie-production-rhythm-human-review/v1"||review.authority!=="EXPLICIT_HUMAN_WHOLE_PROJECT_RHYTHM_REVIEW_BOUND_TO_CURRENT_RHYTHM_PASS") fail("invalid Human rhythm review authority");
if(currentness.state!=="CURRENT"||!Array.isArray(currentness.mismatches)||currentness.mismatches.length!==0||!Object.values(currentness.checks??{}).every(Boolean)) fail("RHYTHM_CURRENTNESS_NOT_CURRENT");
const rhythmSha=sha256(rhythmPath);const currentnessSha=sha256(currentnessPath);
if(currentness.source?.rhythmPassSha256!==rhythmSha) fail("CURRENTNESS_RHYTHM_SHA_MISMATCH");
if(review.projectId!==rhythm.projectId||currentness.projectId!==rhythm.projectId) fail("PROJECT_ID_MISMATCH");
if(review.source?.rhythmPassSha256!==rhythmSha) fail("HUMAN_REVIEW_RHYTHM_SHA_MISMATCH");
if(review.source?.currentnessSha256!==currentnessSha) fail("HUMAN_REVIEW_CURRENTNESS_SHA_MISMATCH");
if(review.source?.previewManifestSha256!==currentness.source?.previewManifestSha256||review.source?.renderSha256!==currentness.source?.renderSha256) fail("HUMAN_REVIEW_RENDER_BINDING_MISMATCH");
if(review.review?.performed!==true||!review.review?.reviewer||!review.review?.reviewedAt) fail("HUMAN_REVIEW_NOT_PERFORMED");
if(review.summary?.allAxesReviewed!==true) fail("HUMAN_REVIEW_INCOMPLETE");
if(review.evidenceBoundary?.humanVisualQa!=="NOT_RUN"||review.evidenceBoundary?.remotionStudioGuiActual!=="NOT_RUN"||review.evidenceBoundary?.palmierGuiActual!=="NOT_RUN"||review.evidenceBoundary?.macDaVinciGuiActual!=="NOT_RUN"||review.evidenceBoundary?.productionReady!==false) fail("HUMAN_REVIEW_EVIDENCE_BOUNDARY_VIOLATION");
const scenes=new Map((rhythm.scenes??[]).map((scene:any)=>[scene.sceneId,scene]));
const binding=(sceneId:string)=>{const scene:any=scenes.get(sceneId);if(!scene)return null;return {sceneId,sourceRevision:scene.sourceRevision,timingRevision:scene.timingRevision??null,durationFrames:scene.durationFrames,durationSeconds:scene.durationSeconds,returnTo:{axis:"PACING",surface:"SCENE_TIMING_AND_A_B_COMPARE"}};};
const edgeCandidates=(rhythm.transitions??[]).map((edge:any)=>{const from:any=scenes.get(edge.fromSceneId);const to:any=scenes.get(edge.toSceneId);if(!from||!to)return null;return {fromSceneId:edge.fromSceneId,toSceneId:edge.toSceneId,fromSourceRevision:from.sourceRevision,toSourceRevision:to.sourceRevision,fromTimingRevision:from.timingRevision??null,toTimingRevision:to.timingRevision??null,transition:edge.transition,durationFrames:edge.durationFrames,durationSeconds:edge.durationSeconds,returnTo:{axis:"TRANSITION",surface:"SCENE_TIMING_AND_A_B_COMPARE",focusSceneId:edge.toSceneId,focusSourceRevision:to.sourceRevision}};}).filter(Boolean);
const mechanicalItems=(rhythm.mechanicalReviewCues??[]).map((cue:any,index:number)=>{const sceneIds=[cue.sceneId,cue.fromSceneId,cue.toSceneId].filter((value:string|undefined,pos:number,all:(string|undefined)[])=>!!value&&all.indexOf(value)===pos) as string[];return {id:`MECHANICAL-${String(index+1).padStart(3,"0")}`,kind:"MECHANICAL_CUE",code:cue.code,rule:cue.rule,sceneBindings:sceneIds.map(binding).filter(Boolean),selectionAuthority:"MECHANICAL_CUE_ONLY_NOT_QUALITY_VERDICT",qualityVerdict:null};});
const failedAxes=Object.entries(review.review.axes??{}).filter(([,value]:any)=>value?.verdict==="FAIL").map(([axis,value]:any)=>({axis,notes:value.notes??""}));
const scopeFor=(axis:string)=>axis==="openingPace"?"OPENING_SECTION":axis==="midsectionVariety"?"MIDSECTION":axis==="emotionalHold"?"HUMAN_SELECTED_EMOTIONAL_MOMENT":axis==="endingBreathingRoom"?"ENDING_SECTION":axis==="transitionCadence"?"TRANSITION_EDGES":"WHOLE_PROJECT";
const humanItems=failedAxes.map(({axis,notes},index)=>({id:`HUMAN-${String(index+1).padStart(3,"0")}`,kind:"HUMAN_AXIS_FAIL",axis,notes,scope:scopeFor(axis),sceneBindings:[],edgeCandidates:axis==="transitionCadence"?edgeCandidates:[],selectionAuthority:"HUMAN_MUST_SELECT_EXACT_SCENE_OR_EDGE_BEFORE_EDIT",qualityVerdict:"FAIL"}));
const output={schemaVersion:"wedding-movie-production-rhythm-correction-queue/v1",authority:"DERIVED_FROM_CURRENT_RHYTHM_PASS_AND_EXPLICIT_HUMAN_WHOLE_PROJECT_REVIEW_WITHOUT_AUTOMATIC_QUALITY_INFERENCE",generatedAt:new Date().toISOString(),projectId:rhythm.projectId,source:{rhythmPassPath:rhythmPath,rhythmPassSha256:rhythmSha,currentnessPath,currentnessSha256:currentnessSha,humanReviewPath:reviewPath,humanReviewSha256:sha256(reviewPath),previewManifestSha256:currentness.source.previewManifestSha256,renderSha256:currentness.source.renderSha256},items:[...humanItems,...mechanicalItems],summary:{humanFailedAxisCount:humanItems.length,mechanicalCueCount:mechanicalItems.length,actionableSceneBindingCount:mechanicalItems.reduce((sum:number,item:any)=>sum+item.sceneBindings.length,0),humanTransitionEdgeCandidateCount:humanItems.reduce((sum:number,item:any)=>sum+(item.edgeCandidates?.length??0),0),requiresHumanSceneSelection:humanItems.some((item:any)=>item.axis!=="transitionCadence"),requiresHumanEdgeSelection:humanItems.some((item:any)=>item.axis==="transitionCadence"),productionReady:false},evidenceBoundary:{humanRhythmReviewPerformed:true,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"Human FAIL axes remain Human judgments. Mechanical cues may bind exact current Scenes for navigation, but they are never converted into quality verdicts. Human transition cadence failures expose current revision-bound edge candidates but require explicit Human edge selection before editing; all other Human axis failures require explicit Human Scene selection."}};
const outputPath=resolve(arg("output")??`out/qa/project-real-media-preview/${rhythm.projectId}/${rhythm.projectId}-production-rhythm-correction-queue.json`);mkdirSync(dirname(outputPath),{recursive:true});writeFileSync(outputPath,`${JSON.stringify(output,null,2)}\n`);console.log(`Wedding production rhythm correction queue: ${output.items.length} item(s) -> ${outputPath}`);
