import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
function arg(name:string){const p=`--${name}=`;const v=process.argv.find((x)=>x.startsWith(p));return v?v.slice(p.length):null;}
function fail(code:string,detail?:string):never{console.error(`${code}${detail?`: ${detail}`:""}`);process.exit(1);}
function load(path:string,code:string){if(!existsSync(path))fail(`${code}_NOT_FOUND`,path);try{return JSON.parse(readFileSync(path,"utf8"));}catch{fail(`${code}_INVALID`,path);}}
function sha256(path:string){return createHash("sha256").update(readFileSync(path)).digest("hex");}
function stableSha(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
const alignmentArg=arg("alignment");const currentnessArg=arg("alignment-currentness");const selectionArg=arg("selection");if(!alignmentArg)fail("BGM_RHYTHM_HUMAN_SELECTION_ALIGNMENT_REQUIRED");if(!currentnessArg)fail("BGM_RHYTHM_HUMAN_SELECTION_CURRENTNESS_REQUIRED");if(!selectionArg)fail("BGM_RHYTHM_HUMAN_SELECTION_INPUT_REQUIRED");
const alignmentPath=resolve(alignmentArg);const currentnessPath=resolve(currentnessArg);const selectionPath=resolve(selectionArg);const alignment=load(alignmentPath,"BGM_RHYTHM_HUMAN_SELECTION_ALIGNMENT");const currentness=load(currentnessPath,"BGM_RHYTHM_HUMAN_SELECTION_CURRENTNESS");const selection=load(selectionPath,"BGM_RHYTHM_HUMAN_SELECTION_INPUT");
if(alignment.schemaVersion!=="wedding-movie-bgm-rhythm-alignment/v1"||alignment.authority!=="DERIVED_ALIGNMENT_DISTANCES_FROM_CURRENT_RHYTHM_AND_HUMAN_BGM_CUES")fail("BGM_RHYTHM_HUMAN_SELECTION_ALIGNMENT_SCHEMA_MISMATCH");if(currentness.schemaVersion!=="wedding-movie-bgm-rhythm-alignment-currentness/v1"||currentness.authority!=="LIVE_REVALIDATION_OF_BGM_RHYTHM_ALIGNMENT_AGAINST_CURRENT_RHYTHM_AND_AUDIO"||currentness.projectId!==alignment.projectId||currentness.state!=="CURRENT")fail("BGM_RHYTHM_HUMAN_SELECTION_ALIGNMENT_NOT_CURRENT");
const alignmentSha=sha256(alignmentPath);if(currentness.source?.alignmentSha256!==alignmentSha)fail("BGM_RHYTHM_HUMAN_SELECTION_CURRENTNESS_BINDING_STALE");if(selection.schemaVersion!=="wedding-movie-human-bgm-rhythm-selection/v1"||selection.projectId!==alignment.projectId||selection.humanSelected!==true)fail("BGM_RHYTHM_HUMAN_SELECTION_INPUT_SCHEMA_MISMATCH");if(selection.alignmentSha256!==alignmentSha)fail("BGM_RHYTHM_HUMAN_SELECTION_ALIGNMENT_SHA_MISMATCH");if(typeof selection.reviewer!=="string"||!selection.reviewer.trim()||typeof selection.reviewedAt!=="string"||!selection.reviewedAt.trim())fail("BGM_RHYTHM_HUMAN_SELECTION_REVIEW_METADATA_REQUIRED");
const event=alignment.events?.find((x:any)=>x.id===selection.selectedEventId);const cue=alignment.cues?.find((x:any)=>x.id===selection.selectedCueId);if(!event)fail("BGM_RHYTHM_HUMAN_SELECTION_EVENT_NOT_FOUND",String(selection.selectedEventId));if(!cue)fail("BGM_RHYTHM_HUMAN_SELECTION_CUE_NOT_FOUND",String(selection.selectedCueId));const candidate=alignment.alignmentCandidates?.find((x:any)=>x.eventId===event.id&&x.cueId===cue.id);if(!candidate)fail("BGM_RHYTHM_HUMAN_SELECTION_PAIR_NOT_CANDIDATE",`${event.id}:${cue.id}`);
const editTarget=event.kind==="TRANSITION_MIDPOINT"?{kind:"TRANSITION_EDGE",fromSceneId:event.fromSceneId,toSceneId:event.toSceneId,fromSourceRevision:event.fromSourceRevision,toSourceRevision:event.toSourceRevision,fromTimingRevision:event.fromTimingRevision,toTimingRevision:event.toTimingRevision,transition:event.transition,durationFrames:event.durationFrames}:{kind:"SCENE_TIMING",sceneId:event.sceneId,sourceRevision:event.sourceRevision,timingRevision:event.timingRevision};
const identity={projectId:alignment.projectId,alignmentSha256:alignmentSha,currentnessSha256:sha256(currentnessPath),selectedEventId:event.id,selectedCueId:cue.id,reviewer:selection.reviewer,reviewedAt:selection.reviewedAt};const output=resolve(arg("output")??`out/qa/project-real-media-preview/${alignment.projectId}/${alignment.projectId}-bgm-rhythm-human-selection.json`);const result={schemaVersion:"wedding-movie-bgm-rhythm-human-selection/v1",authority:"HUMAN_SELECTED_BGM_CUE_AND_CURRENT_RHYTHM_EVENT_FOR_MANUAL_EDIT",generatedAt:new Date().toISOString(),projectId:alignment.projectId,revision:stableSha(identity),source:{alignmentPath,alignmentSha256:alignmentSha,alignmentCurrentnessPath:currentnessPath,alignmentCurrentnessSha256:sha256(currentnessPath),rhythmPassSha256:alignment.source?.rhythmPassSha256,bgmCueMapSha256:alignment.source?.bgmCueMapSha256,bgmSha256:alignment.source?.bgmSha256},selection:{performed:true,reviewer:selection.reviewer,reviewedAt:selection.reviewedAt,notes:typeof selection.notes==="string"?selection.notes:"",event:{id:event.id,kind:event.kind,frame:event.frame,seconds:event.seconds},cue:{id:cue.id,type:cue.type,label:cue.label,frame:cue.frame,seconds:cue.seconds},distanceFrames:Number(event.frame)-Number(cue.frame),distanceSeconds:Number(((Number(event.frame)-Number(cue.frame))/Number(alignment.fps)).toFixed(6)),editTarget},summary:{humanSelection:"PERFORMED",automaticSnapApplied:false,editApplied:false,humanVisualQa:"NOT_RUN",productionReady:false},evidenceBoundary:{automaticBeatDetection:false,automaticEditPointSelection:false,automaticSnapApplied:false,editApplied:false,humanSelectionPerformed:true,humanVisualQa:"NOT_RUN",remotionStudioGuiActual:"NOT_RUN",palmierGuiActual:"NOT_RUN",macDaVinciGuiActual:"NOT_RUN",productionReady:false,rule:"This receipt persists only the Human-selected cue/event pair and exact revision-bound edit target. It does not change Scene timing, transition duration, or snap an edit point automatically."}};mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({output,projectId:alignment.projectId,revision:result.revision,eventId:event.id,cueId:cue.id,editTarget:editTarget.kind,editApplied:false,productionReady:false},null,2));