// AUTO-GENERATED by scripts/sync-profile-v1-runtime-media.mts
// Source authority: public/profile + src/data/profileV1ProductionPlan.ts. Do not edit by hand.

export const profileV1RuntimeMedia = {
  "schemaVersion": "profile-v1-runtime-media/v1",
  "authority": "GENERATED_FROM_CANONICAL_PROFILE_MEDIA_DIRECTORY",
  "sourceDirectory": "public/profile",
  "expectedCount": 17,
  "resolvedCount": 0,
  "missingCount": 17,
  "slots": [
    {"id":"departure-airport","chapterId":"departure","label":"空港","kind":"photo-or-video","canonicalStem":"departure-airport","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"departure-runway","chapterId":"departure","label":"滑走路","kind":"photo-or-video","canonicalStem":"departure-runway","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"departure-window-clouds","chapterId":"departure","label":"飛行機窓・雲","kind":"photo-or-video","canonicalStem":"departure-window-clouds","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"groom-childhood","chapterId":"separate-journeys","label":"新郎 幼少期・家族","kind":"photo","canonicalStem":"groom-childhood","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"groom-school-friends","chapterId":"separate-journeys","label":"新郎 学生・友人","kind":"photo","canonicalStem":"groom-school-friends","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"bride-childhood","chapterId":"separate-journeys","label":"新婦 幼少期・家族","kind":"photo","canonicalStem":"bride-childhood","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"bride-school-friends","chapterId":"separate-journeys","label":"新婦 学生・友人","kind":"photo","canonicalStem":"bride-school-friends","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"couple-early","chapterId":"intersection","label":"出会い・交際初期","kind":"photo","canonicalStem":"couple-early","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"couple-daily","chapterId":"intersection","label":"日常・同棲","kind":"photo","canonicalStem":"couple-daily","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"couple-trip","chapterId":"intersection","label":"二人の旅行","kind":"photo","canonicalStem":"couple-trip","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"adventure-hawaii","chapterId":"adventure","label":"ハワイ","kind":"photo","canonicalStem":"adventure-hawaii","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"adventure-trip","chapterId":"adventure","label":"旅行","kind":"photo","canonicalStem":"adventure-trip","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"adventure-dog","chapterId":"adventure","label":"犬との思い出","kind":"photo","canonicalStem":"adventure-dog","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"adventure-fun","chapterId":"adventure","label":"楽しい思い出","kind":"photo","canonicalStem":"adventure-fun","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"arrival-current-couple","chapterId":"arrival","label":"現在の二人","kind":"photo","canonicalStem":"arrival-current-couple","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"arrival-registration","chapterId":"arrival","label":"入籍","kind":"photo","canonicalStem":"arrival-registration","file":null,"staticFilePath":null,"extension":null,"resolved":false},
    {"id":"arrival-yokohama","chapterId":"arrival","label":"横浜・会場","kind":"photo-or-video","canonicalStem":"arrival-yokohama","file":null,"staticFilePath":null,"extension":null,"resolved":false}
  ]
} as const;
