// AUTO-GENERATED by scripts/sync-profile-v1-framing-verdicts.mts
// Source authority: out/qa/profile-v1-real-media-review.json Human crop/focus verdicts.
// Do not edit by hand. Missing/unapproved Human evidence intentionally resolves to null.

export type ProfileV1ApprovedFraming = {
  fit: 'cover' | 'contain';
  objectPosition?: string;
};

export const profileV1FramingVerdicts = {
  schemaVersion: 'profile-v1-framing-verdicts/v1',
  authority: 'GENERATED_FROM_HUMAN_REAL_MEDIA_REVIEW',
  sourceEvidence: null,
  approvedCount: 0,
  decisions: {
    'departure-airport': null,
    'departure-runway': null,
    'departure-window-clouds': null,
    'groom-childhood': null,
    'groom-school-friends': null,
    'bride-childhood': null,
    'bride-school-friends': null,
    'couple-early': null,
    'couple-daily': null,
    'couple-trip': null,
    'adventure-hawaii': null,
    'adventure-trip': null,
    'adventure-dog': null,
    'adventure-fun': null,
    'arrival-current-couple': null,
    'arrival-registration': null,
    'arrival-yokohama': null,
  },
} as const;

export const getProfileV1ApprovedFraming = (slotId: string): ProfileV1ApprovedFraming | null => {
  const decisions = profileV1FramingVerdicts.decisions as Record<string, ProfileV1ApprovedFraming | null>;
  return decisions[slotId] ?? null;
};
